### ISSUE TITLE
imbalance_volume

### ISSUE THREAD

**Issue by idati** [EnergieID/entsoe-py#102]
Hi,

thank you very much for this API,

I miss some date from entsoe, is it possible to get f.e. the imbalance volume?
like: "query_imbalance_volume"

Thank you very much!

**Comment by AntoBr96** [comment]
Hi,

I have the same problem. Can someone help?

Thank you very much!!!

**Comment by jimich** [comment]
some clues here: https://github.com/EnergieID/entsoe-py/issues/94

**Comment by fboerman** [comment]
I am cleaning up some issues, since this is a duplicated I will close it. lets track it in #94
