### ISSUE TITLE
Mapping for DE-LU bidding zone?

### ISSUE THREAD

**Issue by JasperGroenewoud** [EnergieID/entsoe-py#103]
Hi,

Currently, importing recent data, such as day-ahead prices, doesn't seem to work for Germany. Somewhere in 2018, that data switched from 'DE-AT-LU' to 'DE-LU'. The current 'DE' python mapping refers to the 'DE-AT-LU' zone. Any chance one could be added for the DE-LU zone? This is the one: 10Y1001A1001A82H.

Love working with the package by the way! 

Kind regards,

Jasper

**Comment by JrtPec** [comment]
That already exists! Check `mappings.py`: `DE_AT_LU`, `DE_LU` and `DE` (and some other German ones) should be in there!
