### ISSUE TITLE
Generation by unit is available but not documented

### ISSUE THREAD

**Issue by Gilles-H** [EnergieID/entsoe-py#108]
Actual generation by unit can be extracted into pandas using:
> ts = client.query_generation_per_plant(country_code, start=start,end=end, psr_type='B04', lookup_bzones=False)

Above is for gas units (B04).

For German data, you need to extract by Control Area, but surprisingly, those are classified under Bidding Zones  in the _mapping_ file:

> 'DE-50HZ': '10YDE-VE-------2',
> 'DE-AMPRION': '10YDE-RWENET---I',
> 'DE-TENNET': '10YDE-EON------1',
> 'DE-TRANSNET': '10YDE-ENBW-----N',

Meaning you need to activate the lookup_bzones:
> ts = client.query_generation_per_plant(country_code='DE-50HZ', start=start,end=end, psr_type='B04', lookup_bzones=True)

**Comment by Gilles-H** [comment]
Related to this: there is a typo in _mappings.py_. It should be written DE-AMPRION

TIMEZONE_MAPPINGS = {
    'AL': 'Europe/Tirane',
    'AT': 'Europe/Vienna',
    'BA': 'Europe/Sarajevo',
    'BE': 'Europe/Brussels',
    'BG': 'Europe/Sofia',
    'BY': 'Europe/Minsk',
    'CH': 'Europe/Zurich',
    'CZ': 'Europe/Prague',
    'DE': 'Europe/Berlin',
    'DE-50HZ': 'Europe/Berlin',
    **'DE-AMPRIRON': 'Europe/Berlin',**

**Comment by jpaduart** [comment]
The work of @JrtPec on Areas has fixed both issues.
You can now perfectly run:
ts = CONN.query_generation_per_plant(country_code = 'DE_50HZ', start = start, end = end, psr_type = 'B04')
