### ISSUE TITLE
Query through Control Area 

### ISSUE THREAD

**Issue by Researcher-Retorta** [EnergieID/entsoe-py#110]
Hello folks,

First of all I wish you are doing well through this pandemic.

 I carefully read the functions, codes an examples you share here in git and I am not able to do something.

I am trying to get "A75" data for a specific control area, since some countries have more than 1 control area. 
In my example, I am trying to get data from 50Hz, a German TSO with Eic code 10XDE-VE-TRANSMK 
(https://www.entsoe.eu/data/energy-identification-codes-eic/eic-approved-codes/). 

The code looks like the following:

from entsoe import EntsoeRawClient
import pandas as pd
import numpy as np

client0 = EntsoeRawClient(api_key= MY_TOKEN)
start = pd.Timestamp('20210301', tz='Europe/Brussels')
end = pd.Timestamp('20210302', tz='Europe/Brussels')

params = {
    'documentType': 'A75',
    'controlArea_Domain': '10XDE-VE-TRANSMK',
}

response = client0.base_request(params=params, start=start, end=end)

I also tryied the following in params:

params = {
    'documentType': 'A75',
    'in_Domain': '10YDE-VE-------2',
    'out_Domain': '10YDE-VE-------2'
}
*And also using 10XDE-VE-TRANSMK in 'in_Domain' and 'out_Domain'

Unfortunately, as a result I got a HTTPError. What am I doing wrong?
Thank you in advance

Best regards

**Comment by fboerman** [comment]
this has nothing to do with the package.

if you look at the api reference here: https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html and then under 4.4.8 (which is the only one with document type A75 so I assume thats what you meant) you can see that you are missing the parameters "psrType" and "ProcessType" on top of that it does not seem like it supports control area.

I can get it to work with these extra parameters with the given example in the docs for bidding zone CZ "10YCZ-CEPS-----N" but not with your given example of a control area

this is unfortunately a limitation of the API not of the package. I'm going to close this issue for that reason but if you have further questions feel free to @ me
