### ISSUE TITLE
Option to retrieve EIC Code from queries

### ISSUE THREAD

**Issue by florianlbcm** [EnergieID/entsoe-py#111]
Hi,

When I use the [`query_generation_per_plant`](https://github.com/EnergieID/entsoe-py/blob/master/entsoe/entsoe.py#L314) and [`query_installed_generation_capacity_per_unit`](https://github.com/EnergieID/entsoe-py/blob/master/entsoe/entsoe.py#L368) I need to also retrieve the EIC Code of the unit.

In a local fork I did it by added an argument `eic_code` in these 2 functions and then passed it to the parsers.
For the generation parser: [l.434](https://github.com/EnergieID/entsoe-py/blob/master/entsoe/parsers.py#L434)
```
    if per_plant:
        plantname = soup.find("name").text
        name.append(plantname)
        if eic_code:
            eic = soup.find("mrid", codingscheme="A01").text
            name.insert(0, eic)
```
I used insert because [here](https://github.com/EnergieID/entsoe-py/blob/e61fdaba8816c7907988017ff3c0fcc618f40af7/entsoe/parsers.py#L133) the columns are accessed in reversed order (but it doesn't really matter for now, as the parameter `nett` is not passed by these two functions to the parsers).

And for the capacity parser: [l.459](https://github.com/EnergieID/entsoe-py/blob/e61fdaba8816c7907988017ff3c0fcc618f40af7/entsoe/parsers.py#L459)
```
    extract_vals = {
        "Name": "registeredresource.name",
        "Production Type": "psrtype",
        "Bidding Zone": "inbiddingzone_domain.mrid",
        # 'Status': 'businesstype',
        "Voltage Connection Level [kV]": "voltage_powersystemresources.highvoltagelimit",
    }
    if eic_code:
        extract_vals["Eic Code"] = "registeredresource.mrid
```

I could be very nice to add something like that to the package, as actually the units does not have any unique id.

**Comment by fboerman** [comment]
hi @florianlbcm  I have added your suggestion in PR #124 but only the first suggestion. For your second suggestion it was already in the index of the output so I didnt think it was necessary.

in the future if you already did all the work of getting it to work locally creating a pull request is probably faster way to get it merged ;) but this was fun to dig through so thanks for the suggestion!
