### ISSUE TITLE
Data Import Border - Country client.query_import(country_code, start, end)

### ISSUE THREAD

**Issue by yas18** [EnergieID/entsoe-py#116]
Hello All,

I would like to ask if anyone has used the query client.query_import(country_code, start, end)

The output of the query is giving volumes for biding zones like DU_LU / DU-AT-LU ...

Is there any query to use just to have imported volumes by border countries and not by bidding zones ?

**Comment by jimich** [comment]
It's logical.
Help of this function is """"
        Adds together all incoming cross-border flows to a country
        The neighbours of a country are given by the NEIGHBOURS mapping
        """

--> so it return the net position of the bidding zone.

To retrieve the flow per border: query_scheduled_exchanges (for nominated capacity of all timeframes) or query_crossborder_flows (for measured physical flow). Note that Query_import use internally query_crossborder_flows.

**Comment by fboerman** [comment]
it seems youre question is answered so im closing this issue
