### ISSUE TITLE
SSLError when VPN is on

### ISSUE THREAD

**Issue by paolonervosi** [EnergieID/entsoe-py#122]
Hi, 
I have the following problem. 

the client `client = EntsoePandasClient(api_key="mytoken")` works properly when VPN is OFF. 

But when the VPN in ON I get the following error (for example for `client.query_generation(i, start=start,end=end, psr_type=None).tz_convert('Europe/Rome').tz_localize(None)`):

`SSLError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A75&processType=A16&in_Domain=10YAT-APG------L&securityToken="mytoken"&periodStart=201912312300&periodEnd=202001012300 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))`

Do you have any idea?

thank you very much,
Paolo

**Comment by FrankBoermanTenneT** [comment]
hi @paolonervosi from the error message it follows that your VPN setup means it does a MITM interception with a self signed certificate. This is probably setup by you sysadmin. 

this library uses the python requests library under the hood and you can tell it to trust self signed certificates as explained here: https://stackoverflow.com/a/43935319

in the case your setup uses a http proxy as well, I have solved that within TenneT with these environment variables:
```
os.environ['HTTP_PROXY'] = "http://<username>:<password>@<proxy_url>:<proxy_port>"
os.environ['HTTPS_PROXY'] = "http://<username>:<password>@<proxy_url>:<proxy_port>"
```

**Comment by paolonervosi** [comment]
thank you @FrankBoermanTenneT

**Comment by FrankBoermanTenneT** [comment]
> thank you @FrankBoermanTenneT

youre welcome!
