### ISSUE TITLE
Load Week ahead forecast document type mixup

### ISSUE THREAD

**Issue by AlexanderVenchev** [EnergieID/entsoe-py#125]
Hey folks,

I have the following issue.

I have tried accessing data[6.1.C] for 'DE_LU', for the period 2021-01-01 to 2021-08-01 and I have noticed that sometimes the Pandas client returns the Min Total Load and sometimes returns the Max Total Load.

The issue stems from the  <businessType> attribute. A60 for min A61 for max values.

Is there a plan for the "query_load_forecast" function to support choosing the bussiness type attribute ?

here's the code I execute 
```python
import pandas as pd
from entsoe import EntsoePandasClient

client = EntsoePandasClient('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')

country_code = 'DE_LU' # Germany-Luxembourg
start= pd.Timestamp('20210101', tz='Europe/Berlin')
end= pd.Timestamp('20210810', tz='Europe/Berlin')

client.query_load_forecast(country_code, start= start,end= end, process_type= 'A31')
```
and an example of the results
![image](https://user-images.githubusercontent.com/5927449/128941744-cb0c2629-10fc-4693-8ef0-3444534cccc5.png)
![image](https://user-images.githubusercontent.com/5927449/128941757-66bad0b0-62f7-4f11-a310-49ebf719c41b.png)

**Comment by fboerman** [comment]
hi @AlexanderVenchev thank you for reporting this ! It is a bug in the library that we dont parse week ahead forecasts correctly since the parser assumes there is only one timeseries instead of two. I will write a fix for this and push it

**Comment by fboerman** [comment]
@AlexanderVenchev  I have pushed a new version 0.3.8 which fixes the parser for all process types for load forecasting as well as actual load. hope that helps you and thank you for reporting the issue!
