### ISSUE TITLE
Net Generation Calculation Bug

### ISSUE THREAD

**Issue by ph-eip** [EnergieID/entsoe-py#126]
When there is no generation data and only consumption, the netting calculation fails because it falls back to taking the 'Actual Aggregated' which might not exist.

df = client.query_generation('ES', start=start, end=end, psr_type=None, nett=True)

```python

KeyError: 'Actual Aggregated'

~\anaconda3\envs\entso\lib\site-packages\entsoe\parsers.py in _calc_nett(_df)
    115                 'Actual Consumption'].fillna(0)
    116         except KeyError:
--> 117             _new = _df['Actual Aggregated']
    118         return _new
    119 
```

I presume the right fallback would be to look for either 'Actual Aggregated' or 'Actual Consumption'

If you agree, I can work on a pull request if necessary.

**Comment by fboerman** [comment]
hi @ph-eip this indeed seems like a bug. Could you provide a pull request and a sample code which triggers this situation? THen I will look into it and merge it. Thanks!

**Comment by jpaduart** [comment]
I don’t have access to a computer right now but I may have solved this issue with my latest pull request of around a month ago... 

BR,
Johan.

**Comment by fboerman** [comment]
> 
> I don’t have access to a computer right now but I may have solved this issue with my latest pull request of around a month ago... BR, Johan.

@jpaduart  oh how stupid of me I didnt check the file itself after looking at the date. You are right, if I look in the source it is indeed already fixed. I will close this issue
