### ISSUE TITLE
Is not working for me

### ISSUE THREAD

**Issue by huertamir** [EnergieID/entsoe-py#127]
I tried to execute entsoe.py and I got the following error: (i have the files exceptions, mappings, misc and parsers)

  File "C:\Users\ES09806517F\.spyder-py3\entsoe\entsoe.py", line 20, in <module>
    from entsoe.exceptions import InvalidPSRTypeError, InvalidBusinessParameterError

ModuleNotFoundError: No module named 'entsoe.exceptions'; 'entsoe' is not a package

**Comment by fboerman** [comment]
Hi,

How did you install the package?

-------- Original Message --------

**Comment by huertamir** [comment]
I saved a all files under the folder entsoe with extension .py. I also download the package: Query-ENTSOE-Data-edv0m3 (1).7z\ with both files 

i also tried to execute python3 -m pip install entsoe-py but is not working

**Comment by fboerman** [comment]
The preferred way is to use pip. If you want to download it yourself you need to make sure the folder is in the sys.path. That will solve your original question.

What is the error are you getting with pip?

-------- Original Message --------

**Comment by huertamir** [comment]
python3 -m pip install entsoe-py
  File "<ipython-input-16-75b7167be765>", line 1
    python3 -m pip install entsoe-py
               ^
SyntaxError: invalid syntax

**Comment by fboerman** [comment]
Hmm weird. I do it differently, Install pip and then install the package with "pip install entsoe-py"

The error seems to be general, maybe something is wrong with your python or shell.
-------- Original Message --------

**Comment by huertamir** [comment]
how do i install pip? this i dint do it

**Comment by fboerman** [comment]
Please refer to the official pip documentation on this

-------- Original Message --------

**Comment by huertamir** [comment]
yes i did!
but now I got this:

Successfully installed entsoe-py-0.3.7
Note: you may need to restart the kernel to use updated packages.

runfile('C:/Users/ES09806517F/.spyder-py3/entsoe/ul01_Query_ENTSOE_data.py', wdir='C:/Users/ES09806517F/.spyder-py3/entsoe')
Traceback (most recent call last):

  File "C:\Users\ES09806517F\.spyder-py3\entsoe\ul01_Query_ENTSOE_data.py", line 29, in <module>
    from entsoe import EntsoePandasClient

  File "C:\Users\ES09806517F\.spyder-py3\entsoe\entsoe.py", line 20, in <module>
    from entsoe.exceptions import InvalidPSRTypeError, InvalidBusinessParameterError

ModuleNotFoundError: No module named 'entsoe.exceptions'; 'entsoe' is not a package

**Comment by fboerman** [comment]
Did you:
Restart your kernel
Remove the folder entsoe py you downloaded earlier
Imported with "import entsoe"

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by huertamir** [comment]
ok, done
and now i download the "Query-ENTSOE-Data-edv0m3 (1).7z\" in the folder entsoe created?

**Comment by fboerman** [comment]
I don't understand what are you downloading? You don't need to download anything you need to setup an api key and fill that in. For that I would like to refer you to the entsoe docs and the readme of this repo

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by huertamir** [comment]
I mean th python code to query the data, should be located at the same url as the entsoe installed package i guess

**Comment by ph-eip** [comment]
It sounds like you are new to Python programming and would benefit from the following resource.
https://docs.python.org/3/

There you will learn how to install and import a module, e.g. entsoe, and then use that code to achieve your desired result.

**Comment by fboerman** [comment]
Yes I think it is good to look up the basics of modules and learn from that. This repo is probably not the best place for that. Again, you don't need to download anything yourself. Let pip handle that.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by huertamir** [comment]
Ok, yes you both are completely right. Many thanks for your help and sorry for the inconvenience.

**Comment by fboerman** [comment]
Not a problem!

Sent from ProtonMail mobile

-------- Original Message --------
