### ISSUE TITLE
problem with VPN

### ISSUE THREAD

**Issue by huertamir** [EnergieID/entsoe-py#128]
When doing data scrappin , ts = client.query_day_ahead_prices(country_code, start=start, end=end), i get the following error which might be related to  my company's VPN. Is there a way to solve this issue?

SSLError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A44&in_Domain=10YES-REE------0&out_Domain=10YES-REE------0&securityToken=278a7d7b-0955-4fda-af4c-7843c28305e6&periodStart=202011302300&periodEnd=202012312300 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

Thanks!

**Comment by FrankBoermanTenneT** [comment]
a quick google search gave me this: https://stackoverflow.com/a/43935319 as a possible solution. this library uses the requests library underneath
