### ISSUE TITLE
BadZipFile when fetching unavailabilities with pandas client

### ISSUE THREAD

**Issue by p-reuber** [EnergieID/entsoe-py#129]
I always get the following error message:

```
File "\main.py", line 22, in <module>
    res2 = EntsoeClientNV2(l, start, end)

  File "\EntsoeClientTeil3.py", line 55, in EntsoeClientNV2
    ts1=client.query_unavailability_of_production_units(area, start=start, end=end, docstatus=None, periodstartupdate=None, periodendupdate=None)

  File "\lib\site-packages\entsoe\entsoe.py", line 1675, in query_unavailability_of_production_units
    df = self._query_unavailability(

  File "\lib\site-packages\entsoe\entsoe.py", line 955, in year_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)

  File "\lib\site-packages\entsoe\entsoe.py", line 934, in pagination_wrapper
    df = func(*args, start=start, end=end, **kwargs)

  File "\lib\site-packages\entsoe\entsoe.py", line 1624, in _query_unavailability
    df = parse_unavailabilities(content, doctype)

  File "\lib\site-packages\entsoe\parsers.py", line 782, in parse_unavailabilities
    with zipfile.ZipFile(BytesIO(response), 'r') as arc:

  File "\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()

  File "\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file
```

`start` Timestamp('20180101', tz='Europe/Brussels')
`end` Timestamp('20180201', tz='Europe/Brussels')
`area` 10YDE-RWENET---I

Fetching unavailabilities of generation units works.

**Comment by fboerman** [comment]
hi @p-reuber with the exact same arguments as you with the latest version of the library I could not reproduce your problem:
```
client.query_unavailability_of_production_units('10YDE-RWENET---I', start=pd.Timestamp('20180101', tz='Europe/Brussels'), end=pd.Timestamp('20180201', tz='Europe/Brussels'))
                                            avail_qty  ...  start
created_doc_time                     ...                          
2018-01-16 15:45:38+01:00       216   ... 2018-01-16 15:30:00+01:00
2018-01-24 15:13:48+01:00       216   ... 2018-01-25 13:00:00+01:00
2018-01-24 15:15:57+01:00       144   ... 2018-01-26 08:00:00+01:00
[3 rows x 15 columns]
```

do you have the latest version of the library? are you running in a corporate environment with proxies or vpn?

**Comment by p-reuber** [comment]
Hi @fboerman,

I am using version 0.3.7. Yesterday, I ran the code from home over a vpn connection. This morning I ran the same code again from work and it worked. But when I tried to retrieve data for several areas for a period of half a year each, I got the error mentioned above again for the areas IT, NL, AT and 10YDE-VE-------2. However, I was able to retrieve data for BE, CH and PL. On top of that, fetching unavailabilities of generation units, even over a vpn connection, works for all of these areas.

**Comment by fboerman** [comment]
So it seems your vpn connection is interfering. This is a more general issue with python requests, there are several documented settings you can try for that.

Could you provide an exact code sample of the other cases that keep failing? What do you mean with half year period?

-------- Original Message --------

**Comment by Babybroker** [comment]
The error is thrown when the API doesn't return any data. I.E. the following will throw the BadZipFile error:  client.query_unavailability_of_production_units('NL', pd.Timestamp('20150101', tz='UTC'), pd.Timestamp('20160101', tz='UTC'))

**Comment by p-reuber** [comment]
The code I used for the other cases is:
```
query_unavailability_of_production_units("IT", start=pd.Timestamp("20180101", tz='Europe/Brussels'),end=pd.Timestamp("20180701", tz='Europe/Brussels'), docstatus=None, periodstartupdate=None, periodendupdate=None)
```

@Babybroker I also discovered the same by experimenting with different areas and periods. But I would expect a NoMatchingDataError instead of this BadZipFile error.

However, my initial problem seems to be caused by the VPN connection, since data exists for this query.

**Comment by fboerman** [comment]
> query_unavailability_of_production_units

hi @Babybroker and @p-reuber I have found the problem. for some reason on this endpoint the api does not actually return a http error for the missing data. thats why the library fails. It only starts checking for no data available when there is a http code != 200. I am not sure if this is a mistake from the api side. I have contacted entsoe via mail to ask them to confirm if this is a bug or an intended behaviour.

the intended behaviour for the library is indeed to throw an NoMatchingDataError exception. I will await entsoe response to see how to deal with this if this response is intended.

you can see the behaviour yourself by using the direct url: 
```
https://transparency.entsoe.eu/api?documentType=A77&biddingZone_domain=10YIT-GRTN-----B&securityToken=<snip>&periodStart=201712312300&periodEnd=201806302200
```
(api key stripped)

**Comment by fboerman** [comment]
hi @p-reuber I have received answer from entsoe, apparently they changed it that empty responses no longer give a http error. I disagree with their approach personally but will change the library to follow their behaviour

**Comment by fboerman** [comment]
hi @p-reuber I have release a new version which fixes this issue. Thank you for reporting it!
