### ISSUE TITLE
new bidding zone for for day ahead prices (DE-LU)

### ISSUE THREAD

**Issue by samarthiith** [EnergieID/entsoe-py#132]
Hi, 
thanks for the package. There is a new DE-AT market split there is a new code for DE-LU below

DE: 10Y1001A1001A82H, # DE-LU

Could you let me know how I can include this while getting the prices?

Thanks,
Samarth

**Comment by fboerman** [comment]
Hi

I don't understand, DE has been split from AT for years now. What split are you referring too?

Send from mobile

-------- Original Message --------

**Comment by samarthiith** [comment]
hi, 
thanks for the quick response. 
Yes, however, the BIDDING_ZONES mapping doesn't include the code for DE-AT (10Y1001A1001A82H). My guess is that is why it is not returning any prices when trying to get day-ahead prices for 2020 or 2019.

thanks,
Samarth

**Comment by fboerman** [comment]
Hi

So you mean the old code is not there? I have gotten German prices just fine but maybe I tried a different country code. From the top of my head you have DE-AT-LU for the old zone and the splitted AT and DE-LU zones for the new. De-At is not a thing? But maybe my memory is wrong here. I'll look it up when I return from holiday.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by samarthiith** [comment]
ah...sry, that was a typo. I meant DE-LU. Yeah, what you did sounds correct. Hmm...but I am not getting any prices for DE. For others, it works correctly.

**Comment by fboerman** [comment]
Have you tried DE and DE-LU as inputs?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by samarthiith** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/9819174/132244400-6abf784d-a08f-42af-bc16-d164bd3568a7.png)

**Comment by fboerman** [comment]
Try with underscore (yes I know it sounds stupid I want to fix this in the future)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by samarthiith** [comment]
hey... yeah it works now. Basically 'DE'  doesn't return any values (that was my first mistake) and DE_LU returns from 2018 and DE_LU_AT till 2018. Makes sense. 

thanks for the help. 

ps. on the readMe file (BIDDING_ZONES mapping), it would be good to update that you have already included DE_LU. 



<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SAMART~1.KUM/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SAMART~1.KUM/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">




  | 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | 2021
-- | -- | -- | -- | -- | -- | -- | --
DE_AT_LU | yes | yes | yes | yes | No Value | No Value | No Value
DE | No Value | No Value | No Value | No Value | No Value | No Value | No Value
DE_LU | No Value | No Value | No Value | yes | yes | yes | yes



</body>

</html>

**Comment by fboerman** [comment]
Great! Yeah I agree this is confusing. When I have time when I'm home I'll try to fix it. I'll leave this issue open as a reminder.

Sent from ProtonMail mobile

-------- Original Message --------
