### ISSUE TITLE
Area with code 10Y1001A1001A83F does not exist

### ISSUE THREAD

**Issue by zouss** [EnergieID/entsoe-py#134]
Hello,

I get a error when I try fetching the installed generation capacity per unit for certain countries ['HR','CY','DK','GE','DE','XK', 'LU', 'MT', 'TR','UA','UK']

Here is my code:
```
from entsoe import EntsoePandasClient
api_key = None #To be changed
client = EntsoePandasClient(api_key=api_key)
start = pd.Timestamp('20210101', tz='Europe/Paris')
end = pd.Timestamp('20211001', tz='Europe/Paris')
client.query_installed_generation_capacity_per_unit('DE', start=start, end=end, psr_type=None)
```

Here is an error example:
HTTPError: 400 Client Error: Bad Request for url: https://transparency.entsoe.eu/api?documentType=A71&processType=A33&in_Domain=10Y1001A1001A83F&securityToken={api_key}&periodStart=202012312300&periodEnd=202109302200

**Comment by fboerman** [comment]
hi @zouss please redact your apikey in the example url

it seems like this area code perhaps changed. I will try to see if I can whip up a script to match the mapping.py to the api docs. thanks for reporting!

**Comment by fboerman** [comment]
this is related to #138. I will handle it over there and close this one

**Comment by fboerman** [comment]
hi @zouss sorry I misunderstood your question. Your problem is that you should give a bidding zone. the code for 'DE' is not a bidding zone but a country. The bidding zone is 'DE_LU'. If you put that in then the code works!
