### ISSUE TITLE
Unable to extract DK generation through the API

### ISSUE THREAD

**Issue by IoannisKountouris** [EnergieID/entsoe-py#135]
Hi, 

I am trying to extract generation data for a lot of European countries. Although for some countries such as DE, GR, NO etc the code works perfectly, unfortunately for some other countries (e.g., DK) or bidding zones I am receiving an error.  Perhaps there must be a bug. 

I am attaching in the following pictures my coding syntax and formulation. 

![Variable](https://user-images.githubusercontent.com/74544307/136026440-0fcd4ee7-83ae-4312-af64-bd4a26e49924.png)
![GenerationExtractCode](https://user-images.githubusercontent.com/74544307/136026438-53243317-89f7-4e1e-a947-7ea8bf3e8a2b.png)
![Error1](https://user-images.githubusercontent.com/74544307/136026441-9b983a9b-b028-45ef-97fc-7cd91a94545a.png)

Thank you for your time and consideration in advance

**Comment by jpaduart** [comment]
Hi,

Have you tried DK_1 and DK_2 for Denmark?
Might be you only get data for the bidding zones. 
Also: always a good idea to check data availability on the transparency website first. 
Johan.

**Comment by fboerman** [comment]
Hi, did you verify that the data exists on the transparancy website?

-------- Original Message --------

**Comment by jpaduart** [comment]
Sorry, with all the 1's I thought it was 20211101:-)
Maybe you can strip it down to a few lines of code, and share them as text?

Op wo 6 okt. 2021 om 15:59 schreef IoannisKountouris <
***@***.***>:

**Comment by Babybroker** [comment]
Hi, 

I've encountered the same error when calling the onshore wind power for DE_LU. If you call 2020 and 2021 separately, the issue doesn't occur. It seems to do with the 'consumption', which is not retrieved in 2020, but is in 2021. 
end=pd.Timestamp('20211001', tz='Europe/Amsterdam')
start=pd.Timestamp('20200101', tz='Europe/Amsterdam')
data = client.query_generation('DE_LU', start=start, end=end, psr_type='B19')

**Comment by fboerman** [comment]
hi @Babybroker and @IoannisKountouris I can not really reproduce the problem so I will close this as solved then. thank you for the report!
