### ISSUE TITLE
Add additional areas in mappings

### ISSUE THREAD

**Issue by DamCET** [EnergieID/entsoe-py#138]
Hi,

I noticed that some areas are missing from the mappings. I had to include IFA and IFA2 myself. Perhaps it would be an idea to add these to the package from your side. I found the areas here: https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html (A.10 Areas) 
and just added them to the mappings: 
![image](https://user-images.githubusercontent.com/92980968/138431764-24db0f2c-c7c1-4d63-94b8-4868890268e1.png)

Thanks,
Daniel

**Comment by fboerman** [comment]
hi @DamCET I have made a script to check for new codes and added missing ones to the mapping. I will release an update to pypi soon and then you can use them.

thank you for reporting!
