### ISSUE TITLE
EntsoePandasClient.query_load returns one column, with wrong name

### ISSUE THREAD

**Issue by woutertP1** [EnergieID/entsoe-py#140]
When I do a EntsoePandasClient.query_load(), I expect a pandas.DataFrame containing two columns (6.1.B & 6.1.A). Only 6.1.A is returned, but with column name "Forecasted Load". This is confusing :-)

![image](https://user-images.githubusercontent.com/2571267/139064362-4ec8f49d-9c13-4123-935b-272768b0c821.png)

Request parameters: country=NL & date=20210930.

**Comment by fboerman** [comment]
hi @woutertP1 thank you for reporting!

After some investigation I found out this was only a cosmetic issue as the numbers were correct. but confusing indeed.

I have also updated the readme as you mentioned in #139 

to mimic the view of 6.1A&B from the web viewer I have added a helper function called query_load_and_forecast that combines the actual load and forecasted load, it will be release in 0.4.1
