### ISSUE TITLE
RO Imbalance price

### ISSUE THREAD

**Issue by jordmetz** [EnergieID/entsoe-py#143]
Hi, 
There is an issue when trying to download the imbalance prices for Romania with the method "EntsoePandasClient.query_imbalance_prices". The issue appeard on 18.11.21. Can someone fix thie issue?
Thanks
Jordan Metz

**Comment by fboerman** [comment]
Hi,

Thank you for your report. Could you please provide a clear code example of what goes wrong and please explain what you expected to happen and what happened instead.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jordmetz** [comment]
client = EntsoePandasClient(api_key=api_token)
balancing = client.query_imbalance_prices('RO',start=pd.Timestamp(datetime.strptime('2021-10-01', "%Y-%m-%d").strftime("%Y%m%d%H%M"), tz='Europe/Bucharest'),end=pd.Timestamp(datetime.strptime('2021-11-22', "%Y-%m-%d").strftime("%Y%m%d%H%M"), tz='Europe/Bucharest'))

The expected result is a pandas dataframe.
The actual resut is an exception: "No objects to concatenate"

Thanks for your quick answer

**Comment by fboerman** [comment]
Thanks, did you verify that the data actually exists by checking on the transparancy webinterface?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jordmetz** [comment]
Yes, it exists

**Comment by jordmetz** [comment]
![image](https://user-images.githubusercontent.com/94835138/142844331-cf747b3e-87a7-403c-9712-a39d50a58cd2.png)

**Comment by fboerman** [comment]
Okay thanks. I will take a look at it when I'm home.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jordmetz** [comment]
Great! Thank you!

**Comment by fboerman** [comment]
hi @jordmetz I have done a bit of debugging and it seems that this is an error from the entsoe servers. When having an end date of 21-10-2021 or after the server returns an empty zipfile. I will contact entsoe about this. It is good that the library throws an error in this case so that it is clear there is something wrong.

unrelated but as a tip to you, you do much too complicated stuff with specifying the date. The pandas library is VERY good at magically deducing inputs. I have simplified your example to the following:
```python
client = EntsoePandasClient(api_key=api_token)
balancing = client.query_imbalance_prices('RO',start=pd.Timestamp('2021-10-01', tz='Europe/Bucharest'),end=pd.Timestamp('2021-11-22', tz='Europe/Bucharest'))
```

**Comment by fboerman** [comment]
hi @jordmetz I have received answer from ENTSO-E that this is a bug on their side and they are working on a fix. If I know more ill update this issue

**Comment by jordmetz** [comment]
hi @fboerman, thank you very much for your reply, and for raising the problem to entsoe. I hope they'll fix that quickly as this data is quite critical. 
Thanks for the tip ;)

**Comment by fboerman** [comment]
hi @jordmetz youre welcome. If the data is that critical for you you can also manually look it up on the website? Or perhaps write a quick and dirty scraping script in beautifulsoup as a temporary hotfix.

**Comment by fboerman** [comment]
hi @jordmetz I have received a message from entsoe that they solved the issue and I can indeed execute the snippit just fine now. Please reopen the issue if the problem returns. Thanks for reporting!

**Comment by jordmetz** [comment]
Thank you @fboerman for the update!
