### ISSUE TITLE
query_unavailability_of_generation_units getting stuck at 2020-07-06 07:00 for France

### ISSUE THREAD

**Issue by tim-glitch** [EnergieID/entsoe-py#146]
When querying the query_unavailability_of_generation_units for France, the program gets stuck at  2020-07-06 07:00.  I think the reason is that there are more than 200 elements in this hour. This is the debug info I get:

 The API is limited to 200 elements per request. This query requested for 204 documents and cannot be fulfilled as is.

Is it possible to add the offset parameter described in 4.7.2 in https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_generation_domain so that it is possible to query more than 200 elements when needed?

**Comment by fboerman** [comment]
hi @tim-glitch yes that seems like a good resolution. I dont have the time currently to do it myself, but if you want you can provide a pull request that I can review.

you can also provide a code snippit to recreate your problem and once I have some time I can take a look

**Comment by tim-glitch** [comment]
Fix is merged
