### ISSUE TITLE
Why isn't the UK on the list of countries?

### ISSUE THREAD

**Issue by AlejandroElBecario** [EnergieID/entsoe-py#149]
Sorry if the question is very obvious i am a noob. This package has helped me tremendously and i would like to thank everyone who is working on it. I just don't understand why is the UK left out.

**Comment by fboerman** [comment]
hi @AlejandroElBecario I am not sure what you mean. There is a mapping for GB as well as multiple virtual bidding zones regarding the HVDC cables. please note however that many data items have stopped being reported to entsoe after brexit became effective at 2021-01-01 at the ending of the transition period.

**Comment by AlejandroElBecario** [comment]
Hi @fboerman ! Well my problem was that, in my code, i had an query like:

df_horario = client.query_generation(country_code,start=start,end=end)

And it wasn't working (Error = list index out of range) because there is no "UK" in the list of Domain Mappings. I understand by your answer that GB is basically "Great Britan" or something like that?

**Comment by AlejandroElBecario** [comment]
Ok perfect! Now it is working with GB. The problem was that i was required to bring data from "UK" as a whole, never crossed my mind the possibility that GB was that hahahah.

Thanks for the help!
