### ISSUE TITLE
lookup_bzones in query imbalance prices

### ISSUE THREAD

**Issue by gjertro** [EnergieID/entsoe-py#15]
Hello,

great job, this package helped me alot! 

Can you add lookup_bzones logic to other queries as well? I see data exist for:
query_imbalance_prices,
query_generation,
query_wind_and_solar_forecast,
query_installed_generation_capacity,

**Comment by gjertro** [comment]
yea, found out that this is why we have pull-requests.

**Comment by JrtPec** [comment]
Feel free to open a pull request! Even if it doesn't merge 100%, I can have a look and help you out.
