### ISSUE TITLE
NO_3 missing from NO_4 neighbours 

### ISSUE THREAD

**Issue by timonviola** [EnergieID/entsoe-py#150]
```
--- snipet ---
 'NO_3': ['NO_4', 'NO_5', 'SE_2'],
 'NO_4': ['SE_2', 'FI', 'SE_1'],
```
NO_3 should be part of the NO_4 neighbours

**Comment by timonviola** [comment]
If you agree, I can make a PR 🙂

**Comment by fboerman** [comment]
hi @timonviola yes a PR would be the best way, I dont have much time myself. This seems like a correct change indeed!
