### ISSUE TITLE
Missing mapping for new cable NO2-GB and for area NO2NSL

### ISSUE THREAD

**Issue by grotteru** [EnergieID/entsoe-py#154]
Hi,

Due to the new auction for the NSL cable there is actually calculated a new price for NO2 for a new area NO2NSL. This area is present at the Transparancy platform and the code for the area is: 50Y0JVU59B4JWQCU

I am able to retrieve data from the API with this request:
https://transparency.entsoe.eu/api?securityToken=<TOKEN>&documentType=A44&in_Domain=50Y0JVU59B4JWQCU&out_Domain=50Y0JVU59B4JWQCU&periodStart=202112312300&periodEnd=202209302300
![image](https://user-images.githubusercontent.com/50191995/150938354-bb6fb428-8b2e-4fd6-a133-bbe26f717793.png)

Related to this there is also a new connection between NO2 and GB under Scheduled Commercial Exchanges. I have been able to retrieve data from the API with this request (where bidding zone codes are for NO2 and GB):
https://transparency.entsoe.eu/api?securityToken=<TOKEN>&documentType=A09&in_Domain=10YNO-2--------T&out_Domain=10YGB----------A&contract_MarketAgreement.Type=A01&periodStart=202112312300&periodEnd=202209302300

![image](https://user-images.githubusercontent.com/50191995/150938614-9d3163bd-069b-432c-a69b-ed781b6a8649.png)

Will it be possible to add this to the mapping?

**Comment by fboerman** [comment]
hi @grotteru thanks for your report.
The mappings for your second case are already available as GK and NO_2

as for your first case I would like to  follow the official documented codes from here: https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html
the one you mention is not on there as far as I can see right now (2021-01-30). I will first ask them if this is an official code before adding it. In the future you can contact them yourselves btw at transparency@entsoe.eu

**Comment by fboerman** [comment]
hi @grotteru They confirmed to me the code and added to the docs. I will add it to mapping file

**Comment by grotteru** [comment]
Thank you very much @fboerman. In the future I will adress this directly to transparency@entsoe.eu
