### ISSUE TITLE
produktion=client.query_generation("DK_2", start=start,end=end, psr_type=None) giving failure

### ISSUE THREAD

**Issue by grjoni** [EnergieID/entsoe-py#162]
start = pd.Timestamp('20220101', tz='Europe/Brussels')
end = pd.Timestamp('20220201', tz='Europe/Brussels')

produktion=client.query_generation("DK_2", start=start,end=end, psr_type=None)
produktion

It works fine for this interval

Same query but longer interval ( It used to work) 

start = pd.Timestamp('20210101', tz='Europe/Brussels')
end = pd.Timestamp('20220228', tz='Europe/Brussels')

produktion=client.query_generation("DK_2", start=start,end=end, psr_type=None)
produktion

then I get this failure

lib\site-packages\pandas\core\indexes\multi.py:3559: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  result = lib.fast_unique_multiple([self._values, rvals], sort=sort)

but it works for this interval

start = pd.Timestamp('20210101', tz='Europe/Brussels')
end = pd.Timestamp('20211231', tz='Europe/Brussels')

produktion=client.query_generation("DK_2", start=start,end=end, psr_type=None)
produktion

So I worked around for this. I can se the head is multiindex in 2021 but not in 2022 maybe the reason. The work around is to fetch the periods as 2 subsets.

I hope it is clear. It was not problem week ago.

**Comment by fboerman** [comment]
hi @grjoni it is not very clear to my what your issue is. Could you please specify a code snippit that triggers your issue and explain what is going wrong compared to what you expect.

**Comment by fboerman** [comment]
hi @grjoni I see you edited your opening. its better to also comment with a tag then because otherwise I wont be notified.

as for your problem, I think this has to do with a change in the API response but I am not sure. could you try to see if the xml response is different between 2021 and 2022?

**Comment by grjoni** [comment]
Sorry to be unclear but I found out  I had reach maximum trials.

**Comment by fboerman** [comment]
hi @grjoni so I am assuming that solves your issue that you are running into rate limitations. please reopen the issue if problem persists.
