### ISSUE TITLE
Force pandas>=1.4.0 in requirements

### ISSUE THREAD

**Issue by JrtPec** [EnergieID/entsoe-py#163]
The parameter `inclusive`, used by `pd.date_range` in the `parsers`, was only introduced in pandas version 1.4.0. We should require at least that version.

**Comment by fboerman** [comment]
Hi,

I'm sorry I wasn't aware it was introduced that recently. I did that to fix the future warnings. I will update the dependencies, thank your for reporting!

-------- Original Message --------
