### ISSUE TITLE
query_crossborder_flows results in an error

### ISSUE THREAD

**Issue by EricLeer** [EnergieID/entsoe-py#164]
When using `query_crossborder_flows` I get the below error. See the below snippet. I am currently on 0.4.4, but saw the same behaviour on 0.4.3.

```
from entsoe import EntsoePandasClient

client = EntsoePandasClient(api_key=api_token)
df_crossborder = client.query_crossborder_flows(
    "NL", 
    "NO_2", 
    pd.Timestamp('20220220', tz='Europe/Brussels'), 
    pd.Timestamp('20220225', tz='Europe/Brussels')
)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/0r/z_n61jbd4xs0zhdv9n517p000000gn/T/ipykernel_3728/2036503074.py in <module>
      3 
      4 client = EntsoePandasClient(api_key=api_token)
----> 5 df_crossborder = client.query_crossborder_flows(
      6     "NL",
      7     "NO_2",

TypeError: year_wrapper() missing 2 required keyword-only arguments: 'start' and 'end'
```

**Comment by EricLeer** [comment]
Just found that the following does work. It seems to work just fine when using keyword arguments for start/end, but not when the dates are added as regular arguments.

```
from entsoe import EntsoePandasClient


client = EntsoePandasClient(api_key=api_token)
df_crossborder = client.query_crossborder_flows(
    "NL", 
    "NO_2", 
    start=pd.Timestamp('20220220', tz='Europe/Brussels'), 
    end=pd.Timestamp('20220225', tz='Europe/Brussels')
)
```

**Comment by fboerman** [comment]
Hi,

Yes that is correct and also displayed in the documentation. It has to do with the way the decorators were set up by the first author. I would like to not change such a fundamental thing.

-------- Original Message --------

**Comment by EricLeer** [comment]
Ah I see, also how it is differently labeled between EntsoeRawClient and EnstoePandasClient. But this is not something that is directly obvious from the error or the docstring. 

Would it make sense to throw a more informative error in these cases, or make the start/end kwargs in the function definition? That would make it a bit more self explorative without having to make fundamental changes!

**Comment by fboerman** [comment]
hi @EricLeer you are right I made a more specific exception now!
