### ISSUE TITLE
Pandas FutureWarning in parsers

### ISSUE THREAD

**Issue by jacob-mannhardt** [EnergieID/entsoe-py#165]
When using the parsers, two pandas FutureWarnings pop up:
1. ~\entsoe\parsers.py:631: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`. index = pd.date_range(start=start, end=end, freq=delta, closed='left') #163 
2. ~\entsoe\parsers.py:135: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

**Comment by fboerman** [comment]
hi @jacob-mannhardt the should be fixed when you update the library. the second I fixed at many places but the ones I didnt yet is code im not very familiar with and dont have the time to extensively test now. If you want you can open a PR for this to help.
