### ISSUE TITLE
Generation per unit missing mRID

### ISSUE THREAD

**Issue by p-reuber** [EnergieID/entsoe-py#167]
When retrieving the actual generation per unit, the data is in the following format: code: `client.query_generation_per_plant("AT", start=pd.Timestamp("20200801", tz="CET"), end=pd.Timestamp("20200801", tz="CET"), psr_type="B04")   `

<img width="498" alt="image" src="https://user-images.githubusercontent.com/89388522/157278277-dbe9aee1-08e4-40bf-a2fc-547f0b86b80a.png">

Here, only the name of the power plant is given in the first level of the column name. Unfortunately, the names of the power plants can be ambiguous, for instance the plant "Häusling" has the plant code '14W-TZH-TU-----N' and '14W-TZH-KW-----7'. The plant code is available in the response of the server. May be it is possible to add this information here to remove the ambiguity. The easiest way I can think of is to add another level to the Column MultiIndex.

**Comment by fboerman** [comment]
hi @p-reuber some similar was already suggested in #159 lets keep the discussion in there.
