### ISSUE TITLE
TypeError: _generate_range() got an unexpected keyword argument 'inclusive'

### ISSUE THREAD

**Issue by AndreasBordvik** [EnergieID/entsoe-py#168]
Hi. 
Not able to download data from the API. I get the following TypeError:
[TypeError: _generate_range() got an unexpected keyword argument 'inclusive']()

 
See screenshot of Traceback:
![image](https://user-images.githubusercontent.com/35432806/157390874-1262dc20-4413-425f-871f-bc282a03d908.png)

Br
David Andreas

**Comment by fboerman** [comment]
Hi,

Please update your pandas. The required version for this package is too low, I will fix that soon.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by AndreasBordvik** [comment]
Thanks. This solved the issue!

I get a FutureWarning for reference:

FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

I think this issue is addressed in another issues ticket.
Br

**Comment by fboerman** [comment]
hi yes the pandas requirement is handled in #163 the future warning is handled in #165

**Comment by jimich** [comment]
I got the same issue with a fresh install of 0.5.8 (pip install --upgrade --force-reinstall entsoe-py )
Pandas was however well updated to 1.4.4 with the requirements of entsoe-py
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.4
    Uninstalling pandas-1.4.4:
      Successfully uninstalled pandas-1.4.4
      (...)
      
Successfully installed beautifulsoup4-4.11.1 certifi-2022.6.15.1 charset-normalizer-2.1.1 entsoe-py-0.5.8 idna-3.3 numpy-1.23.2 pandas-1.4.4 python-dateutil-2.8.2 pytz-2022.2.1 requests-2.28.1 six-1.16.0 soupsieve-2.3.2.post1 urllib3-1.26.12

I tried also via a separate install of panda:
$ pip install pandas==1.4.4
Requirement already satisfied: pandas==1.4.4 in **/opt/conda/lib/python3.8/site-packages** (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.8/site-packages (from pandas==1.4.4) (2.8.2)
Requirement already satisfied: numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" in /opt/conda/lib/python3.8/site-packages (from pandas==1.4.4) (1.23.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.8/site-packages (from pandas==1.4.4) (2022.2.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas==1.4.4) (1.16.0)
      

But anyway got the described error, in the fonction _generate_range()  (and the path seems the same as above)
--> **/opt/conda/lib/python3.8/site-packages/panda**s/core/indexes/datetimes.py

I had to revert to an old local entsoe-py from 2021 to be able to retrieve the DAPrices.

(I'm using python on a specific JupyterLab cloud environment)

**Comment by fboerman** [comment]
hi @jimich I think that is an environment error. pandas will only return that error when its not at the latest version
