### ISSUE TITLE
client.query_installed_generation_capacity not working as expected

### ISSUE THREAD

**Issue by wes3985** [EnergieID/entsoe-py#17]
Hi, the above function seems to be not returning the expected data. here is my code:

    from entsoe import EntsoePandasClient
    import pandas as pd
    entsoe_api_key = 'my_key'
    client = EntsoePandasClient(api_key=entsoe_api_key)
    st = pd.Timestamp('20170101', tz='Europe/Brussels')
    en = pd.Timestamp('20170601', tz='Europe/Brussels')
    cc = 'DE' # Germany
    igc = client.query_installed_generation_capacity(country_code=cc, start=st, end=en)
    print(igc)

returns only a single line from 2017-01-01, I have tried with many date combinations, it always returns the first date in the range and no other dates? Many thanks

**Comment by JrtPec** [comment]
In what way is it not the expected data?

If I do [the same lookup on the Entso-e Transparency Platform](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&dateTime.dateTime=01.01.2019+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2019+00:00|UTC|YEAR&area.values=CTY|10Y1001A1001A83F!CTY|10Y1001A1001A83F&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19), I also just get a single value per year.

**Comment by wes3985** [comment]
ah my apologies, I was expecting a line whenever capacity changed throughout the year, e.g a new windfarm coming online. No worries, many thanks for your very quick response.
