### ISSUE TITLE
 FutureWarnings

### ISSUE THREAD

**Issue by VartanAhrensKayayan** [EnergieID/entsoe-py#173]
The query triggers FutureWarnings which I assume will eventually cause issues, not to mention that it is probably being deprecated for a reason. Would it be a worthwhile endeavor to trawl and make the relevant changes?

The warnings are:

FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.

**Comment by fboerman** [comment]
Hi I recently fixed some of these. Did you update to latest version?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by VartanAhrensKayayan** [comment]
Installed with anaconda navigator environments, it states that the version is 0.4.3. What is the latest?

**Comment by fboerman** [comment]
No conda is always behind. I am not sure when it updates I only publish an pypi and then conda picks it up. Probably should look into that. Anyway latest version is 0.4.5. Simply do pip install - U entsoe-py in your conda environment

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by VartanAhrensKayayan** [comment]
Updating does fix the issue. Thank you.
