### ISSUE TITLE
RemoteDisconnected error

### ISSUE THREAD

**Issue by AlejandroElBecario** [EnergieID/entsoe-py#175]
Hi! this isn't a very urgent problem but it's something that has been bothering me for a while.

So, the problem is that, when i am doing the queries **query_scheduled_exchanges** and **query_crossborder_flows** sometimes i get the error RemoteDisconnected.

This doesn't happen all the time, usually when i am querying for lots of data, like an interval of **2015-1-1** to **2022-1-1**. And even then sometimes it works perfectly well, why could this be happening?

> Connection Error, retrying in 0 seconds
> Traceback (most recent call last):
>
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
>
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

And thanks in advance!

**Comment by fboerman** [comment]
Hi alex

I had this too when I burst a lot of requests. It is probably a crude way of rate limiting. You can email the transparancy team themselves to ask about it. Its something from their server. I would like to know the answer as well.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by AlejandroElBecario** [comment]
The thing is, i talked to them about it and they told me, go raise an issue with the module of python.
I thought about adding a retry method in my code. With a max number of retries but it's already a little bit slow so i don't want to push it to far.
Anyways, if they say something else i will add it to this thread.

**Comment by fboerman** [comment]
That's weird since it's clearly a thing on their side. Yes you can specify a retry in the init of the client. But that doesn't really fix the problem

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by leostimpfle** [comment]
I'm having the same issue. Was anyone able to confirm the exact request limits? I was wondering if the decorators `day_limited` should be adjusted to reflect the limits and avoid the `ConnectionError`?

**Comment by milannnnn** [comment]
Since the `EntsoeRawClient` already implements a retry mechanism, would it make sense to add this exception (`http.client.RemoteDisconnected`) to the retry decorator as well?

While this issue originates on ENTSO-e's end, I feel that the retry mechanism should alleviate such temporary outages and try to recover from them (instead of breaking the execution flow by not handling this exception).

**Comment by fboerman** [comment]
please dont necromance on issues. Open a new issue to request your idea. I think its a good idea, will look into it when you make a new issue to track.

**Comment by milannnnn** [comment]
My bad / thanks for pointing it out. I'll open a new issue.
