### ISSUE TITLE
series.append method is depreciated - entsoe/parsers.py:138: FutureWarning

### ISSUE THREAD

**Issue by eamonn-bell** [EnergieID/entsoe-py#176]
>>> import pandas as pd
>>> from entsoe import EntsoePandasClient
>>> client = EntsoePandasClient(api_key=my_api_key)
>>> start_date = pd.Timestamp('2022-03-01', tz='Europe/London')
>>> end_date = pd.Timestamp('2022-03-23', tz='Europe/London')
>>> df_fr = client.query_generation('FR', start=start_date, end=end_date)

I run the query above and I am getting the following error:

/Users/eamonnbell/miniconda3/envs/grid/lib/python3.9/site-packages/entsoe/parsers.py:138: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series = series.append(ts)

Can this be updated without breaking everything?

**Comment by JrtPec** [comment]
This is a warning, not an error. So you won't have any issues with this anytime soon (these deprecation warnings are announced well ahead of time, no need for stress :-)

The `parsers` file has quite a few of these `append` methods. It's not exactly a *quick fix* but we should be able to replace these calls with `concat`s without too much issue.

**Comment by fboerman** [comment]
I already replaced quite a lot of them. But indeed not a high priority for the couple remaining. Its just a warning.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by eamonn-bell** [comment]
Thanks!
