### ISSUE TITLE
Water Reservoir and  Hydro Storage plants

### ISSUE THREAD

**Issue by alexDF-79** [EnergieID/entsoe-py#179]
hi
would it easy to add the option to download Water Reservoir and  Hydro Storage plants data  to the code ? 
I could not find in the list  (sorry in case is already included  and I am missing it)
More specifically I am referring to   the data reported [here ](https://transparency.entsoe.eu/generation/r2/waterReservoirsAndHydroStoragePlants/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2022+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2022+00:00|UTC|YEAR&area.values=CTY|10YIT-GRTN-----B!BZN|10Y1001A1001A73I) in entsoe  

Many thanks
Alessandro

**Comment by fboerman** [comment]
hi @alexDF-79 that is a nice idea! I was actually also interested in this data myself so I implemented it. It will be released in version 0.5.4
