### ISSUE TITLE
XMLParsedAsHTMLWarning from soup

### ISSUE THREAD

**Issue by tvandersen** [EnergieID/entsoe-py#180]
hi  :-)
while using python 3.10 / entsoe-py==0.5.4, the bf soup part raises a huge load of warning text telling me this for every call:

> C:\python310\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor...

**Comment by Retraces** [comment]
Can confirm, even adding ```features="lxml"``` to the BeautifulSoup constructor seems to still raise the error from the looks of it.

**Comment by fboerman** [comment]
hi @tvandersen that is indeed very annoying. however when I replace all instances with features='xml' or features='lxml' beautifulsoup no longer parses correctly timeseries for various endpoints. I have no idea why but for the time being I therefor inserted a warning surpressor instead.
