### ISSUE TITLE
Patchy cross-border data using query_crossborder_flows

### ISSUE THREAD

**Issue by Gilles-H** [EnergieID/entsoe-py#181]
I'll show one specific example but I've found similar issues with many different pairs, and different dates since early March. Worth mentioning my script used to work fine and I could extract all border point data within one market using loops, put them in a single dataframe before extracting the data. Now this is not possible anymore as some hours / quarters are missing here and there.

Running
> client.query_crossborder_flows('NO', 'DE', start=pd.Timestamp('20220501', tz='CET'),end=pd.Timestamp('20220502', tz='CET'))

Returns (bold added to highlight missing rows above)
> 2022-05-01 00:00:00+02:00     965.0
> 2022-05-01 00:15:00+02:00     870.0
> **2022-05-01 00:45:00+02:00     804.0**
> 2022-05-01 01:00:00+02:00     519.0
> 2022-05-01 01:15:00+02:00     443.0
> **2022-05-01 01:45:00+02:00     377.0**
> 2022-05-01 02:00:00+02:00      94.0
> 2022-05-01 02:15:00+02:00      19.0
> **2022-05-01 02:45:00+02:00      23.0**
> 2022-05-01 03:00:00+02:00      48.0
> 2022-05-01 03:15:00+02:00      56.0
> **2022-05-01 03:45:00+02:00      50.0**
> **2022-05-01 04:15:00+02:00      15.0**
> 2022-05-01 04:30:00+02:00      14.0
> 2022-05-01 04:45:00+02:00       7.0
> 2022-05-01 05:00:00+02:00       0.0
> **2022-05-01 18:00:00+02:00     294.0**
> 2022-05-01 18:15:00+02:00     400.0
> **2022-05-01 18:45:00+02:00     495.0**
> 2022-05-01 19:00:00+02:00     897.0
> 2022-05-01 19:15:00+02:00    1003.0
> **2022-05-01 19:45:00+02:00    1065.0**
> 2022-05-01 20:00:00+02:00    1332.0
> 2022-05-01 20:15:00+02:00    1404.0

Compared with the following on the ENTSOE webpage (highlights where data is missing above):
![image](https://user-images.githubusercontent.com/69864686/166915189-acc630c9-449e-4271-8234-899fdbd7f895.png)

**Comment by MattEwen** [comment]
Are you using v0.4.3? There was an error in this version where duplicate values would be deleted (see [here](https://github.com/EnergieID/entsoe-py/blob/master/entsoe/decorators.py) and [here](https://github.com/EnergieID/entsoe-py/issues/158). This has been fixed in subsequent versions, and the code doesn't look like this should happen in the current release

**Comment by Gilles-H** [comment]
Thanks Matt, the fix worked, indeed. For some reason 0.4.3 is the only version available in conda-forge. I've just updated the decorators.py file manually.
