### ISSUE TITLE
Max tries 

### ISSUE THREAD

**Issue by grjoni** [EnergieID/entsoe-py#182]
Hi

I have never had problem to extract data from the site but now I got failure messages. It is like there is max on to withdraw data from site. I tried to open the documents that is refer to failure message but the link didnt work. 

ConnectionError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A65&processType=A16&outBiddingZone_Domain=10YDK-2--------M&out_Domain=10YDK-2--------M&securityToken=712e7984-59cf-4b48-954b-515ed255119a&periodStart=201712312300&periodEnd=201812312300 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D1ACF928B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by fboerman** [comment]
issue seems to be fixed!

**Comment by fboerman** [comment]
Hi it seems there are technical issues from transparancy side. I also get server errors from time to time. Nothing we can do atm unfortunately.

Sent from ProtonMail mobile

-------- Original Message --------
