### ISSUE TITLE
Missing Values for Day Ahead Market prices

### ISSUE THREAD

**Issue by HristoNikodinovski** [EnergieID/entsoe-py#183]
start = pd.Timestamp('20210101', tz='Europe/Brussels')
end = pd.Timestamp('20210105', tz='Europe/Brussels')

Running code with parameters above will not get every single value for the DAM prices but skip some hours. Is there a solution for this problem?

**Comment by jpaduart** [comment]
Hi,
Did you check whether the missing data are correctly published on the web platform?

Johan.

**Comment by HristoNikodinovski** [comment]
Yes, I am sending you the exported data for the BG zone (Bulgaria) for 01.01.2021 as you can see in data i got from the API the Hour 13 is missing (picture in attach). At the same time those values are in the file i downloaded by hand from the systm

![image](https://user-images.githubusercontent.com/105789849/169033939-ff8db383-b166-47bd-80ae-56ec61b12ff2.png)


[Day-ahead Prices_202101010000-202101020000.xlsx](https://github.com/EnergieID/entsoe-py/files/8715987/Day-ahead.Prices_202101010000-202101020000.xlsx)

**Comment by fboerman** [comment]
hi @HristoNikodinovski there was a bug in an earlier release which removed entries it was not supposed to. simply update the package with pip (for example directly from terminal with ```pip install -U entsoe-py``` and everything is fixed.

Just tried it with latest version and the data is complete for your query.

if problems persist feel free to reopen this issue

**Comment by HristoNikodinovski** [comment]
I am using 0.4.3 Version of entsoe-py, which version should i be using? 
I made the instalation through Anacodna and the command above is not working.

**Comment by JrtPec** [comment]
You can check the current version number [here on line 25](https://github.com/EnergieID/entsoe-py/blob/40719dbe2bf47e285ce9a68bdd9fc2956b423c9e/entsoe/entsoe.py#L25). Currently it is 0.5.5.

**Comment by fboerman** [comment]
@HristoNikodinovski like @JrtPec  says latest version is 0.5.5 If pip is not working you are not in your conda environment. Please consult the anaconda docs on how to achieve that
