### ISSUE TITLE
quarterly data extraction

### ISSUE THREAD

**Issue by fcambrea** [EnergieID/entsoe-py#184]
Apparently a simple issue, but i can't solve it.

Here that's an example of my code:

`ts = pd.Timestamp('2022-05-01T00:00:00')
start = ts.tz_localize(tz='UTC')
ts = pd.Timestamp('2022-05-01T02:45:00')
end = ts.tz_localize(tz='UTC')
country_code = 'BE'
x = client.query_load(country_code, start=start, end=end)`

The problem is about the data on Entso-E web site, that are quarterly and not hourly data for some specific time zones. In this cases i usually find this error, because apparently the parser get just one value istead of four during the last hour extraction. 
If someone be able to solve this issue please answer me.
Thank you!

**Comment by fboerman** [comment]
for me it also works so I am closing this. feel free to reopen with more info if needed
