### ISSUE TITLE
Citation of this Project.

### ISSUE THREAD

**Issue by VartanAhrensKayayan** [EnergieID/entsoe-py#185]
I am using the entsoe-py for my master thesis. I suspect the model was built for analysts and researchers so perhaps a standardized way of citing the program is justified. I know that GitHub has a built-in citation system [as seen here.](https://twitter.com/natfriedman/status/1420122675813441540) Perhaps it is a worthwhile effort to set up a citation file. I could do so, but I need to know how the project should be correctly cited. If not for this citation I would like to know for my own project.

**Comment by JrtPec** [comment]
It sure sounds like a cool idea! What information should you need from us, the maintainers, in order to set this up?

**Comment by VartanAhrensKayayan** [comment]
I would like to know how you, the maintainers, would like to be cited going forward. Is it a group of people? If so I would like to know the first and last names and additional information they wish to be shared in the citation (email, organization affiliation, and ORCID). Some repositories refer the citation to a published article or a digital book. That is to your discretion.

**Comment by fboerman** [comment]
hi @VartanAhrensKayayan yes I would like to be cited. full name is simply Frank Boermand and my email is listed on my profile. No company please since I do this in my own time. 
thanks @JrtPec

**Comment by VartanAhrensKayayan** [comment]
@fboerman is included. I can change the file again iff @jpaduart is interested in being cited. Changes are available at #196. Once it is added to the root, there will be an option to cite in the right-hand side options of the repository page.

**Comment by fgenoese** [comment]
Thanks, it is not necessary to cite me. I am simply helping out whenever I can.

**Comment by fboerman** [comment]
this is now merged
