### ISSUE TITLE
cannot import name 'XMLParsedAsHTMLWarning' from 'bs4.builder'

### ISSUE THREAD

**Issue by frapanix** [EnergieID/entsoe-py#186]
Hi All,

I am receiving the error in the object simply running the "Demo".
Any idea that could help?

Thank you
![Screenshot ](https://user-images.githubusercontent.com/69605372/172698459-d817ad7b-07b8-4673-bd99-d98ca46a884a.png)

**Comment by fboerman** [comment]
Are you running latest version of beautifulsoup pandas and entsoe-py?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by frapanix** [comment]
yes: just checked 
beautifulsoup4 (4.9.1)
and pandas

downloaded the last entsoe-py for the occasion...

**Comment by fboerman** [comment]
hi @frapanix I just tried in a clean virtualenv and I can import just fine. my pip freeze:
```
beautifulsoup4==4.11.1
certifi==2022.5.18.1
charset-normalizer==2.0.12
entsoe-py==0.5.4
idna==3.3
numpy==1.22.4
pandas==1.4.2
python-dateutil==2.8.2
pytz==2022.1
requests==2.28.0
six==1.16.0
soupsieve==2.3.2.post1
urllib3==1.26.9
```
I am running python 3.10 atm

could you check against your pip freeze and python version?

**Comment by fboerman** [comment]
great!
