### ISSUE TITLE
'EntsoePandasClient' object has no attribute 'query_net_position'

### ISSUE THREAD

**Issue by AbiAfthab** [EnergieID/entsoe-py#191]
I tried the query_net_position to fetch the import-export data for each member state. However, I get an error saying that ''EntsoePandasClient' object has no attribute 'query_net_position'. Can anyone tell me why this happens? Thanks a lot in advance

**Comment by fboerman** [comment]
hi @AbiAfthab are you running the latest version?

**Comment by AbiAfthab** [comment]
Hi @fboerman . Thanks for responding quickly. You mean the latest version of the code? Below is the code I am running in Python 3

import pandas as pd
from entsoe import EntsoePandasClient
my_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # my API Key
start = pd.Timestamp('20220101', tz ='Europe/Brussels')
end = pd.Timestamp('20220321', tz ='Europe/Brussels')
client = EntsoePandasClient(api_key=my_token)
client = EntsoePandasClient(api_key=my_token) # Create your client 
country_code_1= 'FR'


CrflowFR= client.query_net_position(country_code, start=start, end=end, dayahead=True)


df1 = pd.DataFrame(CrflowFR)


df1.to_csv('CrflowFR.csv')

**Comment by fboerman** [comment]
hi @AbiAfthab no, did you install the latest version of the library

**Comment by AbiAfthab** [comment]
I installed the package first with the command pip install entsoe-py. pip version is  pip-22.1.2.
Tried to run the code again after restarting the kernel.
However, I get the same error for query_net_position as AttributeError: 'EntsoePandasClient' object has no attribute 'query_net_position'

Is it EntsoePandasClient or entsoe-py that you mean when you say latest library? How do I ensure if I am running the latest version?

**Comment by fboerman** [comment]
hi @AbiAfthab im sorry but I cannot reproduce your error. When I use your exact code it works just fine. Please check if you installed entsoe-py correctly. what is the version in pip list output? are you in a virtualenv?

**Comment by AbiAfthab** [comment]
Ohh is it? In pip list output, the entsoe-py version is 0.4.1. Is that the latest one? I am using Jupyter notebook. The python version is 3.9.7

**Comment by fboerman** [comment]
hi @AbiAfthab please upgrade to the latest entsoe-py version which is 0.5.4 and try again your code

**Comment by AbiAfthab** [comment]
Thanks a lot. After upgrading the ENSOE-PY version, it worked. Thanks again.

**Comment by fboerman** [comment]
youre welcome!
