### ISSUE TITLE
method to download cross-border physical flow data for an individual bidding zone containing the import/export data and the names of the neigbouring bidding zones

### ISSUE THREAD

**Issue by AbiAfthab** [EnergieID/entsoe-py#192]
I was looking for a method that would give me a dataset for an individual bidding zone with it's import-export data (not net position) including from/to which neighbouring bidding zones electricity was imported/exported. To be clear, when I am manually downloading cross-border physical flow dataset for Belgium from the ENTSO-E transparency platform, the dataset will contain the import & export data with the neighbouring bidding zones involved (eg: Germany, Netherlands, France etc.). However, I didn't see an exact method to get this same dataset. query_net_position gives only the net import-export value for each bidding zone. Similarly, with query_crossborderflow, we have to specify the from and to countries. So,  I was wondering whether we have a method to get such a dataset. Thanks a lot in advance

**Comment by AbiAfthab** [comment]
No. I mean I know that there is this method query_crossborder_flows. For this method, I need to specify 'to' and 'from' bidding zones. It would be nice to have a method in which I specify only one bidding zone and  gets me all the import& export data including the 'to' and 'from' bidding zones. Do we have such a method already? I hope I am clear.

**Comment by AbiAfthab** [comment]
Ok, fine. I will try. Thanks for your quick responses.

**Comment by JrtPec** [comment]
Hey guys, the first half of what you're looking for does exist!

See the method `query_import`.
