### ISSUE TITLE
query_generation problems

### ISSUE THREAD

**Issue by nhlong2701** [EnergieID/entsoe-py#193]
Hi all, 

I'm trying to use client.query_generation to query generation data for all European zones and i came across several issues after checking the data i pulled:

- DK and SI queries only work with start date from 2021-08-01
- GB and UK only has data until 6/14/2021  8:00:00 AM
- Kosovo only has data from 8/22/2021  10:00:00 PM
- Luxemborg only has data from 5/25/2021  10:00:00 PM
- Ireland data is a week lag
- Macedonia data is often 2 day lag

Does anyone have any suggestions for possible fix of these?

Thank you very much in advance.

**Comment by fboerman** [comment]
hi @nhlong2701  maybe stupid question but did you check that this data is available on the website to begin with? for example GB/UK has stopped many data deliveries somewhere after brexit

**Comment by nhlong2701** [comment]
hi @fboerman, good point. I definitely haven't checked them all. But i did check DK and SI and i could still query their number from 1/1/2021 onward. I just checked our countries' queries and seems like the problems were from source's missing data points

**Comment by fboerman** [comment]
hi @nhlong2701 ah that is a clear problem then. You can mail the transparancy team directly to ask them to poke TSO's to provide the missing data
