### ISSUE TITLE
ITALY CrossBorder

### ISSUE THREAD

**Issue by dilaraIsikliIntellico** [EnergieID/entsoe-py#194]
Italy Nord has four border values which are IT_NORD_CH, IT_NORD_SI, IT_NORD_FR, and IT_NORD_AT. I set the four codes as country code to and as country code from; CH, SI, FR and AT. 
For AT end SI, it doesn't work at all, for the rest it works only in 2017.
Is there anyone who knows the reason for this problem?

**Comment by fboerman** [comment]
hi @dilaraIsikliIntellico  this is probably due to some missing/incorrect eic mapping. could you perhaps check here: https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_areas if there are wrongly mapped ones in mapping.py?

**Comment by fgenoese** [comment]
What are you trying to query? The bidding zone is called “IT_NORD”.  Querying crossborde flows between IT_NORD and FR, CH, AT, SI works for me.

**Comment by fboerman** [comment]
thx for pointing that out @fgenoese then I think there is no issue here, just a bit akward way of using it.
