### ISSUE TITLE
_generate_range() got an unexpected keyword argument 'inclusive'

### ISSUE THREAD

**Issue by Aastha1996** [EnergieID/entsoe-py#195]
<img width="713" alt="Type Error" src="https://user-images.githubusercontent.com/108997675/178118992-e1ce9e60-6d0c-48c9-9916-6162156bdadf.PNG">

**Comment by fboerman** [comment]
Hi you are using an outdated version of pandas please upgrade it according to the requirements

Sent from ProtonMail mobile

-------- Original Message --------
