### ISSUE TITLE
API URL updated

### ISSUE THREAD

**Issue by waltherg** [EnergieID/entsoe-py#200]
Thank you very much for your great work on this package!

As per https://transparency.entsoe.eu/news/widget?id=62f114b5f9b76c4803137060

ENTSO-E are changing their API endpoints this year:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/3273502/183601432-3c87f986-e7ce-4c84-8778-e4e332a621fe.png">

**Comment by fboerman** [comment]
hi @waltherg  thanks for pointing this out! Completely missed this. I will switch to new endpoint for the next release
