### ISSUE TITLE
Problem with data extraction

### ISSUE THREAD

**Issue by PetricaR** [EnergieID/entsoe-py#203]
There are problems with data extraction with pandas.

**Comment by fboerman** [comment]
Please provide more details. What versions do you run of python pandas and entsoe-py. What code are you trying to execute and what is the result

-------- Original Message --------

**Comment by PetricaR** [comment]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/35411971/185571071-f301efed-b1d4-4699-ad59-4b9736c443e9.png">


this is the error

**Comment by PetricaR** [comment]
I encounter an issue with the library. I am runing just the sample code from git (see below)

![image]([https://user-images.githubusercontent.com/107117051/185562518-ed4b0d96-b442-4e4f-9c7b-1b17495433b5.png](https://user-images.githubusercontent.com/107117051/185562518-ed4b0d96-b442-4e4f-9c7b-1b17495433b5.png?fbclid=IwAR3Z4Yvx9rS17ytFFDNQ1-VVX7TnCR8BZjrRN8LzXvATdvo7rufKxGUaxLU))

The code I am trying to run is:
![image]([https://user-images.githubusercontent.com/107117051/185562789-51e00bf0-c634-4b15-a2e9-e8982adaaa02.png](https://user-images.githubusercontent.com/107117051/185562789-51e00bf0-c634-4b15-a2e9-e8982adaaa02.png?fbclid=IwAR0UbmAfDvqOhuAT8is4Lyic55vNKPoQ50mRU-8PgkNdya489ofmK4iij8c))

Do you have any idea how can I fix this issue?

Thank you.

**Comment by fboerman** [comment]
Met vriendelijke groeten Ir. Frank Boerman https://boerman.dev/

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by fboerman** [comment]
yes update your pandas, this is an error with old versions of pandas. it is possible you need to upgrade your python version then was well. 3.7 is quite old

**Comment by fboerman** [comment]
please also note that our setup.py specifically states we only support python 3.9 and python 3.10. Although I know it also works on 3.8 if you have too. pandas also only supports python >= 3.8

**Comment by PetricaR** [comment]
Thank you very much!

**Comment by fboerman** [comment]
youre welcome!

**Comment by fboerman** [comment]
Yes update your pandas. This is an error with old versions of pandas

-------- Original Message --------
