### ISSUE TITLE
New API endpoint

### ISSUE THREAD

**Issue by carl-lange2** [EnergieID/entsoe-py#205]
Hi! The ENTSO-E platform announced that they migrated to a new REST API endpoint end of August. The current endpoint will no longer be supported from 15.11.2022. Will you support the new endpoint? For reference, this was announced on 03.08.2022 here https://transparency.entsoe.eu/news/widget.

**Comment by fboerman** [comment]
yes this was addressed in #200 please update the package and you are ready for the future (along with other fixes)! the new one is already operational so better to switch already.
