### ISSUE TITLE
Retrieve static data

### ISSUE THREAD

**Issue by FabianHofmann** [EnergieID/entsoe-py#21]
Dear EnergieID team, 

thanks for your work! Is there any possibility to query static data such as installed capacity per generation unit? If I see correctly only dynamic data is available so far

Thank you

**Comment by JrtPec** [comment]
Hi Fabian,

Only the installed capacity per type has currently been implemented as `query_installed_generation_capacity`.

Shouldn't be too hard to add installed capacity per unit, based on that call. `processType` is A33, `documentType` is A71, so a simple copy should work, like this:

```python
    def query_installed_generation_capacity_per_unit(self, country_code, start, end, psr_type=None):
        """
        Parameters
        ----------
        country_code : str
        start : pd.Timestamp
        end : pd.Timestamp
        psr_type : str
            filter query for a specific psr type

        Returns
        -------
        str
        """
        domain = DOMAIN_MAPPINGS[country_code]
        params = {
            'documentType': 'A71',
            'processType': 'A33',
            'in_Domain': domain,
        }
        if psr_type:
            params.update({'psrType': psr_type})

        response = self.base_request(params=params, start=start, end=end)
        return response.text
```

**Comment by FabianHofmann** [comment]
Great! Thanks for the support. I managed to incorporate the query for the Pandas client and setup a [PR]( https://github.com/EnergieID/entsoe-py/pull/22)
