### ISSUE TITLE
Query to get cross border flows between Germany and its import/export countries returns erroneous data

### ISSUE THREAD

**Issue by AIKalpithaNidigal** [EnergieID/entsoe-py#214]
I tried querying data from 2022-10-01 to 2022-10-02 for Germany and the countries it imports/exports from. 
To point at a specific few, 

**AT > DE** 
**Using entsoe-py**
<img width="961" alt="Screenshot 2022-10-10 at 10 08 30" src="https://user-images.githubusercontent.com/103555596/194833087-686e23d5-950d-44fa-a41a-28084dd86b87.png">
**On ENTSOE**
<img width="807" alt="Screenshot 2022-10-10 at 10 09 17" src="https://user-images.githubusercontent.com/103555596/194833177-eee86c57-785c-48bc-a143-da3027f1d400.png">

**CZ > DE**
**Using entsoe-py**
<img width="1012" alt="Screenshot 2022-10-10 at 10 10 00" src="https://user-images.githubusercontent.com/103555596/194833231-bbd24894-9ac1-4835-8817-45ccbc9872c0.png">
**On ENTSOE**
<img width="803" alt="Screenshot 2022-10-10 at 10 09 34" src="https://user-images.githubusercontent.com/103555596/194833297-44169f1b-320d-434b-9326-41c0285770e9.png">

As you can see, where there should be 0's, there are some values. Unfortunately, I haven't identified where these values are coming from. 
I haven't yet tested to see if this problem persists for imports and exports between other countries. However, I'll update the issue when I find out more.

**Comment by fboerman** [comment]
The package goes for bidding zones by default and perhaps also day ahead I'm not sure. Could you check at the site at bidding zone?

Met vriendelijke groeten
Ir. Frank Boerman https://boerman.dev/

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by AIKalpithaNidigal** [comment]
I just checked the values at the bidding zone. It still says 0 for those regions.

**Comment by andresdennehy** [comment]
Having the same problem. `DE_LU` and `AT` map to the correct bidding zones, but it return the wrong data. Even if one queries DE_LU->AT and AT->DE_LU, different numbers are returned, which is impossible in cross-border flows.

I am checking whether this is due to an incorrect docType parameter...

**Comment by jvanelteren** [comment]
I just checked, it's the API not the package. Below the output of the raw client for both queries
```
'<?xml version="1.0" encoding="UTF-8"?>\n<Publication_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0">\n\t<mRID>b666c11b79724c979de4c0d190c65545</mRID>\n\t<revisionNumber>1</revisionNumber>\n\t<type>A11</type>\n\t<sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>\n\t<sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>\n\t<receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>\n\t<receiver_MarketParticipant.marketRole.type>A33</receiver_MarketParticipant.marketRole.type>\n\t<createdDateTime>2023-01-21T19:00:23Z</createdDateTime>\n\t<period.timeInterval>\n\t\t<start>2022-01-31T23:00Z</start>\n\t\t<end>2022-02-01T23:00Z</end>\n\t</period.timeInterval>\n\t<TimeSeries>\n\t\t<mRID>1</mRID>\n\t\t<businessType>A66</businessType>\n\t\t<in_Domain.mRID codingScheme="A01">10YAT-APG------L</in_Domain.mRID>\n\t\t<out_Domain.mRID codingScheme="A01">10Y1001A1001A82H</out_Domain.mRID>\n\t\t<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>\n\t\t<curveType>A01</curveType>\n\t\t\t<Period>\n\t\t\t\t<timeInterval>\n\t\t\t\t\t<start>2022-01-31T23:00Z</start>\n\t\t\t\t\t<end>2022-02-01T23:00Z</end>\n\t\t\t\t</timeInterval>\n\t\t\t\t<resolution>PT15M</resolution>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>1</position>\n\t\t\t\t\t\t<quantity>2590</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>2</position>\n\t\t\t\t\t\t<quantity>2486</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>3</position>\n\t\t\t\t\t\t<quantity>2306</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>4</position>\n\t\t\t\t\t\t<quantity>2199</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>5</position>\n\t\t\t\t\t\t<quantity>2470</quantity>\n\t\t\t\t\t</
```
And the reverse:
```
'<?xml version="1.0" encoding="UTF-8"?>\n<Publication_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0">\n\t<mRID>548497a7e85845298b2f1eeabf272426</mRID>\n\t<revisionNumber>1</revisionNumber>\n\t<type>A11</type>\n\t<sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>\n\t<sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>\n\t<receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>\n\t<receiver_MarketParticipant.marketRole.type>A33</receiver_MarketParticipant.marketRole.type>\n\t<createdDateTime>2023-01-21T19:01:49Z</createdDateTime>\n\t<period.timeInterval>\n\t\t<start>2022-01-31T23:00Z</start>\n\t\t<end>2022-02-01T23:00Z</end>\n\t</period.timeInterval>\n\t<TimeSeries>\n\t\t<mRID>1</mRID>\n\t\t<businessType>A66</businessType>\n\t\t<in_Domain.mRID codingScheme="A01">10Y1001A1001A82H</in_Domain.mRID>\n\t\t<out_Domain.mRID codingScheme="A01">10YAT-APG------L</out_Domain.mRID>\n\t\t<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>\n\t\t<curveType>A01</curveType>\n\t\t\t<Period>\n\t\t\t\t<timeInterval>\n\t\t\t\t\t<start>2022-01-31T23:00Z</start>\n\t\t\t\t\t<end>2022-02-01T23:00Z</end>\n\t\t\t\t</timeInterval>\n\t\t\t\t<resolution>PT15M</resolution>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>1</position>\n\t\t\t\t\t\t<quantity>81</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>2</position>\n\t\t\t\t\t\t<quantity>71</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>3</position>\n\t\t\t\t\t\t<quantity>66</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>4</position>\n\t\t\t\t\t\t<quantity>73</quantity>\n\t\t\t\t\t</Point>\n\t\t\t\t\t<Point>\n\t\t\t\t\t\t<position>5</
```
```

**Comment by jvanelteren** [comment]
So far the Transparency Team has been fast and on point with answers to questions:
-----------
As mentioned in the [REST API Guide](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html) "unlike [the Transparency Platform webpage](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show), REST API responds not netted values as data is requested per direction."

In order that you the same values as in the Transparency Platform webpage, you need to net the cross-border physical flow data in both directions.
-----------
In the DE-LU / AT example above this works out for 1 feb 2022: DE-LU --> AT = 2509MW. Using the api yielded 2590 and 81 the other way. Subtracting them leads to 2509

**Comment by fboerman** [comment]
thx @jvanelteren ! this indeed seems to be the issue.
