### ISSUE TITLE
HTTPError when using query_unavailability_of_generation_units

### ISSUE THREAD

**Issue by andreadib** [EnergieID/entsoe-py#215]
Seems that query_unavailability_of_generation_units works fine only with country_code='FR'
Tried with few other countries, i.e. 'DE', and always  got HTTPError: 400 Client Error: Bad Request for url:

**Comment by fboerman** [comment]
Please try the bidding zone DE_LU which is probably what you want.

Send from ProtonMail
-------- Original Message --------
