### ISSUE TITLE
Timestamp truncation causes empty responses for otherwise valid timestamps

### ISSUE THREAD

**Issue by xginn8** [EnergieID/entsoe-py#217]
In [_datetime_to_str](https://github.com/EnergieID/entsoe-py/blob/master/entsoe/entsoe.py#L136-L155), all timestamps are truncated at the hour level. Two timestamps like `00:00` and `00:59` are therefore both treated as `00:00`, which when sent upstream results in an empty response as no datapoints exist between those two (identical) timestamps.

I think it'd be slightly more correct to first round the timestamps to the nearest hour, _then_ truncate the timestamp at the hour mark. I plan to open a PR demonstrating that approach that I will link to this issue.

**Comment by fboerman** [comment]
hi @xginn8 ah that indeed sounds like a good issue, thanks for the fix
