### ISSUE TITLE
Error in unavailability_transmission query

### ISSUE THREAD

**Issue by risosoky** [EnergieID/entsoe-py#219]
Hello, I have an issue when querying the following data for any pair of countries to get unavailibility of transmission :

_today = pd.to_datetime("today") + pd.Timedelta(days =1)
start = pd.Timestamp('20221001', tz='Europe/Brussels')
end = pd.Timestamp('20221031', tz='Europe/Brussels')
df = client.query_unavailability_transmission('SK', 'CZ', start = start, end= end)_

Then I get this error: **ValueError: 12 columns passed, passed data had 14 columns**

Thanks for help

**Comment by Zaher1975** [comment]
Hi, I noticed that issue as well. This can be solved as such:
Just replace part of the function parser (line 885:897) by (I added bla1 and bla2 columns)

HEADERS_UNAVAIL_TRANSM = ['created_doc_time',
                          'docstatus',
                          'businesstype',
                          'bla1',
                          'bla2',
                          'in_domain',
                          'out_domain',
                          'qty_uom',
                          'curvetype',                      
                          'start',
                          'end',
                          'resolution',
                          'pstn',
                          'avail_qty',
                       ]
