### ISSUE TITLE
client.query_procured_balancing_capacity() returning empty df

### ISSUE THREAD

**Issue by srsps** [EnergieID/entsoe-py#224]
The problem with **parser** >> parse_procured_balancing_capacity  Causing to return empty DF

test case:
start = pd.Timestamp('20221207', tz='Europe/Brussels')
end = pd.Timestamp('20221208', tz='Europe/Brussels')
df=client.query_procured_balancing_capacity('10YDE-VE-------2',start=start,end=end,process_type='A51',offset=0)

Returns
empty df

Columns: [(Down, 1, Price), (Down, 1, Volume), (Down, 2, Price), (Down, 2, Volume), (Down, 3, Price), (Down, 3, Volume), (Down, 4, Price), (Down, 4, Volume), (Down, 5, Price), (Down, 5, Volume), (Down, 6, Price), (Down, 6, Volume), (Down, 7, Price), (Down, 7, Volume), (Down, 8, Price), (Down, 8, Volume), (Down, 9, Price), (Down, 9, Volume), (Down, 10, Price), (Down, 10, Volume), (Down, 11, Price), (Down, 11, Volume), (Down, 12, Price), (Down, 12, Volume), (Down, 13, Price), (Down, 13, Volume), (Down, 14, Price), (Down, 14, Volume), (Down, 15, Price), (Down, 15, Volume), (Down, 16, Price), (Down, 16, Volume), (Down, 17, Price), (Down, 17, Volume), (Down, 18, Price), (Down, 18, Volume), (Down, 19, Price), (Down, 19, Volume), (Down, 20, Price), (Down, 20, Volume), (Down, 21, Price), (Down, 21, Volume), (Down, 22, Price), (Down, 22, Volume), (Down, 23, Price), (Down, 23, Volume), (Down, 24, Price), (Down, 24, Volume), (Down, 25, Price), (Down, 25, Volume), (Down, 27, Price), (Down, 27, Volume), (Down, 28, Price), (Down, 28, Volume), (Down, 30, Price), (Down, 30, Volume), (Down, 31, Price), (Down, 31, Volume), (Down, 32, Price), (Down, 32, Volume), (Down, 33, Price), (Down, 33, Volume), (Down, 36, Price), (Down, 36, Volume), (Down, 37, Price), (Down, 37, Volume), (Down, 38, Price), (Down, 38, Volume), (Down, 39, Price), (Down, 39, Volume), (Down, 40, Price), (Down, 40, Volume), (Down, 41, Price), (Down, 41, Volume), (Down, 42, Price), (Down, 42, Volume), (Down, 43, Price), (Down, 43, Volume), (Down, 44, Price), (Down, 44, Volume), (Down, 45, Price), (Down, 45, Volume), (Down, 46, Price), (Down, 46, Volume), (Down, 47, Price), (Down, 47, Volume), (Down, 48, Price), (Down, 48, Volume), (Down, 49, Price), (Down, 49, Volume), (Down, 50, Price), (Down, 50, Volume), (Down, 51, Price), (Down, 51, Volume), (Down, 53, Price), (Down, 53, Volume), (Down, 54, Price), (Down, 54, Volume), (Down, 56, Price), (Down, 56, Volume), ...]

**Comment by fboerman** [comment]
hi @srsps maybe stupid question, but did you verify this data indeed does exist on the website as well?

**Comment by sungsy** [comment]
I have a similar issue  - but I get an error instead of an empty dataframe:
``HTTPError: 408 Client Error: Request Time-out for url: WEB-API``
If I try to open the web-api I get the following: 
````
[...]
<Reason>
<code>999</code>
<text>Request timeout after 300 seconds.</text>
</Reason>
[...]
````

**Comment by sungsy** [comment]
I have a similar issue  - but I get an error instead of an empty dataframe:
``HTTPError: 408 Client Error: Request Time-out for url: WEB-API-LINK``
If I try to open the web-api I get the following: 
````
[...]
<Reason>
<code>999</code>
<text>Request timeout after 300 seconds.</text>
</Reason>
[...]
````
I checked on the website as well, and it looks like data is there available.

**Comment by fboerman** [comment]
I suspect this is an issue of the etp platform itself. Please contact entsoe to ask them about this.
