### ISSUE TITLE
`InvalidBusinessParameterError`when trying to request generation per plant for `DE_LU`

### ISSUE THREAD

**Issue by mcw92** [EnergieID/entsoe-py#225]
Hi!
In analogy to the example provided in your README, we tried to request the actual generation per production type (actual generation per plant) for Germany. For us, your example works perfectly fine for Belgium but when we change the country code from `BE` to `DE_LU`, it throws an `InvalidBusinessParameterError`. Below, you can find a corresponding code snippet. Can you tell us what is wrong here? Any comments or help would be very much appreciated!

Thanks a lot in advance!

`from entsoe import EntsoePandasClient ` 
`import pandas as pd`  

`client = EntsoePandasClient(api_key="<YOUR_API_KEY>")`  
`start = pd.Timestamp('20220601', tz='Europe/Berlin')`  
`end = pd.Timestamp('20220701', tz='Europe/Berlin')`  
`country_code = 'DE_LU'  # Germany`

`client.query_generation_per_plant(country_code, start=start,end=end, psr_type=None)`

**Comment by fboerman** [comment]
ah this is usually due to confusion with bidding zones versus countries. Have you tried "DE" as an input?

**Comment by Ecomodern** [comment]
I am experiencing the same issue. Using "DE" does not work either.

**Comment by fboerman** [comment]
thanks @awarsewa ! then this issue is solved
