### ISSUE TITLE
query for export implementation ?

### ISSUE THREAD

**Issue by irmatgit** [EnergieID/entsoe-py#230]
Hi,

Is it possible to implement a query that output the power exported from a given country.
I am thinking something like the import query but for export instead:
df =  client.query_export(country_code, start, end)         #instead of df =  client.query_import(country_code, start, end) 

Background for this question is that I would like to reconstruct the load of all countries based on the formula:
reconstruted_load = generation + import - export

It seems this could be obtained by querying the crossborder_flows for each neighboring country but it is quite tedious.

Thanks,

Matthieu

**Comment by JamieTaylor-TUOS** [comment]
Hi Matthieu,

I also have a use case that requires this data - I'm going to submit a PR shortly that hopefully provides this functionality...

Cheers

Jamie

**Comment by fboerman** [comment]
hi! I have added query_physical_crossborder_allborders function that can do both import and export and has an added column for sum.
