### ISSUE TITLE
N/A Values not treated

### ISSUE THREAD

**Issue by EnzoMolfetta** [EnergieID/entsoe-py#236]
Hi,
Using this package I see that N/A values are not handled by the "query_load" function.
Example: I want to query data from "Total Load - Day Ahead / Actual" page of entsoe for France (10YFR-RTE------C) on 13 June 2020 which has N/A value in 7:00-8:00 interval.

![Screenshot 2023-01-20 alle 16 37 50](https://user-images.githubusercontent.com/20209002/213741596-5c8c5315-9925-4c7b-b9ba-4c92b29f06be.png)

but the dataframe has only 23 rows, instead of 24 with null value in that interval.

<img width="278" alt="Screenshot 2023-01-20 alle 16 42 49" src="https://user-images.githubusercontent.com/20209002/213742037-42562b3f-127b-4ef6-9bca-db53e73475b0.png">

Can you please check this?

Here is my full demo code:

```
import pandas as pd
from entsoe import EntsoePandasClient

client = EntsoePandasClient(api_key='mykey')

start = pd.Timestamp('20180613', tz='Europe/Rome')
end = pd.Timestamp('20180614', tz='Europe/Rome')
country_code = 'FR'

result = client.query_load('10YFR-RTE------C', start=start, end=end)
print(result)
```

**Comment by fboerman** [comment]
hi thanks for your behaviour but this is intended behaviour. values which are not there should not be in the dataframe. If you later merge it to a table that does have an entry on that hour it will automatically create a nan.
