### ISSUE TITLE
Extraction of net transfer capacity from CH to DE-LU missing data

### ISSUE THREAD

**Issue by mechen-gess** [EnergieID/entsoe-py#238]
Dear Development Team,

Thank you very much first for the provision of the package. I am now trying to extract the transmission capacity data of cross-border connections for 2018. What I tried to do is the following:

text = self.entsoeClient.query_net_transfer_capacity_yearahead(country_code_from='10YCH-SWISSGRIDZ', country_code_to='10Y1001A1001A82H', start='2018-01-01 00:00:00+01:00', end='2018-01-01 00:00:00+01:00')
(The values are just for indicating the variable value in my code; may not be in the correct format)

What I get from 'text' is however the following.

**Problem 1:
The period.timeInterval starts from 2018-09-30 rather than 2018-01-01**.
**Problem 2:
With the time resolution of 1M, there should be 4 values from 09-30 to 12-31, but in this file only 3 values are given**.

The above code works well with other country codes, it just does not work for this specific connection. Could you help me out with this problem? Thank you very much!

Regards,
mechen-gess

<?xml version="1.0" encoding="UTF-8"?>
<Publication_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0">
	<mRID>45ca16e6ea564cbeb98adc60c75461d7</mRID>
	<revisionNumber>1</revisionNumber>
	<type>A61</type>
	<sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>
	<sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>
	<receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>
	<receiver_MarketParticipant.marketRole.type>A33</receiver_MarketParticipant.marketRole.type>
	<createdDateTime>2023-02-01T10:49:08Z</createdDateTime>
	**<period.timeInterval>
		<start>2018-09-30T22:00Z</start>
		<end>2018-12-31T23:00Z</end>**
	</period.timeInterval>
	<TimeSeries>
		<mRID>1</mRID>
		<businessType>A27</businessType>
		<in_Domain.mRID codingScheme="A01">10Y1001A1001A82H</in_Domain.mRID>
		<out_Domain.mRID codingScheme="A01">10YCH-SWISSGRIDZ</out_Domain.mRID>
		<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>
		<curveType>A01</curveType>
			<Period>
				<timeInterval>
					<start>2018-09-30T22:00Z</start>
					<end>2018-12-31T23:00Z</end>
				</timeInterval>
				**<resolution>P1M</resolution>**
					<Point>
						<position>1</position>
						<quantity>1000</quantity>
					</Point>
					<Point>
						<position>2</position>
						<quantity>1000</quantity>
					</Point>
					<Point>
						<position>3</position>
						<quantity>1000</quantity>
					</Point>
			</Period>
	</TimeSeries>
</Publication_MarketDocument>

**Comment by fboerman** [comment]
hi! this seems like a problem with the xml document that is returned from the server. this package is not affiliated with entsoe, it is a community work. we do not have any influence on the server. Please file a report to transparency@entsoe.eu and they can help you further. Thanks!
