### ISSUE TITLE
Issue with Hydro Pumped Storage values

### ISSUE THREAD

**Issue by ThomasAuriel** [EnergieID/entsoe-py#24]
Hi,

The entsoe pandas client (probably also the Raw client but I didn't tested it), does not take into consideration the "negative values" of the Hydro Pumped Storage. This production is able to pump water and so have a negative production (it's a charge not a generator).

The ENTSOE API website does the difference
![image](https://user-images.githubusercontent.com/4946109/58790314-726e7e80-85f0-11e9-987e-4ab6cd6b66a2.png)

But the Python client does not :
![image](https://user-images.githubusercontent.com/4946109/58790637-0fc9b280-85f1-11e9-91fa-a5862f72b214.png)

I don't know how to do the difference too in the raw XML
```xml
	<TimeSeries>
		<mRID>5</mRID>
		<businessType>A01</businessType>
		<objectAggregation>A08</objectAggregation>
		<inBiddingZone_Domain.mRID codingScheme="A01">10YFR-RTE------C</inBiddingZone_Domain.mRID>
		<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>
		<curveType>A01</curveType>
		<MktPSRType>
			<psrType>B10</psrType>
		</MktPSRType>
		<Period>
			<timeInterval>
				<start>2019-05-20T05:00Z</start>
				<end>2019-05-20T06:00Z</end>
			</timeInterval>
			<resolution>PT60M</resolution>
				<Point>
					<position>1</position>
                        <quantity>1902</quantity>
				</Point>
		</Period>
	</TimeSeries>
	<TimeSeries>
		<mRID>6</mRID>
		<businessType>A01</businessType>
		<objectAggregation>A08</objectAggregation>
		<outBiddingZone_Domain.mRID codingScheme="A01">10YFR-RTE------C</outBiddingZone_Domain.mRID>
		<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>
		<curveType>A01</curveType>
		<MktPSRType>
			<psrType>B10</psrType>
		</MktPSRType>
		<Period>
			<timeInterval>
				<start>2019-05-20T03:00Z</start>
				<end>2019-05-20T05:00Z</end>
			</timeInterval>
			<resolution>PT60M</resolution>
				<Point>
					<position>1</position>
                        <quantity>1236</quantity>
				</Point>
				<Point>
					<position>2</position>
                        <quantity>308</quantity>
				</Point>
		</Period>
	</TimeSeries>
```

The first TimeSeries should be considerated as positive and the second as negative.

I have send an email to ENTSO-E platform for more information.

**Comment by jpaduart** [comment]
Hello,

I stumbled on this problem as well last year, but never had the time to fix
it. Differentiating between Pump Load and Generation is quite easy from the
following identifiers:
"inBiddingZone_Domain.mRID" => pump generation
"outBiddingZone_Domain.mRID" => pump load
To be backwards compatible one could simply adapt the sign of the quantity
(negative generation in case of pump load)
Theoretically speaking there could be hours with both consumption and
generation. To cope with that, one could return the values in different
columns (Hydro Pumped Storage Generation and Hydro Pumped Storage
Consumption), but this could break existing code.

Johan.



Op ma 3 jun. 2019 om 11:28 schreef Thomas <notifications@github.com>:

**Comment by ThomasAuriel** [comment]
Yes ENTSO-E did answer the same.

For the use I have from this client, the positive and negative sign is the best. I will try to correct it on my side and share it if i get solid results.
I'm not sure that the generation and the consumption can occur in the same time, but if it does i will sum both.

**Comment by JrtPec** [comment]
Hi @ThomasAuriel and @jpaduart, I'm reopening this because the same issue has popped up with the `generation_forecast` query, see #74. 

Revisiting this, I saw that we chose to implement this as the _nett sum_ for generation, i.e. we subtract the consumption of pumped hydro from the production.
Looking at that code, I'm not happy with how that code is written, definitely not because it took me a while to remember how it works, what the reasoning is, etc... never a good sign of code if you cannot remember what it does or why it is there.

Thats why I'm thinking of redoing it, and returning the explicit result in the same way as they show it on the transparency platform.
Sure it may break some existing code, so I'll add a flag somewhere so the old behaviour can be reproduced.

What do you guys think?

**Comment by tranberg** [comment]
I support the possibility of returning both values for consumption and production of hydro power. I've actually made a small hack for this on a branch somewhere, but never turned it into a proper PR.

**Comment by JrtPec** [comment]
Ok, #75 should solve our issue definitely. (I hope)

There is a curious result though:
The generation request for the Netherlands includes a lot of consumption of generation equipment, something other countries (of the one's I've tested) don't seem to have:

<img width="727" alt="Screenshot 2020-10-21 at 18 27 48" src="https://user-images.githubusercontent.com/4570408/96749464-27166500-13cb-11eb-80d3-bc651772f1c9.png">

Weird is that this information isn't shown on the transparency platform:
<img width="642" alt="Screenshot 2020-10-21 at 18 28 40" src="https://user-images.githubusercontent.com/4570408/96749612-5331e600-13cb-11eb-8fcc-3493a10a8524.png">

Anybody has any idea on how to approach this?

**Comment by jpaduart** [comment]
Hi!

I remember that this was done to keep backwards compatibility (returning a single column of data). True that this may hide information (autoconsumption of power plants). 
No worries if it breaks existing code... sometimes it’s better to go forward, fans have a cleaner solution. (There is versioning of the package anyway?)
Johan

**Comment by JrtPec** [comment]
Sure, you can always install an older version, or you can branch off at any point in history and go you own way. Nobody's code is suddenly going to break

**Comment by fgenoese** [comment]
1st column should be gross generation ("Actual Aggregated"), 2nd column should be the electricity used to operate the power plants ("Actual Consumption"). Not every country has live gross generation, and therefore directly publishes net generation (1st minus 2nd column).

According to ENTSO-E documentation, "Net Generation is preferred however gross generation could be used where it is available with the better precision. TSOs should decide gross or net generation will be used but the net/gross characteristic should be consistent per Bidding zone. "

Your solution leaves it to the user whether gross or net generation should be retrieved (when available). Vote to merge this pull request.

**Comment by JrtPec** [comment]
I've had some exchanges with Entso-e support.

Conclusion is this (indeed the way @fgenoese described):
Some data providers only provide net generation, others provide gross generation and consumption. Hence, the "Actual Aggregated" column can contain either gross or net.
However if you use the `net` parameter in entsoe-py, it will try to sum gross and consumption, so the result is always net.

**Comment by JrtPec** [comment]
Solution deployed in 0.3.2
