### ISSUE TITLE
entsoe changed their API endpoint - 404 HTTP error

### ISSUE THREAD

**Issue by jens-entras** [EnergieID/entsoe-py#240]
Starting from 14/02/2023 entso-e changed their API endpoint. 
The legacy REST API endpoint is no longer supported, instead a new REST API endpoint should be used.
This breaks the entsoe-py package as it results in 404 Client Errors.

See here for more info: https://transparency.entsoe.eu/news/widget?id=63eb9d10f9b76c35f7d06f2e

**Comment by fboerman** [comment]
this has been fixed since V0.5.5 back in august. I would like to kindly request you to test with latest version of the package before opening an issue on things ;) My server with the latest version running is querying fine.

**Comment by jens-entras** [comment]
I did test with the latest version (V0.5.9), and stil got the 404 error, that's why I opened an issue :)
In the error I get it mentiones the old REST API endpoint:

HTTPError: 404 Client Error: 404 for url: https://transparency.entsoe.eu/api?documentType=A44&in_Domain=10YBE----------2&out_Domain=10YBE----------2&securityToken=5ad799dc-e496-4ef6-abd8-f59f1b34e331&periodStart=202207312200&periodEnd=202302282300

Any idea then on what I must be doing wrong? :)

**Comment by fboerman** [comment]
hi @jens-entras  then you are apparently not running the latest version (or I left a hardcoded reference haha but dont think so) could you do

from entsoe import __version___
print(__version__)

**Comment by jens-entras** [comment]
Restarting my Python IDE solved the issue... - strange
Sorry for bothering :s

PS. I was in fact already on version 0.5.9

**Comment by fboerman** [comment]
@jens-entras  did you upgrade while having the IDE open? file changes on disk for already loaded imports has no effect in your current python session.

anyway good that it is fixed now!

**Comment by jens-entras** [comment]
Yeah probably that was the issue. 
I do have the tendency to leave the IDE open for long periods of time. ;s
