### ISSUE TITLE
Entsoe 404

### ISSUE THREAD

**Issue by kjeir** [EnergieID/entsoe-py#242]
The URL of the API has changed from:
https://transparency.entsoe.eu/
to:
https://web-api.tp.entsoe.eu/

**Comment by jdtrebbien** [comment]
Try updating to the current version of entsoe-py. The current version uses the new API. (see entsoe.py: `URL = 'https://web-api.tp.entsoe.eu/api'`)

**Comment by kjeir** [comment]
Thanks !
