### ISSUE TITLE
404 client error

### ISSUE THREAD

**Issue by rablancomo** [EnergieID/entsoe-py#243]
Hi
I am using the library and I am getting this error since last week:
HTTPError: 404 Client Error: 404 for url: https://transparency.entsoe.eu/api?documentType=A44&in_Domain=10YES-REE------0&out_Domain=10YES-REE------0&securityToken=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx&periodStart=202212312300&periodEnd=202312312300

I wonder if it is related whith this new regarding to the end of de support to https://transparency.entsoe.eu/api:
![image](https://user-images.githubusercontent.com/68293684/219972451-be30cd65-44d6-4a88-a706-70462b710681.png)

It seems that the new API is https://web-api.tp.entsoe.eu/api

Thanks for your help

**Comment by fboerman** [comment]
Hi you are kindly requested to always test with the newest version of the package before opening an issue. The package has been using the new url for some versions now. Please update your installation.

-------- Original Message --------

**Comment by rablancomo** [comment]
Thank you!
