### ISSUE TITLE
Georgia is missing when use query_load

### ISSUE THREAD

**Issue by Einwunder** [EnergieID/entsoe-py#245]
Dear Developers,

I am using client.query_load method to extract the actual load data for Georgia (GE) using your API, but it returns errors. The problem seems to be in the lookup table of area, to be precise, here is the error message:  

> area = [area for area in Area if area.value == s][0]
> IndexError: list index out of range

can you please check? Thanks in advance

**Comment by fboerman** [comment]
ah yes that is indeed missing. will try to add with next release!

**Comment by Einwunder** [comment]
Thank you for checking it out!
