### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))

### ISSUE THREAD

**Issue by 399645** [EnergieID/entsoe-py#247]
Hello,

The code works perfectly in my mac computer but when I used the exact same code in a windows computer I get a local issuer certificate error. Any idea on how I can fix this?

![Capture](https://user-images.githubusercontent.com/53593631/221413565-f7d20c49-120a-40c9-b0d7-308a3bddbdf9.JPG)

Thank you!

**Comment by fboerman** [comment]
hi this is indeed a common issue with corporate networks. Please contact your IT department. I rather not encourage unsafe behaviour by allowing a toggle. This unofficial workaround should be enough
