### ISSUE TITLE
Issue with EntsoePandasClient --> query_day_ahead_prices

### ISSUE THREAD

**Issue by Rakkiee** [EnergieID/entsoe-py#248]
![image](https://user-images.githubusercontent.com/126492484/221612873-4f771cc9-8cc2-48a2-b4af-95f9b9e66db7.png)

Returns HTTPError: 403 when executing the following code:

client = EntsoePandasClient(api_key=self.api_key)
da_prices = client.query_day_ahead_prices(self.country_code, start=start_ts, end=end_ts)

**Comment by fboerman** [comment]
Hi you are kindly requested to always test with the latest version of the package before opening an issue. I can see from you screenshot that you are not on it. Please update.

-------- Original Message --------

**Comment by Rakkiee** [comment]
@fboerman this was indeed the issue, thanks for the help

**Comment by 399645** [comment]
Not sure if this is same error but I also can't get anything reported today for any day. Am I doing something wrong? Code was working fine yesterday
<img width="844" alt="Screenshot at Feb 28 11-50-34" src="https://user-images.githubusercontent.com/53593631/221847389-9ebec93a-1ee8-4333-aba2-8fc2254485ab.png">
<img width="846" alt="Screenshot at Feb 28 11-54-10" src="https://user-images.githubusercontent.com/53593631/221847664-e807b40d-77b5-4c89-9f86-081a9c62f6e8.png">
