### ISSUE TITLE
query_generation & query_load resulting in NoMatchingDataError for UK

### ISSUE THREAD

**Issue by AbiAfthab** [EnergieID/entsoe-py#256]
Hi,
I have been using client.query_generation(code, start=start, end=end) and client.query_load (code, start=start, end=end) in my python script. Since today I am getting NoMatchingDataError for UK. Is this an error from ENTSO-E side? 
![image](https://user-images.githubusercontent.com/108003947/232455586-8db87597-276b-4ffe-9783-b23e2e992066.png)

**Comment by fboerman** [comment]
hi since brexit virtually all data about UK/GB has stopped being updated. This is because entsoe is a simple passthrough and does not do generate or fill in any data themselves. In this case the UK TSO has stopped sending in data.
