### ISSUE TITLE
`NoMatchingDataError` for imbalance price query for Germany depending on query start

### ISSUE THREAD

**Issue by clj-enspired** [EnergieID/entsoe-py#260]
Hi all,

I have some weird behaviour when querying the imbalance prices for Germany using 
```
entsoe_client.query_imbalance_prices(area_code, start=dt_start, end=dt_end)
```

I want to query the most recent published data (April 2023) and I am using `area_code=10Y1001A1001A82H` which AFAIK is the correct EIC for recent data. However, if I use any value after `2022-06-21` for `dt_start` I get `NoMatchingDataError`. If I use a value for `dt_start` before `2022-06-22` then the query is successful.

Was there maybe some change in EIC for Germany? On the ENTSOE transparency platform the imbalance prices for all of Germany are provided for IPA (Imbalance Price Area). And I can't find a source for the EIC for the IPA of Germany. According to ENTSOE:

> Imbalance prices shall be reported by default per imbalance price area, which in the majority of cases coincide with the scheduling area. The imbalance price area may differ from the scheduling area when the bidding zone covers several control areas as foreseen by GL SO article 110.2, when required by EB GL article 2(13) or when balancing markets are based on an integrated scheduling process, where local congestion within the scheduling area may influence the imbalance price.

I'm thankful for any help! :)

Best,
Clemens

**Comment by tvwerkhoven** [comment]
I have the same error querying data for area_code NL from 2023-07-04 to 2023-07-07. Maybe related? I've been running the script for a while with no problem, and it suddenly popped up since yesterday.

I get the error with both python3.8 and python3.9.

```
Traceback (most recent call last):
  File "/home/tim/workers/epexspot/epexspot2influx2b.py", line 52, in <module>
    daprice = client.query_day_ahead_prices(country_code, start=_start, end=_end)
  File "/home/tim/.local/lib/python3.9/site-packages/entsoe/decorators.py", line 106, in year_wrapper
    raise NoMatchingDataError
entsoe.exceptions.NoMatchingDataError
```

**Comment by clj-enspired** [comment]
I think in your case the error is correct: day-ahead prices are only published for the next day (published after the SDAC auction at 12:00 CET/CEST). So any data after 2023-07-05 will not exist yet (today that is). 

Only querying for the next day should work in your case. But it is possible that there was some change on ENTSOE side if you always queried so far into the future and did not get the error previously.

**Comment by Retuo** [comment]
> I have the same error querying data for area_code NL from 2023-07-04 to 2023-07-07. Maybe related? I've been running the script for a while with no problem, and it suddenly popped up since yesterday.
> 
> I get the error with both python3.8 and python3.9.
> 
> ```
> Traceback (most recent call last):
>   File "/home/tim/workers/epexspot/epexspot2influx2b.py", line 52, in <module>
>     daprice = client.query_day_ahead_prices(country_code, start=_start, end=_end)
>   File "/home/tim/.local/lib/python3.9/site-packages/entsoe/decorators.py", line 106, in year_wrapper
>     raise NoMatchingDataError
> entsoe.exceptions.NoMatchingDataError
> ```

Noticed the same. Maybe the prices for 07-04 were released later than usual.

**Comment by tvwerkhoven** [comment]
My issue is resolved, @Retuo's hypothesis seems most likely, late release of today's data.

@clj-enspired: this was never an issue before, when you supply a late end date, only available data in the range is returned.

**Comment by fboerman** [comment]
hi all thanks for the report!

@tvwerkhoven the market coupling got delayed a couple of times which results in the no data error. That is a data availability issue and not something about this package

@clj-enspired I am not sure what is going wrong here. It could indeed be different eic codes. I would like to ask you to contact entsoe directly at transparency@entsoe.eu to ask them about the eic codes and report back if that solves your issue. Thanks!
