### ISSUE TITLE
issue with 403 Client Error

### ISSUE THREAD

**Issue by tiltedace** [EnergieID/entsoe-py#264]
When issuing running the follow function:  client.query_wind_and_solar_forecast('FR', start=forecast_start,end=forecast_end, psr_type=None)

Getting a 403 Client Error message when executing:  

TTPError: 403 Client Error: Forbidden for url: [https://transparency.entsoe.eu/api?documentType=A69&processType=A01&in_Domain=10YFR-RTE------C&securityToken=](https://transparency.entsoe.eu/api?documentType=A69&processType=A01&in_Domain=10YFR-RTE------C&securityToken=b1c14f6e-3403-4085-8342-b3cd6558d586&periodStart=201512312300&periodEnd=201612312300)

**Comment by fboerman** [comment]
hi this means your api key is invalid or missing. Please check your api key with the one provided to you

**Comment by tiltedace** [comment]
What I'm getting is this following message: 

The REST API endpoint https://transparency.entsoe.eu/api is not in use anymore.
To be able to use the REST API service, you need to make requests to the new endpoint https://web-api.tp.entsoe.eu/api as described in the [REST API guide](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html).
 
Do the current updates to entsoe-py account for these issues?

**Comment by fboerman** [comment]
Hi,

Yes this has been switched months ago. Please update your installation

-------- Original Message --------

**Comment by tiltedace** [comment]
What would be the correct command/ installation method to upgrade entsoe-py
here:
Tried using pip install entsoe-py --upgrade, but it seems the version
listed is still 0.4.4 and the api issues still persist [image: image.png]

**Comment by fboerman** [comment]
hi @tiltedace the text suggests an image but here on github I dont see any image. Anyway yes pip install -U should work. If it doesnt you are perhaps using an unsupported python version or your installation is borked.

**Comment by tiltedace** [comment]
Updated entsoe-py, the token is new and updated, and installation is fine: 

Still Getting a 403 Client Error message when executing:

What python versions are supported for the existing package?  Am running it on python 3.7.13
