### ISSUE TITLE
Typo in HEADERS_UNAVAIL_TRANSM

### ISSUE THREAD

**Issue by LemuelKL** [EnergieID/entsoe-py#268]
There is a missing comma in the list `HEADERS_UNAVAIL_TRANSM`:
https://github.com/EnergieID/entsoe-py/blob/4c288c518dc38eaec18793ee4ca45321650e934c/entsoe/parsers.py#L892-L906

Typo was introduced in pull request #263

**Comment by BenediktPrusas** [comment]
Thank you!
