### ISSUE TITLE
Missing Day-Ahead NTC for DE_LU-NO_2 and DE_LU-SE_4

### ISSUE THREAD

**Issue by zoobar** [EnergieID/entsoe-py#271]
start = pd.Timestamp('20230901', tz='Europe/Brussels')
end = pd.Timestamp('20230905', tz='Europe/Brussels')

client.query_net_transfer_capacity_dayahead(country_code_from='DE_LU', country_code_to='SE_4', start=start, end=end)
NoMatchingDataError: 

client.query_net_transfer_capacity_dayahead(country_code_from='DE_LU', country_code_to='NO_2', start=start, end=end)
NoMatchingDataError:

**Comment by fboerman** [comment]
hi this data is missing on the UI as well so this is not the issue of this package. please contact the transparancy platform to ask for details on this.
