### ISSUE TITLE
NoMatchinDataError

### ISSUE THREAD

**Issue by magnushaga** [EnergieID/entsoe-py#276]
query net position leads to No Matching Data error with EntsoePandasClient for all start and end dates and area codes. The same issue is prevalent whilst using the EntsoeRawClient for xml. The resful API seems to handle the GET request from entsoe's API

**Comment by fboerman** [comment]
Hi,

Whenever this happens please always check the website first.

The netposition data has been missing for couple of days now on the site so the api also can't return it. Entsoe is working on this on their site.

-------- Original Message --------

**Comment by fboerman** [comment]
this has been fixed now by entsoe
