### ISSUE TITLE
query_net_position returns always void results

### ISSUE THREAD

**Issue by jimich** [EnergieID/entsoe-py#277]
I'm trying to use the query_net_position (not used it in the past) and use the following code:
start = pd.Timestamp('20220701', tz='Europe/Brussels')
end = pd.Timestamp('20221231', tz='Europe/Brussels')
country_code = 'BE'  #
seriesDANetPosition= client.query_net_position(country_code=country_code,start=start,end=end, dayahead=True)
dfDANetPosition=seriesDANetPosition.to_frame()
print(dfDANetPosition)

Whatever the period or the country (FR, etc...), I got an exception due to the fact that no data is retrieved.
Also in case of dayahead=false

 102     frames.append(frame)
    104 if sum([f is None for f in frames]) == len(frames):
    105     # All the data returned are void
--> 106     raise NoMatchingDataError

There is however data in ETP
![image](https://github.com/EnergieID/entsoe-py/assets/24934116/e919e4db-3ff4-409a-8922-cdcf9a134a21)

I've tried to get DAprices via same parameters/code but with 
seriesDAPrices= client.query_day_ahead_prices(country_code=country_code,start=start,end=end)
dfDAPrices=seriesDAPrices.to_frame()
print(dfDAPrices)
and that works (so error is not in my key/access to entsoe-py)

**Comment by fboerman** [comment]
Hi Jean-Michel,

There was an outage in this data both on the site and the api. It now seems they have only fixed the first.... I have already send in a ticket. We just have to wait for entsoe sadly. This is not a package issue.

-------- Original Message --------

**Comment by jimich** [comment]
Thanks a lot!
I confirm

![image](https://github.com/EnergieID/entsoe-py/assets/24934116/a533f5fa-1f10-4248-9c7d-d203396595f5)
