### ISSUE TITLE
Querying transfer capacities across October daylight savings end crashes code

### ISSUE THREAD

**Issue by ploplen** [EnergieID/entsoe-py#279]
start = pd.Timestamp('20230101', tz='Europe/Stockholm')
end = pd.Timestamp('20231024', tz='Europe/Stockholm')
capacity_from = client.query_net_transfer_capacity_weekahead('SE_1', 'FI', start=start, end=end)
Will crash because when _parse_datetimeindex in parsers.py parses the last week it returns 8 indexes instead of 7. The problem is that the week is one extra hour long.
Note that end date (20231024) is still with daylight saving so there is no easy check on the input data to do.
Daylight savings occur at 20231029, the Sunday in the week of 20231024. The response from entso-e will only contain UTC timestamps, 
start = Timestamp('2023-10-22 22:00:00+0000', tz='UTC')
end = Timestamp('2023-10-29 23:00:00+0000', tz='UTC')
so start.dst() can't be checked.

Adding 
    elif pd.Timedelta(delta) >= pd.Timedelta('1D') and end.hour == start.hour + 1:
        # For a daily or larger granularity, if we jump over the DST date in October,
        # date_range erronously returns an additional index element
        # because the period contains one extra hour.
        index = index[:-1]
to _parse_datetimeindex will fix the issue. But I can't really overview if it breaks something in the bigger picture.

**Comment by fboerman** [comment]
hi! thanks for spotting this! lets merge the discussion into #280
