### ISSUE TITLE
fail to query data via query_net_transfer_capacity_monthahead()

### ISSUE THREAD

**Issue by echoqsun** [EnergieID/entsoe-py#280]
Hello all,

I had an issue when query data during these timestamp, it raised the value error.
![image](https://github.com/EnergieID/entsoe-py/assets/92441765/5a2436ad-cb5c-4d8d-9bd2-faf3a15714db)
![image](https://github.com/EnergieID/entsoe-py/assets/92441765/e2e74553-d202-450b-8215-77cc40d21fe4)

But if I query same data article at another time stamps, it works. 
![image](https://github.com/EnergieID/entsoe-py/assets/92441765/e67be80c-d9d4-47cd-b6f4-b315d4d82088)

Could someone figure out this kind of issues？

**Comment by fboerman** [comment]
hi! thanks for spotting this! @ploplen how exactly do you see the fix with to _parse_datetimeindex? Can you ellaborate or make a PR available?

**Comment by ploplen** [comment]
Hi @fboerman ,
Tried making a PR, but ran into some kinda permissions issue (haven't pushed to github before). The complete function inside parsers.py should look like below when updated. As I said in #279, I am not sure if breaks anything in the bigger picture, but it worked for me.

`def _parse_datetimeindex(soup, tz=None):
    """
    Create a datetimeindex from a parsed beautifulsoup,
    given that it contains the elements 'start', 'end'
    and 'resolution'

    Parameters
    ----------
    soup : bs4.element.tag
    tz: str

    Returns
    -------
    pd.DatetimeIndex
    """
    start = pd.Timestamp(soup.find('start').text)
    end = pd.Timestamp(soup.find_all('end')[-1].text)
    if tz is not None:
        start = start.tz_convert(tz)
        end = end.tz_convert(tz)

    delta = _resolution_to_timedelta(res_text=soup.find('resolution').text)
    index = pd.date_range(start=start, end=end, freq=delta, inclusive='left')
    if tz is not None:
        dst_jump = len(set(index.map(lambda d: d.dst()))) > 1
        if dst_jump and delta == "7D":
            # For a weekly granularity, if we jump over the DST date in October,
            # date_range erronously returns an additional index element
            # because that week contains 169 hours instead of 168.
            index = index[:-1]
        index = index.tz_convert("UTC")
    elif pd.Timedelta(delta) >= pd.Timedelta('1D') and end.hour == start.hour + 1:
        # For a daily or larger granularity, if we jump over the DST date in October,
        # date_range erronously returns an additional index element
        # because the period contains one extra hour.
        index = index[:-1]

    return index
`

**Comment by fboerman** [comment]
very nice thanks @ploplen ! I think its a good fix and have pushed it!

**Comment by ploplen** [comment]
Great! Thank you.
