### ISSUE TITLE
Add activated balancing prices (A84) 

### ISSUE THREAD

**Issue by CoenvdPol** [EnergieID/entsoe-py#283]
Hi, is it possible to add the 

"Activated balancing prices"

Documenttype A84, to the query?

Best,
Coen

**Comment by fboerman** [comment]
hi! if you want you can easily add this yourself when looking at an example query. Do you have an example of the GUI of a country which publishes data for this? Then I can take a look as well. For NL it seems there is no data in the GUI for this

**Comment by TwanKrmr** [comment]
Hello, we are specifically seeking FCR prices, which Entsoe publishes on their platform under "Price of Reserved Balancing Reserves" with the following [link](https://transparency.entsoe.eu/balancing/r2/balancingVolumesReservationPrice/show?name=&defaultValue=false&viewType=GRAPH&areaType=SCA&atch=false&dateTime.dateTime=14.11.2023+00:00|UTC|DAY&dateTime.endDateTime=19.11.2023+00:00|UTC|DAY&contractTypes.values=A13&contractTypes.values=A01&contractTypes.values=A02&contractTypes.values=A03&contractTypes.values=A04&contractTypes.values=A06&reserveType.values=A95&marketArea.values=CTY|10YNL----------L!SCA|10YNL----------L&reserveSource.values=A04&reserveSource.values=A05&reserveSource.values=NOT+SPECIFIED&dv-datatable-detail_6551cce483963b1d777a7a36_length=10&dv-datatable_length=10).

In the API user guide provided by Entsoe, we are referring to section 4.6.9, titled "Prices of Procured Balancing Reserves [17.1.C]."

I plan to attempt making the query on my own. Unfortunately, I lack the experience to do this easily.

**Comment by jpaduart** [comment]
Hi,I implemented this feature a few years ago, not sure if I did a PR. Have a look at my “reserves” fork.Comparing EnergieID:master...jpaduart:reserves · EnergieID/entsoe-pygithub.comJohan.Op 20 nov 2023 om 14:11 heeft TwanKrmr ***@***.***> het volgende geschreven:﻿
Hello, we are specifically seeking FCR prices, which Entsoe publishes on their platform under "Price of Reserved Balancing Reserves" with the following link.
In the API user guide provided by Entsoe, we are referring to section 4.6.9, titled "Prices of Procured Balancing Reserves [17.1.C]."
I plan to attempt making the query on my own. Unfortunately, I lack the experience to do this easily.

**Comment by TwanKrmr** [comment]
Thank you for the response! I have found the right function in the branch "reserve". Is it possible to include this code into the main branch? I see there are additional functions which are related to the reserve capacity. Would be nice if these will be added into the main branch. So, it has more functions.

`def query_contracted_reserve_prices(self, country_code, start, end,
                                        type_marketagreement_type, psr_type = None):
        """
        Parameters
        ----------
        country_code : str
        start : pd.Timestamp
        end : pd.Timestamp
        type_marketagreement_type : str
            type of contract (see mappings.MARKETAGREEMENTTYPE)
        psr_type : str
            filter query for a specific psr type
        Returns
        -------
        str
        """
        domain = BIDDING_ZONES[country_code]
        params = {
            'documentType': 'A89',
            'controlArea_Domain': domain,
            'type_MarketAgreement.Type': type_marketagreement_type,
        }
        if psr_type:
            params.update({'psrType': psr_type})
        response = self.base_request(params = params, start = start, end = end)
        return response.text`

**Comment by fboerman** [comment]
hi those functions are already merged in the main repo its even in the readme? so I am assuming this fixes your issue. Next time please check before filing an issue ;) I thought you needed something else

**Comment by TwanKrmr** [comment]
Yes, sorry. We also thought we needed something else when we filled the issue. Thank you for the quick response!
