### ISSUE TITLE
query_installed_generation_capacity returns empty dataframe

### ISSUE THREAD

**Issue by mlibsig** [EnergieID/entsoe-py#289]
Hi all,

I am trying to retrieve installed generation capacity using this code:

> start = pd.to_datetime('2014-01-01').tz_localize('UTC')
> end = pd.to_datetime('2024-01-15').tz_localize('UTC')
> 
> client = EntsoePandasClient(api_key=_entsoe_api_key)
> tmp = client.query_installed_generation_capacity(start=start,end=end,country_code=lookup_area('DE'),psr_type=None)

I tried with a few different countries, they all returns empty dataframe.
Anyone has any idea how to fix this?

**Comment by fboerman** [comment]
Please decrease the timeframe you are querying. For example do it per year. I think that fixes this.

-------- Original Message --------

**Comment by jpaduart** [comment]
Installed capacity is published with a very specific timestamp, around on
the 31st of December (or 1st of January).
Try to query from Dec 15th to Jan 15th.
Extending the query over several years should be fast & work like a charm.

Johan.

Op ma 15 jan 2024 om 11:34 schreef fboerman ***@***.***>:

**Comment by mlibsig** [comment]
All seems okay now, changed initial date some date in december
