### ISSUE TITLE
Missing intraday imbalance in certain countries?

### ISSUE THREAD

**Issue by klaasv12** [EnergieID/entsoe-py#290]
Hi,

It seems that certain countries are missing the intraday imbalances. For instance 'NL'.

**Comment by fboerman** [comment]
hi please be a bit more specific, which query exactly do you mean and did you check the UI if the data is present there?

**Comment by klaasv12** [comment]
Hi, sorry for this after refreshing it showed up as N/E, I had a stale UI when I checked the prices for NL. It was just another country.
