### ISSUE TITLE
conda feedstock maintainers

### ISSUE THREAD

**Issue by FabianHofmann** [EnergieID/entsoe-py#298]
Dear developers, 

some years ago, I was creating a `entsoe-py-feedstock` on conda forge (https://github.com/conda-forge/entsoe-py-feedstock) to enable the installation of entsoe-py via conda. Since then, I have maintained the repo and it seems to be working very stably. However, I would like to slowly move out of the maintenance role and ask somebody from the developer side to take over if possible. It is really not a lot of work, just making sure that package dependencies are correct in place. Most of the times, everything runs automatically after a new version was released on pypi. 

I can just add the name(s) of the future maintainer(s) to the repo at https://github.com/conda-forge/entsoe-py-feedstock/blob/main/recipe/meta.yaml and that's it :)

**Comment by fboerman** [comment]
dear @FabianHofmann thank you for your efforts. I personally dont use conda stock and also regard conda install as not very usefull. I always use pip, even in conda environments. I thus dont want to maintain this myself.
If anybody else wants to pick this up feel free to do so!
