### ISSUE TITLE
ValueError: truncate requires a sorted index

### ISSUE THREAD

**Issue by tdekelver-bd** [EnergieID/entsoe-py#299]
In the function ``query_physical_crossborder_allborders`` some countries report values per 15 minutes and some per hour. When you query first a country that has only per hour (such as 'BE') and then a country that has values per 15 minutes (such as 'DE_LU') the index will not be sorted (you'll have first the hours with 0 minutes and later the 15v, 30 and 45 minutes (i.e. ``'2024-02-02 00:00:00+01:00', '2024-02-02 01:00:00+01:00', '2024-02-02 02:00:00+01:00' .... '2024-02-02 00:15:00+01:00', '2024-02-02 00:30:00+01:00', '2024-02-02 00:45:00+01:00'``) but this will cause a ``ValueError: truncate requires a sorted index`` on the line: [        df = df.truncate(before=start, after=end)](https://github.com/EnergieID/entsoe-py/blob/b6791e3052995dec1ae09ca0f01bec32fc6dfe4d/entsoe/entsoe.py#L2139)

This can be solved by adding a ``sort=True`` in the line [        df = pd.concat(imports, axis=1)](https://github.com/EnergieID/entsoe-py/blob/b6791e3052995dec1ae09ca0f01bec32fc6dfe4d/entsoe/entsoe.py#L2135)

Code to reproduce:
```py
from entsoe import EntsoePandasClient
import pandas as pd
client = EntsoePandasClient(api_key=api_key)
start = pd.Timestamp('2024-02-02 00:00:00+0100', tz='Europe/Brussels')
end = pd.Timestamp('2024-02-07 00:00:00+0100', tz='Europe/Brussels')
client.query_physical_crossborder_allborders(country_code='NL', start=start, end=end, export=True)
```

**Comment by fboerman** [comment]
thanks for reporting and giving a fix! I will handle it in the PR
