### ISSUE TITLE
query_installed_generation_capacity_per_unit broken

### ISSUE THREAD

**Issue by FabianHofmann** [EnergieID/entsoe-py#30]
The truncation in 

https://github.com/EnergieID/entsoe-py/blob/ae578fcdea56341c412bfc89966de944bbf7dc06/entsoe/entsoe.py#L761

leads to an error as the dataframe df does not have a DateTimeIndex. Commenting the line resolves the bug.

**Comment by JrtPec** [comment]
Absolutely correct, these truncates were introduced for all Time Series, obviously this one was in the wrong place. Fixed in version 0.2.9
