### ISSUE TITLE
query_contracted_reserve_prices returns data from legacy 17.1.C, rename to legacy and/or add retrieving reserve prices from 17.1.B&C 

### ISSUE THREAD

**Issue by larstellemannsaether-aenergi** [EnergieID/entsoe-py#303]
query_contracted_reserve_prices() returns data for 17.1.C (legacy) 

Not sure when this was marked legacy, but for NO and SE areas this method no longer return data for dates after Jan 18th.

This correlates with web, where legacy 17.1.C contains data up to January 18th: [Data View (NO2)](https://transparency.entsoe.eu/balancing/r2/balancingVolumesReservationPrice/show?name=&defaultValue=false&viewType=TABLE&areaType=MBA&atch=false&dateTime.dateTime=18.01.2024+00:00|UTC|DAY&dateTime.endDateTime=31.01.2024+00:00|UTC|DAY&contractTypes.values=A13&contractTypes.values=A01&contractTypes.values=A02&contractTypes.values=A03&contractTypes.values=A04&contractTypes.values=A06&reserveType.values=A96&marketArea.values=CTY|10YNO-0--------C!MBA|10YNO-2--------T&reserveSource.values=A04&reserveSource.values=A05&reserveSource.values=NOT+SPECIFIED&dv-datatable_length=10) 
After this, 17.1.B&C contains data from January 19th: [Data View (NO2)](https://transparency.entsoe.eu/balancing/r2/amountAndPricesPaidOfBalancingReservesUnderContract/show?name=&defaultValue=false&viewType=TABLE&areaType=SCA&atch=false&dateTime.dateTime=01.01.2024+00:00|UTC|DAY&dateTime.endDateTime=22.01.2024+00:00|UTC|DAY&reserveType.values=A51&schedulingArea.values=CTY|10YNO-0--------C!SCA|10YNO-2--------T&reserveSource.values=A04&reserveSource.values=A05&reserveSource.values=A03&direction.values=A02&direction.values=A03&direction.values=A01&timeHorizon.values=NIL&timeHorizon.values=A13&timeHorizon.values=A01&timeHorizon.values=A02&timeHorizon.values=A03&timeHorizon.values=A04&timeHorizon.values=A06&typeOfProduct.values=A03&typeOfProduct.values=A04&typeOfProduct.values=NIL&typeOfProduct.values=A02&typeOfProduct.values=A01&dv-datatable_length=10)

17.1.C is marked legacy in [Postman Collection link ](https://documenter.getpostman.com/view/7009892/2s93JtP3F6), which I received from support, and in the [docs](https://transparency.entsoe.eu/content/static_content/Static%20content/knowledge%20base/data-views/balancing/Data-view%20Price%20of%20Reserved%20Balancing%20Reserves.html)
As far as I can understand, it is replaced by 17.1.B&C which I think is not available through entsoe-py

I would propose:

* query_contracted_reserve_prices renamed to query_contracted_reserve_prices_legacy (or something similar)
* query_contracted_reserve_prices have one extra parameter process_type (can choose A51, A52, A47 or A46), change document_type from A89 to A81 and add businessType B95 to query

Or, in order not to break existing method, find another name for new method for document type retrieving prices with documentType A81, i.e.:
* keep query_contracted_reserve_prices unchanged
* add query_contracted_reserve_prices_procured_capacity (or something similar) with extra parameter process_type, using documentType A81 and businessType B95 (Procured capacity)

In addition to this, mappings.py needs to be updated for BSNTYPE, adding B95 for this to work when parsing result (business type values in [docs](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_businesstype))

**Comment by fboerman** [comment]
lets discuss this in your PR
