### ISSUE TITLE
Query query_unavailability_of_generation_units returns mismatching unit names

### ISSUE THREAD

**Issue by cantoyu** [EnergieID/entsoe-py#304]
When running function query_unavailability_of_generation_units, the returned unit names under column production_resource_name does not match with ENTSOE UI webpage

Did some de-bug, in the XML returned, there are two items that are considered as unit name - <production_registeredreource_name> and <production_registeredresource.psrtype.powersyste.resources.name>, what ENTSOE UI is displaying (and if you are mapping against individual unit but not site like me), is the latter

To solve this, go to parser module and find _unavailability_gen_ts, above it add another column name (whatever you want to call it), and add another get_attr and put get_attr('production_registeredresource.psrtype.powersystemresources.name')

Now the new script should return both unit name that matched with the UI and also the site name
![image](https://github.com/EnergieID/entsoe-py/assets/92871091/e556013e-a8b8-4b00-9fd1-42d40e582725)

**Comment by fboerman** [comment]
hi @cantoyu  thanks for this report. your fix sounds good! Could you please make a pullrequest for it? Thanks!

**Comment by fboerman** [comment]
pr provided and merged so closing this
