### ISSUE TITLE
ValueError: no types given - calling entsoe API query_generation(countryCode, start=start, end=end, psr_type=k)

### ISSUE THREAD

**Issue by AlessandroFossi** [EnergieID/entsoe-py#309]
I receive this error when calling the query_generation API for bidding zone IT_NORD with start = 01/01/2020 and end = 31/12/2020.
It seems happening only when I call the query for gen of psr_type = B10 (hydro_pumped_storage)

Any idea about how to solve this?

**Comment by fboerman** [comment]
hi I cannot reproduce this issue on the last version of the package. Please update your installation to the latest version as I only provide support on that one.
