### ISSUE TITLE
Inability to Access Both Market Prices for DE_LU Day-Ahead

### ISSUE THREAD

**Issue by blacksilvergeek** [EnergieID/entsoe-py#310]
I've encountered an issue where it's not possible to access both market prices for the DE_LU area's day-ahead pricing. According to the ENTSO-E Transparency Platform [link](https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=18.02.2024+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&resolution.values=PT15M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)), there are two markets available for DE_LU, but the library only provides data for one.

**Comment by fboerman** [comment]
Hi, you can put in a resolution argument as documented in the code here: https://github.com/EnergieID/entsoe-py/blob/master/entsoe/entsoe.py#L1162

However everything but the 60 min market is a very localised illiquid market and should be disregarded for serious analysis. The 60 min one is the real SDAC. Frankly I disagree with publishing the other ones on entsoe.

-------- Original Message --------

**Comment by blacksilvergeek** [comment]
Thank you. You are absolutely correct.
