### ISSUE TITLE
I cannot get price data for DE_LU: KeyError: '15T' query_day_ahead_prices

### ISSUE THREAD

**Issue by yusufgencer** [EnergieID/entsoe-py#318]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[26], line 6
      2 start = pd.Timestamp('2023-01-01', tz='UTC')
      3 end = pd.Timestamp('2023-02-01', tz='UTC')
----> 6 price = client.query_day_ahead_prices(country_code, start=start, end=end, resolution = '15min')
      9 price

File ~\anaconda3\Lib\site-packages\entsoe\decorators.py:124, in year_limited.<locals>.year_wrapper(start, end, *args, **kwargs)
    122 for _start, _end in blocks:
    123     try:
--> 124         frame = func(*args, start=_start, end=_end, **kwargs)
    125         if func.__name__ != '_query_unavailability' and isinstance(frame.index, pd.DatetimeIndex):
    126             # Due to partial matching func may return data indexed by
    127             # timestamps outside _start and _end. In order to avoid
   (...)
    132             # If there are repeating records in a single frame (e.g. due
    133             # to corrections) then the result will also have them.
    134             if is_first_frame:

File ~\anaconda3\Lib\site-packages\entsoe\entsoe.py:1185, in EntsoePandasClient.query_day_ahead_prices(self, country_code, start, end, resolution)
   1179 # we do here extra days at start and end to fix issue 187
   1180 text = super(EntsoePandasClient, self).query_day_ahead_prices(
   1181     country_code=area,
   1182     start=start-pd.Timedelta(days=1),
   1183     end=end+pd.Timedelta(days=1)
   1184 )
-> 1185 series = parse_prices(text)[resolution]
   1186 if len(series) == 0:
   1187     raise NoMatchingDataError

File ~\anaconda3\Lib\site-packages\entsoe\parsers.py:38, in parse_prices(xml_text)
     36 for soup in _extract_timeseries(xml_text):
     37     soup_series = _parse_timeseries_generic(soup, 'price.amount')
---> 38     series[soup_series.index.freqstr].append(soup_series)
     40 for freq, freq_series in series.items():
     41     if len(freq_series) > 0:

KeyError: '15T'

**Comment by fboerman** [comment]
what version of python pandas and entsoe-py are you running?

**Comment by yusufgencer** [comment]
(entsoe-py version: 0.6.7) I upgraded the pandas version from 2.1.4 to 2.2.1, and now it is working well. Thank you!
