### ISSUE TITLE
cannot import name 'EntsoePandasClient' from partially initialized module 'entsoe'

### ISSUE THREAD

**Issue by wtrabesinger** [EnergieID/entsoe-py#319]
Despite having installed the package correctly on my Python environment, I get this error when running the EntsoePandasClient code. Can anyone help ?

**Comment by fboerman** [comment]
hi this means that you borked your environment. Do you have a folder named entsoe next to your script? what version of python and the package are you running?

**Comment by wtrabesinger** [comment]
many thanks for the hint. obviously naming the file "entsoe.py" did not help ....

**Comment by fboerman** [comment]
Haha no problem it's a common mistake!

-------- Original Message --------
