### ISSUE TITLE
UTC info in datetime index is not correct

### ISSUE THREAD

**Issue by yusufgencer** [EnergieID/entsoe-py#320]
![image](https://github.com/EnergieID/entsoe-py/assets/72134051/8861bbcc-1951-4753-a1be-ffc5ad1eec77)
It should be +00:00

**Comment by fboerman** [comment]
Hi this is intended behaviour. Results are always converted to the timezone of the bidding zone that you requested. You can see that it does start at the time you requested. If you want the results in utc you have to convert it yourself.

-------- Original Message --------

**Comment by yusufgencer** [comment]
Thank you very much for explanation

**Comment by fboerman** [comment]
No problem!

-------- Original Message --------
