### ISSUE TITLE
Missing data query_contracted_reserve_prices [17.1.c Price of Reserved Balancing Reserves]

### ISSUE THREAD

**Issue by TwanKrmr** [EnergieID/entsoe-py#323]
Good afternoon,

While collecting data for the Dutch capacity prices in the imbalance markets, I've encountered a problem. The dataset only includes the FCR and aFRR down values, whereas the other necessary values are missing.

Could someone help?
![image](https://github.com/EnergieID/entsoe-py/assets/151535682/9c72f0ef-6537-4d1a-9305-4bf1ee796e39)

**Comment by fboerman** [comment]
Hi are you using the latest entsoepy and pandas versions?

-------- Original Message --------

**Comment by TwanKrmr** [comment]
I was on an old version. Thank you, it works now! Should have checked if updating works...

However, I now get the following warning:
\anaconda3\Lib\site-packages\entsoe\parsers.py:449: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df = df.groupby(axis=1, level = [0,1]).mean()

**Comment by fboerman** [comment]
Good that it works now. Yes that future warning you can ignore for now.

-------- Original Message --------
