### ISSUE TITLE
Daylight Saving Time and period.timeInterval

### ISSUE THREAD

**Issue by juhanijaakola** [EnergieID/entsoe-py#324]
Now in Finland we are 3 hours ahead of UTC (in normal time 2 hours). Tag createdDateTime has a 3 hours difference, but period.timeInterval and timeInterval have 2 hours difference.

Today at about 15 o'clock localtime I performed the following in Python REPL:

```
$ python
>>> from entsoe import EntsoeRawClient
>>> client = EntsoeRawClient(api_key="SECRET")
>>> import pandas as pd
>>> start = pd.Timestamp('20240415', tz='Europe/Helsinki')
>>> end = pd.Timestamp('20240417', tz='Europe/Helsinki')
>>> client.query_day_ahead_prices(country_code, start, end)
```

In the response I got:

```
<createdDateTime>2024-04-15T12:02:46Z</createdDateTime>
        <period.timeInterval>
                <start>2024-04-13T22:00Z</start>
                <end>2024-04-16T22:00Z</end>
        </period.timeInterval>

        <TimeSeries>
               <Period>
                                <timeInterval>
                                        <start>2024-04-13T22:00Z</start>
                                        <end>2024-04-14T22:00Z</end>

```

If Daylight Saving Time is honoured, shouldn't the time be 21:00Z instead of 22:00Z?

**Comment by fboerman** [comment]
Hi, two things here, first of all you are talking about the raw response. This package is only for parsing the raw response, only entsoe can change the raw response itself.
Second UTC time never changes that is the whole point of UTC. Only your local perception shifts.
If you feel that the raw response is wrong please file a ticket with ***@***.***

-------- Original Message --------

**Comment by juhanijaakola** [comment]
I sent e-mail to ENTSO-E regarding the DST inconsistency in the raw data.

I then noticed that EntsoePandasClient handles DST correctly (note the +03:00), good!

```
$ python     
>>> from entsoe import EntsoePandasClient
>>> import pandas as pd
>>> client = EntsoePandasClient(api_key="SECRET")
>>> start = pd.Timestamp('20240416', tz='Europe/Helsinki')
>>> end = pd.Timestamp('20240417', tz='Europe/Helsinki')
>>> ts = client.query_day_ahead_prices(country_code, start=start, end=end)
>>> ts
2024-04-16 00:00:00+03:00     35.01

```

**Comment by juhanijaakola** [comment]
I got reply from ENTSO-E: "The market timezone of Finland (CET/CEST) is different from the geographical timezone (EET/EEST). This is why you receive this response."
