### ISSUE TITLE
`EntsoePandasClient.query_wind_and_solar_forecast()` fails for Norway

### ISSUE THREAD

**Issue by mkaut** [EnergieID/entsoe-py#326]
Calling `client.query_wind_and_solar_forecast()` with Norwegian bidding zones (`NO_1` to `NO_5`) and `client = EntsoePandasClient(api_key)` raises `entsoe.exceptions.NoMatchingDataError`.
The same call with `DK_1` works fine.

I have also tried: 
- `NO` - raises the same exception
- `NO1` and `NO-1` - fails with `IndexError: list index out of range` in `mappings.py`

Is this a bug, or am I missing something?

**Comment by mkaut** [comment]
It looks like intraday forecasts are not available in Norway, so `NoMatchingDataError` may actually be considered a correct response.
I am therefore closing the issue (since I see no way of deleting it completely).

**Comment by fboerman** [comment]
Hi did you check on the UI the data is actually there?

-------- Original Message --------
