### ISSUE TITLE
When will Georgia be added to the mappings file?

### ISSUE THREAD

**Issue by sicallan** [EnergieID/entsoe-py#327]
https://github.com/EnergieID/entsoe-py/blob/4560a5d7d96d964f5cf50370d576662f190fd500/entsoe/mappings.py#L73

There was a PR at some point which added this line in:
    GE =            '10Y1001A1001B012', 'Georgia',                                      'Asia/Tbilisi',

I added it locally and it enabled me to pull data for Georgia, it would be great if you could sort permanently. 
Cheers

**Comment by sicallan** [comment]
Any updates on this? Thanks

**Comment by fboerman** [comment]
hi @sicallan  done per #325

**Comment by sicallan** [comment]
Many thanks!
