### ISSUE TITLE
Date format for query

### ISSUE THREAD

**Issue by Jancs-E** [EnergieID/entsoe-py#333]
Hi!
I am trying to pull DA hourly price data from ENTSO-E for the single (current, or DA) using Pandas client, but whatever I do with the dates, I am getting

Traceback (most recent call last):
  File "/home.../NPS-ENTSOE-00.py", line 30, in <module>
    response = client.query_day_ahead_prices(country_code, start, end)
  File "/usr/lib64/python3.9/site-packages/entsoe/decorators.py", line 103, in year_wrapper
    raise Exception(
Exception: Please specify the start and end date explicity withstart=<date> when calling this function

the last tried:
start = pd.Timestamp('20240201', tz='Europe/Riga')
end = pd.Timestamp('20240201T2359', tz='Europe/Riga')
response = client.query_day_ahead_prices(country_code='LV', start, end)

I have API key (token), module - latest from repository. Python - 3.9.18

The raw one works (seems), at least I am getting xml

**Comment by fboerman** [comment]
Hi, you need to use them as named keyword arguments in the function call. This has to do with some decorator magic which the library uses. If you do start=start and end=end it will work. See the readme for examples.

-------- Original Message --------

**Comment by Jancs-E** [comment]
Ou... so stupid of me... and AI

**Comment by fboerman** [comment]
That's why shouldn't use ai for coding ;) it makes you stop thinking

-------- Original Message --------

**Comment by Jancs-E** [comment]
I fell in this trap for the second time just out of the wish to quickly test the concept
