### ISSUE TITLE
Iceland mapping

### ISSUE THREAD

**Issue by HuxleySumitomo** [EnergieID/entsoe-py#337]
In geo.mappings.Area the eic codde for Iceland is `IS`. However, the [ENTSOE web lookup](https://www.entsoe.eu/data/energy-identification-codes-eic/eic-approved-codes/) has the EIC code listed as `10Y1001A1001A958`.

**Comment by fboerman** [comment]
hi, this is because in the specific transparancy guide it is listed as such: https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html
if you believe this is in error please contact entsoe on it. I would prefer to stick to their guide
