### ISSUE TITLE
EntosePandasClient.query_generation_per_plant() results in NoMatchingDataError for DE and DK

### ISSUE THREAD

**Issue by NicbechVolt** [EnergieID/entsoe-py#338]
I am encountering an issue when querying generation per plant data for DK and DE using the Entso-e API via entsoe-py. The query results in an error message, while the same query works fine for SE. 

### Code
```python
start = pd.Timestamp('20240601', tz='UTC')
end = pd.Timestamp('20240701', tz='UTC')
country_code = 'DK'

data = client.query_generation_per_plant(country_code=country_code, start=start, end=end)
```

### Error message
![image](https://github.com/user-attachments/assets/02b71cac-2719-456f-a1a1-b610b4bc1b74)

It looks like the reason is empty data, but is this a problem with the Entso-e API or entsoe-py? 
Any guidance or suggestions on how to troubleshoot this further would be greatly appreciated.

**Comment by fboerman** [comment]
Have you tried to use the bidding zone DK_1 or DK_2 instead of country code?

⁣Get BlueMail for Android ​

**Comment by NicbechVolt** [comment]
I have tried that as well, but unfortunately, I get the same error.

**Comment by fboerman** [comment]
hi! you need to use control area for this endpoint, so try DK_CA or directly 10Y1001A1001A796
this is a common issue that its not always clear what to use here, I am not sure how to make that more clear, need to think about that.
