### ISSUE TITLE
Issue with Entso-e changes in EntsoePandasClient.query_aggregated_bids

### ISSUE THREAD

**Issue by timhaj** [EnergieID/entsoe-py#339]
When running 
```python
client = EntsoePandasClient(api_key=api_key)
aggregated_bids = client.query_aggregated_bids("10YSI-ELES-----O", process_type="A51", start=start, end=end)
```

, it throws the following error: 
```python
flow_direction = direction[soup.find('flowdirection.direction').text]
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'A04
```

My coworker, working with XML parsing, also encountered this problem, which happened because of recent Entso-e API changes. The product direction changed from »flowDirection.direction« to »original_MarketProduct.marketProductType«. It should be worth noting, when using the German country code ("10YDE-ENBW-----N"), there are no issues. Maybe the error is somewhere else, so any some guidance or troubleshoot suggestions would be appreciated.

**Comment by fboerman** [comment]
hi this must have been a temporary bug on entsoe side because your snippit works perfectly now!

**Comment by timhaj** [comment]
Hey,
yeah, it randomly started to work again. At least it works now, thanks!
