### ISSUE TITLE
SSL Error fixed? By using "urllib3" instead of "requests"

### ISSUE THREAD

**Issue by Simongabsschon** [EnergieID/entsoe-py#340]
Hello, 

(this is my first post here, I am quite new into programming...)

I had an issue with my Company-PC, where there was a SSL-Error. I realised that requesting by the "urllib3" library works instead of the "requests" library. I somehow was able to replace the libraries and maybe fix the issue (it works for now). 

Here is the code, I think it would be cool if it was possible to switch the library in entsoe-py. :)

(sry for my bad english)
[entsoe.txt](https://github.com/user-attachments/files/16661878/entsoe.txt)
[decorators.txt](https://github.com/user-attachments/files/16661879/decorators.txt)

**Comment by fboerman** [comment]
hi! great that you managed to solve your own problem! however this is most likely related to restrictions on your company network. I do not want to comprise the whole library for that. most likely requests enables some more sane defaults then urllib, which explains why this would work
You can keep using it yourself of course but I wont merge this into the main package sorry.
