### ISSUE TITLE
New Production Type: Energy storage

### ISSUE THREAD

**Issue by robingrether** [EnergieID/entsoe-py#342]
Recently, ENTSO-E added the new production type _Energy storage_. As far as I am aware of the code of this project, the new type needs to be added to the `PSRTYPE_MAPPINGS` dictionary in `mappings.py`. Following the new [API documentation](https://documenter.getpostman.com/view/7009892/2s93JtP3F6#d4383852-1e53-4f98-a028-e0d9ac73d5f5), the PSR type identifier for _Energy storage_ is _B25_. Until now though, no country/bidding zone/control area has published any data under this category.

**Comment by fboerman** [comment]
sure thats a small thing, ill accept the PR thanks!
