### ISSUE TITLE
Dependency on pandas>=2.2.0 makes it impossible to use for a home assistant integration.

### ISSUE THREAD

**Issue by Roeland54** [EnergieID/entsoe-py#351]
Hi I am a collaborator on the [Entso-e integration](https://github.com/JaccoR/hass-entso-e) for home assistant. 
As from January of this year home assistant core has [pinned pandas to 2.1.4](https://github.com/home-assistant/core/commit/6cf8a3e5d1cbacc077a813b290d0964159786c5b). So this made it impossible to use versions of entsoe-py that require pandas>=2.2.0. 

As the entsoe api xml format for day ahead prices has changed now. It is not possible to use the older versions of this entsoe-py anymore. To solve this issue we have stopped using this library and implemented the api call without external library. 

Getting home assistant to drop the pinning of pandas would probably difficult. 
And it will probably not be feasible to lower your dependency requirements any time soon. But I just wanted share our experience.

**Comment by fboerman** [comment]
hi @Roeland54  sorry to hear that. If I drop pandas version it will create other problems in the library. regardless I believe most projects will eventually upgrade anyway. It is too much work for me to drop it back to lower version for the sake of your library I am sorry.

very nice plugin btw! I will answer some issues to help with understanding what is going on with the belgian prices.
