### ISSUE TITLE
Change in Location of Day Ahead Prices on Entso

### ISSUE THREAD

**Issue by ruxandramitu14** [EnergieID/entsoe-py#352]
### Hello,

It appears that there has been a recent change on Entso, specifically where the day-ahead prices are located. This has affected the function query_day_ahead_prices(country_code, start=start_ts, end=end_ts) as it no longer returns the correct day-ahead prices.

The current function might be pointing to an outdated location for retrieving the prices, as indicated by the following screenshot:

![image](https://github.com/user-attachments/assets/70b56bf1-8f8f-4b50-863f-1d5452be4fa1)
Would it be possible to update the function to reflect the new location for day-ahead prices?

Thank you for your time!

**Comment by fboerman** [comment]
this has been fixed in the latest version. please first update before opening an issue thank you!
