### ISSUE TITLE
Distinguish between SDAC and EXAA values with "classificationSequence_AttributeInstanceComponent.position"

### ISSUE THREAD

**Issue by Roeland54** [EnergieID/entsoe-py#354]
The current logic of separate the data of the SDAC and EXAA when retrieving German prices is to request the 60min resolution for SDAC and the 15min resolution for EXAA. This feels like an unsustainable way, definitely when the SDAC would change to also use the 15min resolution. Now currently the response contains a 'classificationSequence_AttributeInstanceComponent.position' tag which is 1 for SDAC  and 2 for EXAA. The field can even be passed as parameter to only receive one or the other. It could be a nice way of clearly distinguish the datasets. But I can't find an explanation of the 'classificationSequence_AttributeInstanceComponent.position' in the documentation anywhere so I am just guessing a.t.m.  My proposal would be to start using this field instead of the resolution if we can confirm its meaning.

**Comment by fboerman** [comment]
hi! interesting observation!  I indeed see in the postman reference here: https://documenter.getpostman.com/view/7009892/2s93JtP3F6#3b383df0-ada2-49fe-9a50-98b1bb201c6b this parameter
however when I tried to query with it I always get no data. did you try it yourself as well?

**Comment by Roeland54** [comment]
Mmm yes I did a quick test with receiving german data which worked:
`https://web-api.tp.entsoe.eu/api?documentType=A44&securityToken=<SECRET>&periodStart=202410060000&periodEnd=202410071300&in_domain=10Y1001A1001A82H&out_domain=10Y1001A1001A82H&classificationSequence_AttributeInstanceComponent.Position=1`

But I now also tested it for the belgian zone and it does not return any data. Seems like it only works for the german zone then which makes it less usable.

**Comment by fboerman** [comment]
yeah thats a bit sad. I guess we need to close this for now and see how it works when 15min mtu goes live
