### ISSUE TITLE
 Unable to Access Day-Ahead Prices in Python (version 0.6.9) – Length mismatch

### ISSUE THREAD

**Issue by RomanProcyk** [EnergieID/entsoe-py#355]
I'm experiencing an issue with accessing Day-Ahead prices using the ENTSOE API in Python (version 0.6.9). Despite updating to the latest version.

When I run the below code:

start = pd.Timestamp('20241005', tz='Europe/Sofia')
end = pd.Timestamp('20241006', tz='Europe/Sofia')

client.query_day_ahead_prices('BG', start=start, end=end)

 "Length mismatch: Expected axis has 94 elements, new values have 96 elements"

This is the same issue that @NewEnergyAnalyst ran into the previous week.

**Comment by kugelfish42** [comment]
Same problem here. I have been using a pretty old version which suddenly stopped working sometime after Oct 8 - upgrade to latest release via pip did not help either. At the same time, I also started getting a "max 1 year of data" access error from the API. Presumably something changed on the ENTSOE side last week?

**Comment by NewEnergyAnalyst** [comment]
> hi after writing a fix for #350 this problem no longer occurs. if you can reproduce it in the latest version please reopen the issue

Unfortunately, it does not work. Another possible solution?

Thanks...
