### ISSUE TITLE
Missing timezone-conversion in query_day_ahead_prices()

### ISSUE THREAD

**Issue by bantu** [EnergieID/entsoe-py#356]
https://github.com/EnergieID/entsoe-py/commit/5e9f4c68d07f476a12779597fa315d949c30129a#diff-80a09bedd7384672dc1f3edebe8107fa26dcc992e71e812dc8b142b0a2ace615L1234 removed the statement `series = series.tz_convert(area.tz)`. Thus, in version 0.6.12 the returned dataframe no longer has a timezone assigned. This was the case in version 0.6.11. I do not believe this change was intended as it changes the format of the returned dataframe.

**Comment by fboerman** [comment]
hi @bantu many thanks for pointing at this. this was indeed a mistake by me to get the fix quickly out of the door to help people. my apologies!
please note that timezone does not disappear. the results still are timezone aware but they are simply not converted to the local timezone so are always in UTC. I will quickly push a fix

**Comment by bantu** [comment]
Excellent.

Confirming fix.

Thank you
