### ISSUE TITLE
DA price download does not work anymore 

### ISSUE THREAD

**Issue by ThomasPade** [EnergieID/entsoe-py#359]
Dear Entsoe-py community ,

I noticed that the day ahead price download with entsoe client isn't working anymore . This is probably since last week the case .
Do I missed something ? Can you please help with that ?
![Capture](https://github.com/user-attachments/assets/1e45a1ec-b3ae-4fed-bf95-92f1156f10c0)

Thanks a lot.

Thomas

**Comment by fboerman** [comment]
Please update the library to latest version

⁣Get BlueMail for Android ​

**Comment by MurielleGY** [comment]
Use :
pip install --upgrade --force-reinstall entsoe-py

**Comment by ThomasPade** [comment]
Dear Entsoe-py community,

it works . Thanks a lot for your support!
