### ISSUE TITLE
Duplicate area code in mappings.py leading to bugs

### ISSUE THREAD

**Issue by morrisonmaxw** [EnergieID/entsoe-py#369]
Area code 10Y1001A1001A82H is used for both DE_LU and LU_BZN. It looks like only DE_LU is valid? [Entsoe Areas Ref](https://transparencyplatform.zendesk.com/hc/en-us/articles/15885757676308-Area-List-with-Energy-Identification-Code-EIC)

This is leading to unexpected results in data processing. 

One example is I am looping through country codes for EntsoePandasClient.query_day_ahead_prices and get a duplicate result for DE_LU and LU_BZN.

Another example is I am extracting mappings.py into JSON to build my data model and LU_BZN gets omitted:

`import json
from entsoe import mappings

area = mappings.Area
psrtype = mappings.PSRTYPE_MAPPINGS
docstatus = mappings.DOCSTATUS
bsntype = mappings.BSNTYPE
marketagreementtype = mappings.MARKETAGREEMENTTYPE
documenttype = mappings.DOCUMENTTYPE
processtype = mappings.PROCESSTYPE
neighbours = mappings.NEIGHBOURS

def enum_to_json(enum_class):
    members = []
    for member in enum_class:
        print(member)  # Debugging line
        members.append({
            "area_key": member.name,
            "code": member.code,
            "meaning": member.meaning,
            "timezone": member.tz
        })
    return members

data = {
    "areas": enum_to_json(area),
    "psrtype": psrtype,
    "docstatus": docstatus,
    "bsntype": bsntype,
    "marketingagreementtype": marketagreementtype,
    "documenttype": documenttype,
    "process_types": processtype,
    "neighbours": neighbours
}

json_output = json.dumps(data, indent=4)

with open('entsoe_mappings.json', 'w') as file:
    file.write(json_output)`

**Comment by fboerman** [comment]
luxenburg and germany share the same bidding zone so this is expected behaviour. if you dont want to get results from both you have to adjust your code for this.
