### ISSUE TITLE
duplicated timestamps for ranges longer than one year

### ISSUE THREAD

**Issue by welworx** [EnergieID/entsoe-py#38]
When looking for date ranges that include more than one year, the result has (at least) a duplicate element.

client = EntsoePandasClient(api_key=api_key)

start = pd.Timestamp('20180101', tz='UTC')
end = pd.Timestamp('20190901', tz='UTC')

dat = client.query_day_ahead_prices('AT', start=start, end=end)

`dat.index.shape`
(8041,)
`dat.index.unique().shape`
(8040,)
`dat[dat.index.duplicated()]`
2019-01-01 01:00:00+01:00    39.76

------------
```
start = pd.Timestamp('20150101', tz='UTC')
end = pd.Timestamp('20190901', tz='UTC')
dat = client.query_day_ahead_prices('DK-1', start=start, end=end)
dat.shape
```
(40898,)
`dat.index.unique().shape`
(40894,)

`dat[dat.index.duplicated()]`
2016-01-01 01:00:00+01:00    16.04
2017-01-01 01:00:00+01:00    20.90
2018-01-01 01:00:00+01:00    26.43
2019-01-01 01:00:00+01:00    10.07

--------------

I assume this comes from the splitting into yearly blocks.

Version: 0.2.10

**Comment by JrtPec** [comment]
fixed in 0.2.14. Thanks for the issue!
