### ISSUE TITLE
Imbalance prices not available for bidding zones but only for countries

### ISSUE THREAD

**Issue by maksym-semenyuk** [EnergieID/entsoe-py#39]
When using request for imbalance prices, the expected area code is mapped from DOMAIN_MAPPINGS, thus only allows to specify country code.

When reading imbalance prices manually from the Transparency Platform it is possible to access imbalance prices per bidding zone which should also be the case when using Python API.

Suggestion - substitute domain in query_imbalance_prices from DOMAIN_MAPPINGS to BIDDING_ZONES.

**Comment by JrtPec** [comment]
New approach: in version 0.3.0 the `Area` object is introduced. You can now specify any area (country, bidding zone, ...) you'd need. It is also backwards compatible with (most) country codes we used before.

So now you can do: `country_code='BE'`, `country_code=Area.DE_AMPRION`, or `country_code='10YDE-VE-------2'`. Whatever you need.
