### ISSUE TITLE
Time zone ignored in start and end parameters to base request

### ISSUE THREAD

**Issue by atantet** [EnergieID/entsoe-py#42]
Hi,
When giving time-zoned timestamps to `start` and `end` arguments of, e.g., `EntsoePandasClient.generation`, the latter are converted to strings without timezones in `entsoe.base_request` and given as `periodStart` and `periodEnd` parameters to `requests.Session().get`.
In the [ENTSO-E Transparency API documentation](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html), it reads that these parameters use local time-zones.

However, the `TimeInterval` parameter should allow one to give time-zoned time intervals in ISO UTC format.

Could we add a `TimeInterval` argument to give to the query functions instead of the `start` and `end` arguments to ask for data in ISO UTC format?

The code to reproduce this behavior:

```
from entsoe import EntsoePandasClient
client = EntsoePandasClient(api_key=security_token)

start = pd.Timestamp('2015-01-01T00:00Z') 
end = pd.Timestamp('2016-01-01T00:00Z') 
client.generation('SE-4', start=start, end=end, psr_type='B19', lookup_bzones=True)
```

**Comment by atantet** [comment]
Thanks for the reply and sorry for my very late reply.
Indeed it does not seem to change anything.
However, I have tried it for France and Spain and you get exactly the right timestamps, only they are in respective local times. A df.index.tz_convert(None) gives the requested UTC timestamps.

However, there is an issue with Sweden, but it seems to be coming from ENTSOE. The time zone of the index is "'Europe/Stockholm' LMT+1:12:00 ST", so that the conversion to UTC is one hour ahead. If the time zone of the index was GMT+1, as should be, everything would be fine.

Do you think we should warn ENTSOE ?

Thanks for the great work package anyway!

**Comment by JrtPec** [comment]
If you believe there is an issue with the API response from ENTSO-E, best to contact them directly I suppose

**Comment by fboerman** [comment]
since this seems to be an entsoe problem im going to close this issue as part of a clean up. if you still encounter problems with the package @atantet please reopen the issue or file a new one
