### ISSUE TITLE
Issue with Installed Capacity per Production Type 

### ISSUE THREAD

**Issue by Cordou** [EnergieID/entsoe-py#44]
I would like to download the installed capacity per production type for each country. For this, I am using the following:

client.query_installed_generation_capacity(country_code, start=start,end=end, psr_type=None)

For some country codes, I get an empty dataframe; even though the data exist online, e.g. for FI (Finland). Is there a reason for that?

Thank you in advance.

**Comment by jpaduart** [comment]
First thing to do is to check whether the web interface publishes the info you are looking for.
If that is the case, paste the query in a browser and look at the xml response, and see what happens. Easy!

**Comment by francoe** [comment]
I have encountered this same problem when trying to pull data for Finland and Greece using the same method (client.query_installed_generation_capacity(country_code, start=start,end=end, psr_type=None)).

**Comment by JrtPec** [comment]
This could have something to do with the installed capacities being returned on a yearly basis (so dated on 1 Jan.), and then getting truncated by `start` and `end`. In #054562e20ca3038edd57156ce9888fb6ae5ecda9, I've fixed the truncate to clip to the beginning and end of the year for these methods.

Check if it works, in version 0.3.0? (releasing very soon)

**Comment by hardikod** [comment]
I had the same problem, and upgrading to the current version (0.3.2) solved this issue. Generation capacities are now downloaded nicely.
