### ISSUE TITLE
Transmission capacity forecast

### ISSUE THREAD

**Issue by Zaher1975** [EnergieID/entsoe-py#49]
I believe that in addition to 'query_crossborder_flows', it is quite straightforward to create 'query_crossborder_Capacity_Forecast' using documenttype 'A61'.  The codes will be equivalent, except that extra granularities ( contract_MarketAgreement = 'A01','A02','A03') are allowed for the capacity forecasts.

**Comment by fgenoese** [comment]
@JrtPec had to add four methods but all of them are based on query_crossborder()
