### ISSUE TITLE
Truncate requires a sorted index

### ISSUE THREAD

**Issue by ererkka** [EnergieID/entsoe-py#52]
Executing for example this query for Belgian offshore wind for the year 2018

```python
client.query_generation('BE', 
    start=pd.Timestamp('2018-01-01', tz='UTC'), 
    end=pd.Timestamp('2019-01-01', tz='UTC'), 
    psr_type='B18'
)
```
results in a `ValueError: truncate requires a sorted index` from pandas which requires the truncated series to be sorted first. This happens on line [903 in entsoe.py](https://github.com/EnergieID/entsoe-py/blob/e62b8ec93dd02bacdac58d02c3c3bc5195b80b43/entsoe/entsoe.py#L903):

     df = df.truncate(before=start, after=end)

If I manually do

     df = df.sort_index().truncate(before=start, after=end)

in a debugger, it works fine.

I’m running entsoe-py v. 0.2.12 and pandas v. 1.0.3.

**Comment by JrtPec** [comment]
Will be fixed in version 0.3.0
