### ISSUE TITLE
from entsoe import EntsoePandasClient does not work

### ISSUE THREAD

**Issue by vijapija** [EnergieID/entsoe-py#54]
Thank your for the downloader. I am trying to create one from entso-e that takes generation on a unit basis, which is usually given only in 24-hour frames, and instead to extend the downloaded generation data to a calendar year series. 
For this I wanted to test your downloader and to seek inspiration.
However, although I installed entsoe-py (pip install), all the requirements were satisfied, I fail to import as the first step 'from entsoe import EntsoePandasClient'. The module is not found. I am using  Python 3, Jupiter notebooks. What am I doing wrong? Do not judge me for not knowing - I am quite new in this downloaders' business.

**Comment by JrtPec** [comment]
Seems like you might be installing the package to a different Python environment than the one you're using in your Notebook. Try `python3 -m pip install entsoe-py`, see if that changes anything.
