### ISSUE TITLE
NoMatchingDataError for query_load with country_code 'DE' (Germany)

### ISSUE THREAD

**Issue by geertscholma** [EnergieID/entsoe-py#55]
Compliments for the package, it was very useful for our covid-19 research / blogpost https://amperon.co/blog/covid-19-impact-on-global-energy-markets/

Almost everything I desired worked, except downloading the German load data.
Running the next code block in my jupyter notebook with my own api_key returned a NoMatchingDataError. Running the same for country_code = 'FR' would return proper data
Also running the  client.query_wind_and_solar_forecast for country_code = 'DE' would work

from entsoe import EntsoePandasClient
import pandas as pd
client = EntsoePandasClient(api_key='xxx')
start = pd.Timestamp('20200108', tz='Europe/Brussels')
end = pd.Timestamp('20200109', tz='Europe/Brussels')
country_code = 'DE'
entsoe_load = pd.DataFrame(client.query_load(country_code, start=start,end=end)).reset_index()
entsoe_load.head()

Exact outcome:

NoMatchingDataError: between 2020-01-08 00:00:00+01:00 and 2020-01-09 00:00:00+01:00

NoMatchingDataError                       Traceback (most recent call last)
<ipython-input-3549-dd3d4186bfed> in <module>()
      5 end = pd.Timestamp('20200109', tz='Europe/Brussels')
      6 country_code = 'DE'
----> 7 entsoe_load = pd.DataFrame(client.query_load(country_code, start=start,end=end)).reset_index()
      8 entsoe_load.head()

/home/geert/.local/lib/python3.6/site-packages/entsoe/entsoe.py in year_wrapper(start, end, *args, **kwargs)
    740         if sum([f is None for f in frames]) == len(frames):
    741             # All the data returned are void
--> 742             raise NoMatchingDataError
    743 
    744         df = pd.concat(frames, sort=True)

NoMatchingDataError: 

About my Jupyter Notebook:

The version of the notebook server is: 5.2.2
The server is running on this version of Python:
Python 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Current Kernel Information:
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
IPython 5.5.0 -- An enhanced Interactive Python.

**Comment by quintinnicolas** [comment]
Hello Geert,

You could use the domain "DE-LU" for your query, that should work

**Comment by geertscholma** [comment]
Hi quintinnicolas, I just tried that, but then I get the data from bidding zone DE-LU which contains different data, so not sure if this a complete fix. Thanks anyway for the help!

**Comment by jpaduart** [comment]
It has to do with the bidding zone/control area zone definitions - I
recently made a fix locally, will push it asap.

Johan.

Op wo 15 apr. 2020 om 12:39 schreef geertscholma <notifications@github.com>:

**Comment by geertscholma** [comment]
that sounds great, thanks!

**Comment by fgenoese** [comment]
Worth noting that data can be queried per country, per control area or per bidding zone. For Germany, there is quite a mix-up, due to the fact that the bidding zone covers DE-LU today and used to cover DE-AT-LU.

Before implementing the fix, we need to make sure that it does not break any code. Some functions in the code refer to bidding zones, while others refer to country codes:
```
domain = DOMAIN_MAPPINGS[country_code]
domain = BIDDING_ZONES[country_code]
```

Could you check for inconsistencies?
