### ISSUE TITLE
Polygons for BIDDING_ZONES

### ISSUE THREAD

**Issue by emilhe** [EnergieID/entsoe-py#57]
Would it be possible to add the geographical polygons for each bidding zone? Maybe as GeoJSON files?

For countries like Belgium it is easy as there is a 1:1 mapping between country and bidding zone. However, for the UK, France, Portugal, the Netherlands, Denmark, Sweden, Norway, Italy and Spain the mappings is more complex.

**Comment by JrtPec** [comment]
We could add anything to the package, if we want ;-)

Could you maybe give me an intended use case? So I can judge what information you're after exactly.

**Comment by emilhe** [comment]
Haha, that's true ;)

The intended use case was for an application where the user selects the bidding zone by clicking on a map. To draw the polygons on the map, and to transform the user click, which is a (lat,lon) tuple, into a bidding zone, the bidding zone polygons are needed. The polygons could be e.g. lists of (lat,lon) tuples or geosjon data.

**Comment by JrtPec** [comment]
Well, in the next version, 0.3.0, which I will be releasing later tonight, a new `Area` class is introduced. This is basically an Enum containing some data about each Area (country, bidding zone, ...). We could easily add some more fields to this class, to include some geodata about each Area.

**Comment by emilhe** [comment]
That is exactly the structure I also ended up with in my app. The object is even called Area :)

It seems like the right place to put the geodata.

**Comment by ph-eip** [comment]
My project would also benefit from zone boundaries.  The use case is that energy generation assets in my application that have coordinates can be linked to their corresponding bidding_zone and therefore the wealth of data provided by ENTSO-E.

I have tried to locate a consistent source for this data for my project with only partial success:

This cool project [https://github.com/tmrowco/electricitymap-contrib](electricitymap-contrib) contains electricity zones as geojson in the following folder: electricitymap-contrib/web/third_party_maps/ - there is a long discussion on how they got the zone boundaries for their map from multiple sources in this issue https://github.com/tmrowco/electricitymap-contrib/issues/917 which links to other issues.  Perhaps they would be open to open-sourcing the boundaries in a standalone repository?

![image](https://user-images.githubusercontent.com/85677784/129165838-ded73a13-f0be-4db7-98f2-ce1851fa4b40.png)

[https://www.epexspot.com/en/market-data?data_mode=map](https://www.epexspot.com/en/market-data?data_mode=map) also has the zone boundaries in their map available as svg polygons in the source code, e.g.:

```html
<polygon class="st4 js-map-polygon has-value" data-code="NO3" points="479.3,246.3 477.8,243 477.2,235.4 468.8,233.7 459.3,233.5 457.6,232 439.7,230.7 437,226.6
                      442,226 444.6,225.5 445.8,229.1 447.9,229.1 446.4,224.4 450.2,223.3 453.4,225.5 459.6,229.1 462.8,227.4 459.6,224.4
                      454.6,219.2 459.6,213.1 464.9,213.7 472.2,219.7 476,217.8 467.8,210.1 470.4,208.5 473.6,210.1 479.8,215.6 481.6,213.7
                      479.2,210.9 484.2,208.5 477.2,203.8 476.6,201.3 484.8,201.3 489.2,204.9 492.4,204.3 495.6,201.3 501.2,201.9 502.9,207.4
                      506.7,204.9 513.2,203.8 522,196.1 522,189.5 513.8,193.1 514.4,197.2 509.4,199.1 506.7,196.6 500.6,196.6 501.8,193.6
                      506.2,188.9 513.2,180.1 522.6,180.7 524.9,176 524.3,170.8 527.5,165.9 531.4,164.8 535.2,166.7 538.1,163.1 540.6,164.5
                      543.6,167.3 546.8,170.3 550.1,171.2 552,173.4 554.5,175.5 548.3,179 548.9,183.7 556,183.7 554.5,190 551.6,193.1 539.6,192.5
                      532.5,200.2 531.7,211.8 531.7,212.4 526.7,214.4 526.7,215.5 519,216.4 517.1,218.7 512.1,219 504.8,221.3 505.1,222.9
```

But I don't know what coordinate system these points represent...

![image](https://user-images.githubusercontent.com/85677784/129166017-eb4e783a-c173-4c6a-a24a-523d552cb268.png)

**Comment by fboerman** [comment]
hi @ph-eip I recently looked into this and from my search electricitymap is the closest you can get to accurate data.
 as an experiment I build a github action workflow of extraction the geojson from electricitymap which you can find here: https://github.com/fboerman/energymarket-map/tree/geojson-generation and you can download the geojson here: https://github.com/fboerman/energymarket-map/releases/tag/geojson-202106

if you have any more accurate source let me know

**Comment by Evelyn0** [comment]
Hi @fboerman I looked your github repo. I have a question, maybe it is silly, but i am not able to identify the countries or regions with your files. I want to say, I though that the AT.geojson was the polygon for Austria but i am wrong. Do you have a file with the abbreviations that can be shared ?

**Comment by Evelyn0** [comment]
Hi @fboerman  your repo has valuable information. I have a question about the geojson files. I downloaded the folder with the information but I am not able to distinguish which file belongs to each country or zone. For example, I though that GE.geojson was the polygon for Germany but I am wrong. Could you provide a file with the abbreviations, please?

**Comment by ph-eip** [comment]
Hi @Evelyn0, GE is not Germany but Georgia.

You should familiarize yourself with the ISO-alpha-2 codes, e.g.: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by fboerman** [comment]
hi @Evelyn0 and @ph-eip yes that is correct it should be ISO-alpha-2

if you are working with it maybe you can help me solve an annoying problem. I need to dissolve the geojsons in the final build step, but changes something in the way the geojson is then saved. I tried to plot the geojsons with plotly in a chloropleth map. However when using the files after the dissolve step (the release of 202110) then it silently fails with plotting the map. when using the 202106 version it does work but the geojson is ugly. I have tried many things but cant get this too work. 

if you manage to have some python code to plot a choropleth map with my generated geojson files I would be very grateful if you could share it. Thanks!

**Comment by Evelyn0** [comment]
Hi @fboerman unfortunately I am using your files in R. I used the 202110 and 202106 versions and nothing changes in my chloropleth maps.

**Comment by IoannisKountouris** [comment]
@Evelyn0 

Hi, I would like to ask if it's possible to share an R code on how are you using @fboerman geojson files in R. I am trying to build a dashboard with shiny for my PhD project, where I want to plot spatial electricity prices projections.  If you have a code formulation would be really helpful :)

**Comment by Evelyn0** [comment]
Hi @IoannisKountouris  maybe is a little late for this. I have a repo called SpatialElecMod there you will find the code for plotting the geojson files in R

**Comment by fboerman** [comment]
hi @Evelyn0 @IoannisKountouris @emilhe @JrtPec I also needed this stuff for a project so have done a deep dive to solve this properly for once. I have added a subpackage geo which you can see here: https://github.com/EnergieID/entsoe-py/tree/master/entsoe/geo

Many bidding zones have been added but not yet all, main example being italy. I will add those soon. I hope this helps people how like me would like to make some maps. I am closing this issue now, if you have further questions about the geo subpackage feel free to open a new issue.
