### ISSUE TITLE
crossborder_flows: help

### ISSUE THREAD

**Issue by rablancomo** [EnergieID/entsoe-py#62]
Hello
This is my first issue in GitHub.
I am trying to use this project to build a PowerBI application.
I can use some functions (installed_generation_capacity, unavailability_of_generation_units, query_generation, withdrawn_unavailability_of_generation_units).
I don't get any data when I try to use crossborder_flows.
The message is "The table is empty".
No error is returned.
Can you help me?
Thank you

CODE:
from entsoe import EntsoePandasClient
import pandas as pd
client = EntsoePandasClient(api_key='KEY')
start = pd.Timestamp('20200101', tz='Europe/Brussels')
end = pd.Timestamp('20210101', tz='Europe/Brussels')
df = client.query_crossborder_flows('ES', 'FR', start=start, end=end)
print (df)

**Comment by tranberg** [comment]
Your example code works fine for me. Did you get it working?

**Comment by JrtPec** [comment]
Just tested this example with the new version 0.3.0 that will release soon; and it works fine.
