### ISSUE TITLE
Time periods?

### ISSUE THREAD

**Issue by rablancomo** [EnergieID/entsoe-py#63]
These are my first steps into Python.
How can I get the time period as a column when I use this code?
I think this is important when the hour change form winter to summer time (or summer to winter)
Can the functions return the time period?
Thank you.

*************************************************************************************
CODE
from entsoe import EntsoePandasClient
import pandas as pd
client = EntsoePandasClient(api_key='KEY')
start = pd.Timestamp('20200101', tz='Europe/Brussels')
end = pd.Timestamp('20210101', tz='Europe/Brussels')
country_code = 'ES' 
# methods that return Pandas DataFrames
ts = client.query_generation(country_code, start=start,end=end, psr_type=None)
print (ts)

**Comment by todor1** [comment]
Hi, 
If i understood correctly you would like to have the datetime index as a column in the dataframe.
You could check the df.reset_index() method
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html

**Comment by rablancomo** [comment]
It's too difficult for me. 
I have generated the hourly periods in PowerBI.
Thank you.

**Comment by tranberg** [comment]
The time is already included in the response. Have a look at `ts.index`. The object `ts` is a [pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html). A very powerful class if you're familiar with it's methods.

You can set the time as a regular column with `ts["timepreiod"] = ts.index`.

**Comment by JrtPec** [comment]
This is a general "working with timeseries in Pandas" question, not specifically related to entsoe-py.

That said: All responses given by the library are timezone-aware, and localized to the timezone of the area you request data from. It automatically handles winter and summer time.
