### ISSUE TITLE
Generation Forecasts for Wind and Solar

### ISSUE THREAD

**Issue by ThomasAuriel** [EnergieID/entsoe-py#65]
The [A69 document](https://transparency.entsoe.eu/content/static_content/Static%20content/knowledge%20base/data-views/generation/Data-view%20Generation%20Forecasts%20-%20Day%20Ahead%20for%20Wind%20and%20Solar.html) is not correctly downloaded.

Their is three levels of forecast : Current, Day ahead and Intraday. Only Day Ahead is transcribe in the returned dataframe.
(It is also possible I make something wrong with the code).

**Comment by JrtPec** [comment]
The method `query_wind_and_solar_forecast` has a default `process_type = 'A01'`, which is day-ahead.
I've tried using the parameters `process_type = 'A18'` (intraday total), and `'A40'` (intraday process), and these seem to work for me.

Is that what you would need?

**Comment by fboerman** [comment]
hi @ThomasAuriel as @JrtPec explained this is already possible so I am closing this issue as part of a little cleanup. if you have  trouble using the solution feel free to reopen
