### ISSUE TITLE
Some periods are missing

### ISSUE THREAD

**Issue by rablancomo** [EnergieID/entsoe-py#66]
Hi!
I'm using the generation query for several years and countires. 
I count the number of different periods and some periods are missing. The function doesn't return the date. I don't know wich ones are missing.

COUNT
COUNTRIE   -//-  2018 -//-    2019 
ES               -//- 8759     -//- 8755 
FR               -//- 8757     -//- 8751
IT                -//- 8751     -//- 8760
PT               -//- 8760     -//- 8760

I use the same code changing the countrie.

CODE
from entsoe import EntsoePandasClient
import pandas as pd
client = EntsoePandasClient(api_key='MY KEY')
start = pd.Timestamp('20180101', tz='Europe/Brussels')
end = pd.Timestamp('20190101', tz='Europe/Brussels')
country_code = 'FR' 
ts = client.query_generation(country_code, start=start,end=end, psr_type=None)
print (ts)

**Comment by tranberg** [comment]
This is caused by missing data in the ENTSO-E Transparency Platform from which the API reads.

Using your example code above:
```
start = pd.Timestamp('20180101', tz='Europe/Brussels')
end = pd.Timestamp('20191231', tz='Europe/Brussels')
country_code = 'FR'
ts = client.query_generation(country_code, start=start,end=end, psr_type=None)
```
Here's how to inspect what hours are missing:
```
set(pd.date_range(start, end, freq="1H")) - set(ts.index)
```
Output:
```
{Timestamp('2018-03-26 09:00:00+0200', tz='Europe/Brussels', freq='H'),
 Timestamp('2018-12-14 05:00:00+0100', tz='Europe/Brussels', freq='H'),
 Timestamp('2018-12-14 06:00:00+0100', tz='Europe/Brussels', freq='H'),
 Timestamp('2019-01-01 00:00:00+0100', tz='Europe/Brussels', freq='H')}
```
I hope this helps.

**Comment by rablancomo** [comment]
Thank you for your help. 
I am starting to program in Python and this helps me a lot.

**Comment by JrtPec** [comment]
This seems to be an issue with the Entsoe API not returning data, which is unfortunate, but not something that we can fix in this library... sorry
