### ISSUE TITLE
Cyprus DOMAIN_MAPPINGS and TIMEZONE_MAPPINGS missing

### ISSUE THREAD

**Issue by ThanosGkou** [EnergieID/entsoe-py#67]
Cyprus mappings are missing in the mappings dictionaries. 
What I could find for sure is the fix for DOMAIN_MAPPINGS & TIMEZONE_MAPPINGS, 

item for DOMAIN_MAPPINGS:         'CY': '10YCY-1001A0003J',
item for TIMEZONE_MAPPINGS:      'CY': 'Asia/Nicosia'

**Comment by JrtPec** [comment]
Added in version 0.3.0.

You can use `CY`, `Area.CY`, or `10YCY-1001A0003J` anywhere `country_code` is asked ;-)

**Comment by ThanosGkou** [comment]
I'm sorry but this does not work for me. Does it really work for you? ( I
note that almost all other countries work properly for me too).


Στις Κυρ, 18 Οκτ 2020 στις 11:06 μ.μ., ο/η Jan Pecinovsky <
notifications@github.com> έγραψε:

**Comment by JrtPec** [comment]
This works for me:

```python
from entsoe import EntsoePandasClient, Area
import pandas as pd

start = (pd.Timestamp.today(tz='Asia/Nicosia') - pd.Timedelta(days=1)).normalize()
end = start + pd.Timedelta(days=1)

client = EntsoePandasClient(api_key=<api_key>)

client.query_load(country_code=Area.CY, start=start, end=end)
```

However, I've noticed that there are no day-ahead prices for Cyprus on transparency.entsoe.eu, so obviously entsoe-py cannot download that data either...

**Comment by ThanosGkou** [comment]
Ok I'll try it again. Yes, I wasn't talking about actual data
unavailability.
Thank you

Στις Δευ, 19 Οκτ 2020 στις 1:41 μ.μ., ο/η Jan Pecinovsky <
notifications@github.com> έγραψε:
