### ISSUE TITLE
Generation Forecast Austria contains unexplained zeros

### ISSUE THREAD

**Issue by Nakhlemario** [EnergieID/entsoe-py#74]
I am running query_generation_forecast for 'AT' using version 0.3.0 (pip installed)  and am receiving the following, as an example:
2017-09-28 18:00:00+00:00    7724.0
2017-09-28 19:00:00+00:00       0.0
2017-09-28 20:00:00+00:00       0.0
2017-09-28 21:00:00+00:00    5145.0

When the entsoe data platform shows (CET):
20:00 - 21:00  7724 
21:00 - 22:00  5541 
22:00 - 23:00  5408 
23:00 - 00:00  5145
The corresponding Scheduled Consumption in the data platform is 0.

As you can see some returned values are correct, others are just zero. This behaviour happens consistently every day and doesn't seem to follow a specific intuitive rule. 
Before updating to 0.3.0, I had exactly the same issue with 'DE-AT-LU'

**Comment by JrtPec** [comment]
Interesting bug!

So here's what happens.

This call:
```python
client.query_generation_forecast(
    country_code=Area.AT,
    start=pd.Timestamp('2017-09-28 18:00:00+00:00'),
    end=pd.Timestamp('2017-09-28 21:00:00+00:00')
)
```

Gets this response from server:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<GL_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0">
	<mRID>6289f46307884a1e88eefbe36564c8ad</mRID>
	<revisionNumber>1</revisionNumber>
	<type>A71</type>
	<process.processType>A01</process.processType>
	<sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>
	<sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>
	<receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>
	<receiver_MarketParticipant.marketRole.type>A33</receiver_MarketParticipant.marketRole.type>
	<createdDateTime>2020-10-21T10:16:35Z</createdDateTime>
	<time_Period.timeInterval>
		<start>2017-09-27T22:00Z</start>
		<end>2017-09-28T22:00Z</end>
	</time_Period.timeInterval>
	<TimeSeries>
		<mRID>1</mRID>
		<businessType>A01</businessType>
		<objectAggregation>A01</objectAggregation>
		<inBiddingZone_Domain.mRID codingScheme="A01">10YAT-APG------L</inBiddingZone_Domain.mRID>
		<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>
		<curveType>A01</curveType>
		<Period>
			<timeInterval>
				<start>2017-09-27T22:00Z</start>
				<end>2017-09-28T22:00Z</end>
			</timeInterval>
			<resolution>PT60M</resolution>
				<Point>
					<position>1</position>
                        <quantity>5107</quantity>
				</Point>
				<Point>
					<position>2</position>
                        <quantity>5052</quantity>
				</Point>
				<Point>
					<position>3</position>
                        <quantity>5079</quantity>
				</Point>
				<Point>
					<position>4</position>
                        <quantity>4948</quantity>
				</Point>
				<Point>
					<position>5</position>
                        <quantity>4946</quantity>
				</Point>
				<Point>
					<position>6</position>
                        <quantity>5106</quantity>
				</Point>
				<Point>
					<position>7</position>
                        <quantity>5644</quantity>
				</Point>
				<Point>
					<position>8</position>
                        <quantity>7208</quantity>
				</Point>
				<Point>
					<position>9</position>
                        <quantity>7430</quantity>
				</Point>
				<Point>
					<position>10</position>
                        <quantity>7398</quantity>
				</Point>
				<Point>
					<position>11</position>
                        <quantity>7002</quantity>
				</Point>
				<Point>
					<position>12</position>
                        <quantity>6402</quantity>
				</Point>
				<Point>
					<position>13</position>
                        <quantity>5810</quantity>
				</Point>
				<Point>
					<position>14</position>
                        <quantity>5802</quantity>
				</Point>
				<Point>
					<position>15</position>
                        <quantity>5764</quantity>
				</Point>
				<Point>
					<position>16</position>
                        <quantity>5709</quantity>
				</Point>
				<Point>
					<position>17</position>
                        <quantity>6080</quantity>
				</Point>
				<Point>
					<position>18</position>
                        <quantity>7241</quantity>
				</Point>
				<Point>
					<position>19</position>
                        <quantity>7966</quantity>
				</Point>
				<Point>
					<position>20</position>
                        <quantity>8122</quantity>
				</Point>
				<Point>
					<position>21</position>
                        <quantity>7724</quantity>
				</Point>
				<Point>
					<position>22</position>
                        <quantity>5541</quantity>
				</Point>
				<Point>
					<position>23</position>
                        <quantity>5408</quantity>
				</Point>
				<Point>
					<position>24</position>
                        <quantity>5145</quantity>
				</Point>
		</Period>
	</TimeSeries>
	<TimeSeries>
		<mRID>2</mRID>
		<businessType>A01</businessType>
		<objectAggregation>A01</objectAggregation>
		<outBiddingZone_Domain.mRID codingScheme="A01">10YAT-APG------L</outBiddingZone_Domain.mRID>
		<quantity_Measure_Unit.name>MAW</quantity_Measure_Unit.name>
		<curveType>A01</curveType>
		<Period>
			<timeInterval>
				<start>2017-09-27T22:00Z</start>
				<end>2017-09-28T22:00Z</end>
			</timeInterval>
			<resolution>PT60M</resolution>
				<Point>
					<position>1</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>2</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>3</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>4</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>5</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>6</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>7</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>8</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>9</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>10</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>11</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>12</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>13</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>14</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>15</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>16</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>17</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>18</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>19</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>20</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>21</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>22</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>23</position>
                        <quantity>0</quantity>
				</Point>
				<Point>
					<position>24</position>
                        <quantity>0</quantity>
				</Point>
		</Period>
	</TimeSeries>
</GL_MarketDocument>
```

Notice how there's two timeseries', one with values and one with zero's, with the same time interval, same header, ...
**So this is the source of the problem, something is wrong with the server response**

These two timeseries' are parsed correctly, and are combined. The index is sorted, and duplicates are removed. Due to the way this sorting works, sometimes an actual value is on top, sometime a zero is on top. The duplicate removal retains either the value or the zero, resulting in the bug.

So:
I will first contact ENTSO-E and ask about this bug on their part.
We could also program something that checks if there are series with identical indices about to be combined, and one of them contains nothing but zero's, we should drop that series.

**Comment by Nakhlemario** [comment]
Thanks for the quick analysis. The other time series has to be the Scheduled Consumption - which I assume is the power consumed by producers, like for example to pump water to a higher reservoir - and is 0 most of the times ([Example](https://transparency.entsoe.eu/generation/r2/dayAheadAggregatedGeneration/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=28.09.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=28.09.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YAT-APG------L!CTY|10YAT-APG------L&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))). In the case of Germany, the Scheduled Consumption column is completely empty, which probably explains why this problem doesn't occur for 'DE' ([Example](https://transparency.entsoe.eu/generation/r2/dayAheadAggregatedGeneration/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=28.09.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=28.09.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10Y1001A1001A83F!CTY|10Y1001A1001A83F&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)))

**Comment by JrtPec** [comment]
Oh I see! We've actually encountered this before...

I can fix this, but help me out as to how:

- Parsing returns 2 columns (_In_ & _Out_).
- Parsing returns the net generation, so we subtract _Out_ from _In_.
- Parsing returns the gross generation, so we omit _Out_.

I'm actually like option 1 the best (explicit is better than implicit), although it changes the return type and may break some people's code.
Apparently, we've already solved this problem once, and `query_generation` uses it, but there option 2 has been picked, so production and consumption are subtracted. See #24 for that discussion it's all coming back to me now...

What do you think?

**Comment by Nakhlemario** [comment]
- For most countries, the column _Out_ does not contain any data at all, so either option will not make a difference (assuming that in option 1, column  _Out_ will not be returned if it is empty)
- For countries that do have data in column _Out_, the current output is totally wrong. Any of the three options would be a big improvement. 

Having said that, I agree that option 1 is the best. Data downloaded manually from the entsoe data platform contains both columns, which I think should be used as a reference. Option 2 creates a new variable that is not found in entsoe and option 3 disregards the net generation, which I am sure there is use cases for.

Hope this helps. For my use case, either option is fine.

**Comment by JrtPec** [comment]
#75 should solve it. It seems to work fine for the most part...

There is however a new artefact that's popped up that I've described in #24, don't know how to approach that one yet.

**Comment by JrtPec** [comment]
Solution deployed in 0.3.2
