### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by PetricaR** [EnergieID/entsoe-py#79]
Hello,

I have these problem with the API. Can you help me! Thanks a lot! 

MaxRetryError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A44&in_Domain=10YRO-TEL------P&out_Domain=10YRO-TEL------P&securityToken=XXXXXXXXXX&periodStart=202010112200&periodEnd=202010122200 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

**Comment by jpaduart** [comment]
This smells like a proxy issue. Are you behind a corporate proxy/firewall?
Did you try a simple requests example ?
E.g. https://requests.readthedocs.io/en/master/user/quickstart/

Johan.

Op di 27 okt. 2020 om 09:39 schreef Radan Petrica <notifications@github.com

**Comment by PetricaR** [comment]
Dear Johan,
Yes, I am behind in a corporate proxy/firewall.
I have the same problem even for a simple request.

How this can be managed? 

Thank you!

**Comment by jpaduart** [comment]
Google is your friend.
You can specify the "proxies" argument when calling the client.
The documentation of the requests module explains how to set up this
argument:
https://requests.readthedocs.io/en/master/user/advanced/

Johan

Op di 27 okt. 2020 om 13:45 schreef Radan Petrica <notifications@github.com

**Comment by JrtPec** [comment]
I hope this was resolved eventually? I'm closing the issue regardless since it seems to be a proxy/firewall issue, not directly related to the code.

**Comment by syafiqadibafham** [comment]
can i get the step by step to solve this problem?
