### ISSUE TITLE
query_contracted_reserve_prices error

### ISSUE THREAD

**Issue by PetricaR** [EnergieID/entsoe-py#81]
Hello,

There are some errors on API for getting data for the "**query_contracted_reserve_prices**" and "**query_contracted_reserve_amount** for Romanian Country". 

---------------------------------------------------------------------------
NoMatchingDataError                       Traceback (most recent call last)
<ipython-input-47-56d44ee03d41> in <module>
----> 1 client.query_contracted_reserve_amount(country_code=Area.RO, start=start, end=end, type_marketagreement_type='A01')

f:\ML\Git_Repo\Market-Price-Forecast\1. DAM_Market_Price_Forecast\env\lib\site-packages\entsoe\entsoe.py in year_wrapper(start, end, *args, **kwargs)
    835         if sum([f is None for f in frames]) == len(frames):
    836             # All the data returned are void
--> 837             raise NoMatchingDataError
    838 
    839         df = pd.concat(frames, sort=True)

NoMatchingDataError:

Also Day-Ahead Market Price , Actual Load, Load Forecast, Generation Forecast, Crossborder Flows, Scheduled Exchanges doesn't have a default column name, but this can be solved with pandas DataFrame function.

Petrica

**Comment by jpaduart** [comment]
Did you check whether any data is available from the transparency website?

**Comment by PetricaR** [comment]
Yes, there is data for RO Country:

**Comment by PetricaR** [comment]
Yes, there is data for RO [Country](https://transparency.entsoe.eu/balancing/r2/pricesOfActivatedBalancingEnergy/show?name=&defaultValue=false&viewType=TABLE&areaType=MBA&atch=false&dateTime.dateTime=24.10.2020+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=24.10.2020+00:00|CET|DAYTIMERANGE&reserveType.values=A96&reserveType.values=A97&reserveType.values=A98&CTY|10YRO-TEL------P|SINGLE=CTY|10YRO-TEL------P|SINGLE&marketArea.values=CTY|10YRO-TEL------P!MBA|10YRO-TEL------P&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)).

**Comment by PetricaR** [comment]
I saw that on ENTSO website are two available options for **Prices of Activated Balancing Energy**
1. Area
2. Market Balance Area.

For RO Country there is no data available for the option no 1 (Area), but the data is available for the option no 2 (Market Balance Area). 

So, maybe here is the problem.

**Comment by JrtPec** [comment]
I've looked around a bit, but as far as I can tell from the docs ([and this useful presentation](https://eepublicdownloads.entsoe.eu/clean-documents/EDI/Library/Market_Areas_v2.1.pdf)), Romania is only represented by a single area code.

`10YRO-TEL------P` represents Romania as a Member State, Control Area, Bidding Zone, Scheduling Area and Market Balance Area. This Area code is also used when you request data using the `Area.RO` object.

However, if you manage to find another code we could try, let me know.

**Comment by PetricaR** [comment]
Hi,

I think I have found another code for RO country. For Market Balance Area
"CTY|10YRO-TEL------P!MBA|10YRO-TEL------P" is the full text.  The code is from the next link

https://transparency.entsoe.eu/balancing/r2/imbalance/show?name=&defaultValue=false&viewType=TABLE&areaType=MBA&atch=false&dateTime.dateTime=06.11.2020+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=06.11.2020+00:00|CET|DAYTIMERANGE&marketArea.values=**CTY|10YRO-TEL------P!MBA|10YRO-TEL------P**&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

But the actual code, I suppose is **10YRO-TEL------P!MBA**.

Best regards,
Petrica

**Comment by fboerman** [comment]
@PetricaR I have tested your code with the latest version and it seems to work so I am gonna clean up this issue as part of a little cleanup. if you experience problems again feel free to reopen the issue.
