### ISSUE TITLE
GB seeming to incorrectly resolve in mappings.py

### ISSUE THREAD

**Issue by ditchell** [EnergieID/entsoe-py#82]
Hi guys,

I noticed an issue earlier I thought I'd make you aware of.

When calling **query_load** with **'GB'** as the country it resolves the area to **'10YGB----------A'**, however I believe it should resolve to simply **'GB'** as this is the value that is used to get country load in the [Entsoe API docs](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html).

```python
from entsoe import EntsoePandasClient
import pandas as pd

client = EntsoePandasClient(api_key=ENTSOE_API_KEY)

start = pd.Timestamp('2020-11-1', tz='Europe/London')
end= pd.Timestamp('2020-11-2', tz='Europe/London')

print(client.query_load('GB', start=start, end=end))
```

I'd expect the above to display the data for the **Country Total Load** for United Kingdom however it instead returns the data for the **Bidding Zone**.

Let me know if you need any further information.

Regards,
Ditchell

**Comment by fgenoese** [comment]
According to the [MarketAreas ](https://eepublicdownloads.entsoe.eu/clean-documents/EDI/Library/Market_Areas_v2.1.pdf) documentation '10YGB----------A' points to the bidding zone Great Britain (= England, Scotland, Wales).

What we are indeed missing is UK (= England, Scotland, Wales & Northern Ireland), which is what is reported under the "country" tab of the ENTSO-E Transparency Platform. Code should be '10Y1001A1001A92E' according to the documentation.

**Comment by fgenoese** [comment]
Interestingly, when trying this EIC code I get the following response:

> Delivered Area EIC 10Y1001A1001A92E is not valid.

**Comment by ditchell** [comment]
> Interestingly, when trying this EIC code I get the following response:
> 
> > Delivered Area EIC 10Y1001A1001A92E is not valid.

So for me, when I look at the actually URL generated when doing a **Total Load - Day Ahead / Actual** query on the UK for  country, I just see simply **GB** in there:

`https://transparency.entsoe.eu/load-domain/r2/totalLoadR2/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&dateTime.dateTime=31.10.2020+00:00|WET|DAY&biddingZone.values=CTY|GB!CTY|GB&dateTime.timezone=WET_WEST&dateTime.timezone_input=WET+(UTC)+/+WEST+(UTC+1)`

**Comment by fgenoese** [comment]
Noted, I still think it's worth checking with the Transparency Platform team whether this is intended or not. After all, when querying for Germany (country), we have to use '10Y1001A1001A83F’ and not 'DE'.

**Comment by fgenoese** [comment]
Checked with the TP team: It is planned to change GB country code to the correct EIC code during the Christmas period (when few TP requests are made).

We will update our Python package shortly after.

**Comment by ditchell** [comment]
Great, thank you.

**Comment by fboerman** [comment]
hi @ditchell I have tested your code with the latest version and it seems to work so I am gonna clean up this issue as part of a little cleanup. if you experience problems again feel free to reopen the issue.
