### ISSUE TITLE
Logging definition mismatches

### ISSUE THREAD

**Issue by r4ch45** [EnergieID/entsoe-py#86]
Hello,

Thanks for the package - has saved me a lot of time and effort!

I get a crashing and logging overload when I use the package along with the logging implemented as part of my wider project. 
Code to reproduce:
`import sys, os
import datetime as dt

from entsoe import EntsoePandasClient
import pandas as pd

import logging

# logging setttings
LOGNAME = "entsoe_test"
LOGTOFILE = True  # true = create and send all messages or errors to a log file
LOGFILENEWONSTART = False  # true = create a new file each startup, false = append across multiple startups
LOGCONSOLETOFILE = True  # true = echo the stderr and stdout to the log file as well as application messages, it usually desireable to keep this turned on
LOGFILENAME = "test.log"
LOGLEVEL = "DEBUG"

# global logger variable
logger = logging.getLogger(LOGNAME)

proxies = None
entsoe_api_key = ""

class StreamLogger(object):
    def __init__(self, stream, prefix=""):
        self.stream = stream
        self.prefix = prefix
        self.data = ""

    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

        self.data += data
        tmp = str(self.data)
        if "\x0a" in tmp or "\x0d" in tmp:
            tmp = tmp.rstrip("\x0a\x0d")
            logger.info("%s%s" % (self.prefix, tmp))
            self.data = ""

    def flush(self):
        pass

def init_logging(runid, name=LOGFILENAME):
    print(f"Saving LOGFILE to {name}")

    if LOGTOFILE == True:

        if LOGFILENEWONSTART == True:
            try:
                os.remove(name)
            except:
                None

        hdlr = logging.FileHandler(name)
        formatter = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
        hdlr.setFormatter(formatter)
        logger.addHandler(hdlr)

        if LOGLEVEL == "DEBUG":
            logger.setLevel(logging.DEBUG)
        if LOGLEVEL == "INFO":
            logger.setLevel(logging.INFO)
        if LOGLEVEL == "WARNING":
            logger.setLevel(logging.WARNING)
        if LOGLEVEL == "ERROR":
            logger.setLevel(logging.ERROR)
        if LOGLEVEL == "CRITICAL":
            logger.setLevel(logging.CRITICAL)

        # with this redirect stdout and std error will go to both the consol and the log.
        if LOGCONSOLETOFILE == True:

            sys.stdout = StreamLogger(sys.stdout, ":  [stdout] ")
            sys.stderr = StreamLogger(sys.stderr, ":  [stderr] ")

    # log some useful info to the log file
    logger.info("---------------------------------")
    logger.info("---------------------------------")
    logger.info(f"RUNID: {runid}")
    try:
        logger.info(f"USER: {os.getlogin()}")
        logger.info(f"COMPUTERNAME: {os.environ['COMPUTERNAME']}")
        logger.info(f"OS: {os.environ['OS']}")
        logger.info(f"CODE EXE: {sys.executable}")
    except:
        pass

def writelog(level, msg):

    if LOGTOFILE == True:

        if level == "DEBUG":
            logger.debug(LOGNAME + ":  " + msg)
        if level == "INFO":
            logger.info(LOGNAME + ":  " + msg)
        if level == "WARNING":
            logger.warning(LOGNAME + ":  " + msg)
        if level == "ERROR":
            logger.error(LOGNAME + ":  " + msg)
        if level == "CRITICAL":
            logger.critical(LOGNAME + ":  " + msg)
        if level == "EXCEPTION":
            logger.exception(LOGNAME + ":  " + msg)

    else:  # at least tell the console
        if level == "DEBUG":
            print("DEBUG: " + LOGNAME + ":  " + msg)
        if level == "INFO":
            print("INFO: " + LOGNAME + ":  " + msg)
        if level == "WARNING":
            print("WARNING: " + LOGNAME + ":  " + msg)
        if level == "ERROR":
            print("ERROR: " + LOGNAME + ":  " + msg)
        if level == "CRITICAL":
            print("CRITICAL: " + LOGNAME + ":  " + msg)
        if level == "EXCEPTION":
            print("EXCEPTION: " + LOGNAME + ":  " + msg)

init_logging("TEST", name="test.log")

writelog("INFO", "Setting up")

client = EntsoePandasClient(api_key=entsoe_api_key, proxies=proxies)

start = dt.date(2020, 11, 15)
end = dt.date(2020, 11, 19)

start = pd.Timestamp(start, tz="Europe/London")
end = pd.Timestamp(end, tz="Europe/London")

country = "FR"
writelog("DEBUG", f"ENTSOE: Gathering Data for {country}")
df_country = client.query_load_forecast(country, start=start, end=end).to_frame(
    f"{country}_LOAD_FORECAST"
)

writelog("INFO", "Done")
`

To fix it, within the entsoe.py I can define the logging object like:
`logger = logging.getLogger(__name__)`
and use like:
`logger.debug(f'Performing request to {URL} with params {params}')`

Does that work as a fix?

**Comment by r4ch45** [comment]
The formatting went a bit off there - apologies!

**Comment by r4ch45** [comment]
Example output to logger:
2020-11-17 15:11:30,959 INFO ---------------------------------
2020-11-17 15:11:30,959 INFO ---------------------------------
2020-11-17 15:11:30,959 INFO RUNID: TEST
2020-11-17 15:11:30,960 INFO USER: 
2020-11-17 15:11:30,960 INFO COMPUTERNAME: 
2020-11-17 15:11:30,960 INFO OS: Windows_NT
2020-11-17 15:11:30,960 INFO CODE EXE: 
2020-11-17 15:11:31,057 INFO GIT HASH: 
2020-11-17 15:11:31,057 INFO demand_forecasting:  Setting up
2020-11-17 15:11:31,114 DEBUG demand_forecasting:  ENTSOE: Gathering Data for load_forecast
2020-11-17 15:11:31,114 DEBUG demand_forecasting:  ENTSOE: Gathering Data for FR
2020-11-17 15:11:31,969 DEBUG demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,969 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,970 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,970 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,979 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,981 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,984 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
2020-11-17 15:11:31,988 INFO :  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL
INFO:demand_forecasting::  [stderr] DEBUG:demand_forecasting:demand_forecasting:  ENTSOE: Gathering Data for NL

etc.

**Comment by S-Black** [comment]
Try to add
``logger.propagate = False```
just below where you declare you logger object.

**Comment by fboerman** [comment]
hi @r4ch45 did the last comment fix your issue?

**Comment by piotrpochec** [comment]
This is an old topic but I've had some problems with this. I agree with @r4ch45 - their solution is the way to go. I proposed a PR along these lines.
