### ISSUE TITLE
Refactoring and updating of unit tests

### ISSUE THREAD

**Issue by fleimgruber** [EnergieID/entsoe-py#87]
Proposal to move unit tests to the conventional top level `tests` directory. For a first draft, please see https://github.com/fleimgruber/entsoe-py/commit/4fe0fb77bb19dcb5647767415da12f02d3fc5215. I tried to separate into tests related to `domains` and `clients`. Is the test code still relevant or does it need to be adapted due to internal API changes? E.g. for `test_domains` I get 9 tests passing and one failing like this (because of binary string vs. `str`):

```
FAILED          [ 10%]
tests\test_clients.py:23 (EntsoeRawClientTest.test_basic_queries)
self = <tests.test_clients.EntsoeRawClientTest testMethod=test_basic_queries>

    def test_basic_queries(self):
        queries = [
            self.client.query_day_ahead_prices,
            self.client.query_load,
            self.client.query_wind_and_solar_forecast,
            self.client.query_load_forecast,
            self.client.query_generation,
            self.client.query_generation_forecast,
            self.client.query_installed_generation_capacity,
            self.client.query_imbalance_prices
        ]
        for query in queries:
            text = query(country_code=self.country_code, start=self.start,
                         end=self.end)
>           self.assertIsInstance(text, str)
E           AssertionError: b'PK\x03\x04\x14\x00\x08\x08\x08\x00...' is not an instance of <class 'str'>

test_clients.py:38: AssertionError
```

**Comment by fboerman** [comment]
hi @fleimgruber this seems like a good idea. Could you provide a pull request for it?

**Comment by fleimgruber** [comment]
@fboerman please see https://github.com/EnergieID/entsoe-py/pull/131.

**Comment by fboerman** [comment]
hi @fleimgruber thank you lets move the discussion to there
