### ISSUE TITLE
requirements.txt not being used

### ISSUE THREAD

**Issue by aferrero23** [EnergieID/entsoe-py#88]
I've noticed that you have a requirements.txt with 7 libraries and the version required for each of them.
However, in setup.py there's a line:
`install_requires=['requests', 'pytz', 'beautifulsoup4', 'pandas']`
which is the responsible of installing the libraries required. There is no version specified and that's causing problems in my code.

**Comment by fboerman** [comment]
@aferrero23 could you specify what kind of problems? Because im tempted to change the requirements to what the setup says. I never have problems with taking the latest versions of these packages.

**Comment by aferrero23** [comment]
@fboerman correct me if I'm wrong, but the way I see it is that there is not going to be any problem installing the latest version, the problems comes when it installs the latests version with the install_requires array and that version is greater than the version specified in the requirements.txt file. For instance, if I just pip install pandas with the install_requires array, I install the latest stable version which I think is 1.3.2, and the version in the requirements file is limited to pandas~=1.0.3. I assume that in this case the library was design for pandas~=1.0.3 and not for latest versions.

**Comment by fboerman** [comment]
@aferrero23 ah like that. that is not a problem, the requirements is pretty old and the library works fine with latest versions. Pandas is very stable anyway. I will remove the unneeded version constraints from the requirements
