### ISSUE TITLE
DE-AT-LU bidding zone split

### ISSUE THREAD

**Issue by JrtPec** [EnergieID/entsoe-py#9]
I have found this on [the Entsoe-E news section](https://transparency.entsoe.eu/news/widget?id=5b7c1e9b5092e75a10bab903) concerning a 'DE-AT-LU' bidding zone split that is coming up:

> Dear Users,
>
>Please be informed, that we will start preparation of the platform for DE-AT-LU bidding zone split on >the 23rd of August. BZN|DE-AT-LU will be separated into 2 new bidding zones BZN|DE-LU and >BZN|AT.
> 
>New bidding zones will be active from the 1st of October, however, first data submissions, like month >ahead forecasts, are expected from the 1st of September. 
> 
>Validity end date for BZN|DE-AT-LU is the end of September 2018. 
> 
>EIC codes for new bidding zones:
>BZN|DE-LU - 10Y1001A1001A82H 
>BZN|AT - 10YAT-APG------L (same as control area or country)
> 
>Thanks for your patience and understanding.
> 
>Best Regards
>Transparency Platform Team.

These new EIC codes should be added to the code, while making sure that you can still perform historical queries.

**Comment by JrtPec** [comment]
DE-LU bidding zone was added in b8ccfcaac3aa8d4c6c0beb62f440c19a41291ede, included in 0.2.4

**Comment by Tinkaa** [comment]
Hi,
Related to this, I was wondering: is there a reason that in the mapping BIDDING_ZONES, the country code of Germany (DE) is mapped to the bidding zone DE-AT-LU? 
And that in several functions (e.g. query_load) the bidding zone mapping is used instead of the domain mapping?
I am asking this, because I would like to get all the data of Germany starting in 2017, but now this is throwing the NoMatchingDataError due to DE-AT-LU not containing any data anymore after the change of bidding zones in 2018 (DE-AT-LU --> DE-LU).

**Comment by JrtPec** [comment]
To give a specific answer:
If you want German data before October 2018, use `DE`. (which is mapped to `DE-AT-LU` behind the scenes.
If you want German data after October 2018, explicitly type `DE-LU`.

Some general comments on how it got to this point:
These mappings were added once, some time ago, when the only user of the code was me, and I only needed data from Belgium which has only one bidding zone. So it made sense to me to map the parameter `BE`, so I wouldn't have to type this complex domain code every time.

Since then I've learned that these mappings change, bidding zones merge or split, some API-calls take domains, others take bidding zones... frankly it's a mess.

So, feel free to update the code to something more useful and I will be happy to approve the update.

**Comment by Tinkaa** [comment]
Great, thank you for the explanation. It seems indeed like a mess and I am surprised it is working most of the time. I tried to come up with an easy solution, but so far didn't succeed and for my purposes it is good enough to just make two different calls for Germany. 
I will update the code if I come up with a smart way to order it :)

**Comment by kappe79** [comment]
Hi. I have a problem to download the data of DE-LU, no problem with the other zones. Is there a solution?

KeyError: 'DE-LU'
